import { RoutineCategory, RoutineItem, RoutineTimeOfDay } from '@/types/routine';

export const ROUTINE_TIME_BLOCKS: {
  key: RoutineTimeOfDay;
  label: string;
  emoji: string;
  hours: string;
  startHour: number;
  endHour: number;
  color: string;
}[] = [
  {
    key: 'MORNING',
    label: 'Morning Kickstart',
    emoji: '🌅',
    hours: '05:00 AM - 11:59 AM',
    startHour: 5,
    endHour: 12,
    color: '#FFB020',
  },
  {
    key: 'AFTERNOON',
    label: 'Afternoon Focus',
    emoji: '☀️',
    hours: '12:00 PM - 04:59 PM',
    startHour: 12,
    endHour: 17,
    color: '#00B4FF',
  },
  {
    key: 'EVENING',
    label: 'Evening Wind-down',
    emoji: '🌆',
    hours: '05:00 PM - 08:59 PM',
    startHour: 17,
    endHour: 21,
    color: '#A78BFA',
  },
  {
    key: 'NIGHT',
    label: 'Night Recovery',
    emoji: '🌙',
    hours: '09:00 PM - 04:59 AM',
    startHour: 21,
    endHour: 5,
    color: '#89FE00',
  },
];

export const CATEGORY_CONFIG: Record<
  RoutineCategory,
  { label: string; icon: string; color: string }
> = {
  HEALTH: { label: 'Health', icon: 'favorite', color: '#FF4D6D' },
  FITNESS: { label: 'Fitness', icon: 'fitness-center', color: '#A78BFA' },
  NUTRITION: { label: 'Nutrition', icon: 'restaurant', color: '#89FE00' },
  MIND: { label: 'Mindfulness', icon: 'self-improvement', color: '#89CEFF' },
  FINANCE: { label: 'Finance', icon: 'account-balance-wallet', color: '#20C997' },
  REST: { label: 'Rest & Sleep', icon: 'bedtime', color: '#748CAB' },
};

export const DEFAULT_ROUTINES: RoutineItem[] = [
  // MORNING
  {
    id: 'sys_morning_water',
    title: '500ml Warm Water & Hydration',
    description: 'Jumpstarts metabolism and cellular rehydration',
    timeOfDay: 'MORNING',
    targetTime: '07:00 AM',
    category: 'HEALTH',
    icon: 'water-drop',
    color: '#89CEFF',
    isSystem: true,
    linkedAction: 'HYDRATION',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000000,
  },
  {
    id: 'sys_morning_stretch',
    title: '10 Min Morning Mobility & Stretch',
    description: 'Relieves spine tension and awakens nervous system',
    timeOfDay: 'MORNING',
    targetTime: '07:30 AM',
    category: 'FITNESS',
    icon: 'accessibility-new',
    color: '#A78BFA',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000001,
  },
  {
    id: 'sys_morning_vitamins',
    title: 'Take Morning Vitamins & Medicine',
    description: 'Omega-3, Vitamin D3, and daily supplements',
    timeOfDay: 'MORNING',
    targetTime: '08:00 AM',
    category: 'HEALTH',
    icon: 'medication',
    color: '#FFB020',
    isSystem: true,
    linkedAction: 'MEDICINE',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000002,
  },
  {
    id: 'sys_morning_sunlight',
    title: '15 Min Natural Sunlight Exposure',
    description: 'Sets circadian clock and boosts natural cortisol surge',
    timeOfDay: 'MORNING',
    targetTime: '08:30 AM',
    category: 'MIND',
    icon: 'wb-sunny',
    color: '#FFD166',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000003,
  },

  // AFTERNOON
  {
    id: 'sys_afternoon_lunch',
    title: 'Nutrient-Dense Whole Food Lunch',
    description: 'High protein & colorful greens, zero processed food',
    timeOfDay: 'AFTERNOON',
    targetTime: '01:00 PM',
    category: 'NUTRITION',
    icon: 'restaurant',
    color: '#89FE00',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000004,
  },
  {
    id: 'sys_afternoon_walk',
    title: '5,000 Steps Midday Movement Walk',
    description: 'Lowers postprandial glucose and boosts afternoon energy',
    timeOfDay: 'AFTERNOON',
    targetTime: '02:30 PM',
    category: 'FITNESS',
    icon: 'directions-walk',
    color: '#00B4FF',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000005,
  },

  // EVENING
  {
    id: 'sys_evening_workout',
    title: 'Daily Workout or 5km Cardio Run',
    description: 'Hypertrophy resistance session or zone 2 aerobic cardio',
    timeOfDay: 'EVENING',
    targetTime: '06:00 PM',
    category: 'FITNESS',
    icon: 'fitness-center',
    color: '#A78BFA',
    isSystem: true,
    linkedAction: 'WORKOUT',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000006,
  },
  {
    id: 'sys_evening_expense',
    title: 'Daily Financial & Expense Review',
    description: 'Check daily spending and budget compliance',
    timeOfDay: 'EVENING',
    targetTime: '07:30 PM',
    category: 'FINANCE',
    icon: 'account-balance-wallet',
    color: '#20C997',
    isSystem: true,
    linkedAction: 'EXPENSE',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000007,
  },
  {
    id: 'sys_evening_dinner',
    title: 'Dinner Completed Before 8:00 PM',
    description: 'Allows 3 hours digestion buffer before sleep',
    timeOfDay: 'EVENING',
    targetTime: '08:00 PM',
    category: 'NUTRITION',
    icon: 'dinner-dining',
    color: '#FF9F1C',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000008,
  },

  // NIGHT
  {
    id: 'sys_night_fasting',
    title: 'Start Intermittent Fast Window',
    description: 'Initiates cellular autophagy and overnight fat burn',
    timeOfDay: 'NIGHT',
    targetTime: '09:00 PM',
    category: 'HEALTH',
    icon: 'timer',
    color: '#89CEFF',
    isSystem: true,
    linkedAction: 'FASTING',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000009,
  },
  {
    id: 'sys_night_screen',
    title: 'Screen-Free 30 Mins Before Bed',
    description: 'Protects natural melatonin release and deep sleep phase',
    timeOfDay: 'NIGHT',
    targetTime: '10:30 PM',
    category: 'REST',
    icon: 'phonelink-off',
    color: '#FF6B6B',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000010,
  },
  {
    id: 'sys_night_reading',
    title: '15 Mins Book Reading or Reflection',
    description: 'Calms central nervous system for restorative sleep',
    timeOfDay: 'NIGHT',
    targetTime: '11:00 PM',
    category: 'MIND',
    icon: 'menu-book',
    color: '#748CAB',
    isSystem: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    createdAt: 1700000000011,
  },
];
