/**
 * MENTOR: Demo fasting history — __DEV__ only when API returns empty.
 * Production empty state stays honest ("No past fasts yet").
 */

import type { FastingSessionStatus } from '@/types/fasting';

function daysAgoIso(days: number, hour = 20, minute = 0) {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

/** Three outcomes: Completed Goal · Ended Early · Exceeded Goal */
export const DEMO_FASTING_HISTORY: FastingSessionStatus[] = [
  {
    sessionId: 'demo-completed',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(1, 20, 0),
    endedAt: daysAgoIso(0, 12, 15),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60 + 15,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-early',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(2, 20, 0),
    endedAt: daysAgoIso(1, 10, 45),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 14 * 60 + 45,
    remainingMinutes: 75,
    progressPercent: 92,
    goalMet: false,
  },
  {
    sessionId: 'demo-exceeded',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(3, 19, 0),
    endedAt: daysAgoIso(2, 13, 5),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 18 * 60 + 5,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-omad',
    protocol: '20:4',
    status: 'COMPLETED',
    startedAt: daysAgoIso(5, 20, 0),
    endedAt: daysAgoIso(4, 16, 0),
    endReason: 'MANUAL',
    targetMinutes: 20 * 60,
    elapsedMinutes: 20 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-lastweek-1',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(8, 20, 30),
    endedAt: daysAgoIso(7, 12, 30),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-lastweek-2',
    protocol: '18:6',
    status: 'COMPLETED',
    startedAt: daysAgoIso(10, 19, 0),
    endedAt: daysAgoIso(9, 13, 30),
    endReason: 'MANUAL',
    targetMinutes: 18 * 60,
    elapsedMinutes: 18 * 60 + 30,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-lastmonth-1',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(25, 20, 0),
    endedAt: daysAgoIso(24, 12, 0),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-lastmonth-2',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: daysAgoIso(32, 21, 0),
    endedAt: daysAgoIso(31, 13, 10),
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60 + 10,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  // 2025 Historical Sessions
  {
    sessionId: 'demo-2025-1',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: '2025-11-14T20:00:00.000Z',
    endedAt: '2025-11-15T12:00:00.000Z',
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-2025-2',
    protocol: '20:4',
    status: 'COMPLETED',
    startedAt: '2025-08-20T19:00:00.000Z',
    endedAt: '2025-08-21T15:00:00.000Z',
    endReason: 'MANUAL',
    targetMinutes: 20 * 60,
    elapsedMinutes: 20 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  // 2024 Historical Sessions
  {
    sessionId: 'demo-2024-1',
    protocol: '16:8',
    status: 'COMPLETED',
    startedAt: '2024-06-10T20:30:00.000Z',
    endedAt: '2024-06-11T12:30:00.000Z',
    endReason: 'MANUAL',
    targetMinutes: 16 * 60,
    elapsedMinutes: 16 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
  {
    sessionId: 'demo-2024-2',
    protocol: '18:6',
    status: 'COMPLETED',
    startedAt: '2024-02-18T19:00:00.000Z',
    endedAt: '2024-02-19T13:00:00.000Z',
    endReason: 'MANUAL',
    targetMinutes: 18 * 60,
    elapsedMinutes: 18 * 60,
    remainingMinutes: 0,
    progressPercent: 100,
    goalMet: true,
  },
];
