import { AnalyteKnowledgeDefinition, LabPanelType } from '@/types/ai-report-explainer';

export const LAB_ANALYTE_KNOWLEDGE_BASE: AnalyteKnowledgeDefinition[] = [
  // =========================================================================
  // 1. COMPLETE BLOOD COUNT (CBC - রক্তের সম্পূর্ণ গণনা)
  // =========================================================================
  {
    code: 'HB',
    nameEn: 'Hemoglobin (Hb)',
    nameBn: 'হিমোগ্লোবিন (রক্তের মূল উপাদান)',
    category: 'CBC',
    standardUnit: 'g/dL',
    normalMin: 12.0,
    normalMax: 16.5,
    lowAlertThreshold: 10.0,
    highAlertThreshold: 18.0,
    simpleMeaningBn: 'এটি লোহিত রক্তকণিকার প্রোটিন যা সারা শরীরে অক্সিজেন পৌঁছে দেয় এবং শক্তি জোগায়।',
    ifLowMeaningBn: 'হিমোগ্লোবিন কম থাকা মানে রক্তস্বল্পতা (Anemia)। এর ফলে ক্লান্তি, মাথা ঘোরা, শরীর দুর্বল লাগা ও শ্বাসকষ্ট হতে পারে।',
    ifHighMeaningBn: 'হিমোগ্লোবিন বেশি থাকলে রক্ত ঘন হতে পারে, যা পানিশূন্যতা বা ধূমপানের কারণে হতে পারে।',
    dietAdviceIfAbnormalBn: 'গরুর কলিজা, দেশি মুরগি, লাল শাক, কচু শাক, কাঁচকলা, বেদানা, খেজুর ও ভিটামিন-সি যুক্ত ফল খান।',
    suggestedDoctorQuestionBn: 'স্যার, আমার রক্তস্বল্পতা দূর করতে কোনো আয়রন ও ফলিক এসিড সাপ্লিমেন্ট প্রয়োজন আছে কি?',
  },
  {
    code: 'ESR',
    nameEn: 'ESR (Erythrocyte Sedimentation Rate)',
    nameBn: 'ইএসআর (শরীরে প্রদাহ বা ইনফেকশন সূচক)',
    category: 'CBC',
    standardUnit: 'mm/1st hr',
    normalMin: 0,
    normalMax: 20,
    highAlertThreshold: 50,
    simpleMeaningBn: 'এটি শরীরে কোনো ধরনের দীর্ঘমেয়াদী ইনফেকশন, প্রদাহ বা অ্যালার্জি আছে কিনা তা নির্দেশ করে।',
    ifLowMeaningBn: 'ইএসআর কম থাকা সম্পূর্ণ স্বাভাবিক ও স্বাস্থ্যকর লক্ষণ।',
    ifHighMeaningBn: 'ইএসআর বেশি থাকা নির্দেশ করে শরীরের কোথাও প্রদাহ, বাতব্যথা বা ব্যাকটেরিয়াল ইনফেকশন চলছে।',
    dietAdviceIfAbnormalBn: 'হলুদ-দুধ, আদা চা, রসুন এবং প্রদাহনাশক অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ তাজা শাকসবজি খান।',
    suggestedDoctorQuestionBn: 'স্যার, ইএসআর বৃদ্ধির পেছনে কোনো সুনির্দিষ্ট ইনফেকশন বা জয়েন্ট পেইন দায়ী কিনা তা কিভাবে নিশ্চিত হব?',
  },
  {
    code: 'PLATELET',
    nameEn: 'Platelet Count',
    nameBn: 'প্লাটিলেট (রক্ত জমাট বাঁধার অণুচক্রিকা)',
    category: 'CBC',
    standardUnit: 'x10^3/uL',
    normalMin: 150,
    normalMax: 450,
    lowAlertThreshold: 100,
    highAlertThreshold: 550,
    simpleMeaningBn: 'কেটে গেলে বা রক্তপাত হলে রক্ত জমাট বাঁধিয়ে রক্তক্ষরণ বন্ধ করাই প্লাটিলেটের মূল কাজ।',
    ifLowMeaningBn: 'প্লাটিলেট কমে যাওয়া (Thrombocytopenia) ডেঙ্গু জ্বর, ভাইরাল ইনফেকশন বা লিভার সমস্যার সংকেত দেয়। রক্তক্ষরণের ঝুঁকি বাড়ে।',
    ifHighMeaningBn: 'প্লাটিলেট অতিরিক্ত বেশি হলে রক্তনালীতে রক্ত জমাট বাঁধার ঝুঁকি তৈরি হতে পারে।',
    dietAdviceIfAbnormalBn: 'পেঁপে পাতার রস, ডালিম/বেদানা, কচি ডাবের পানি, ভিটামিন-সি ও পর্যাপ্ত তরল খাবার গ্রহণ করুন।',
    suggestedDoctorQuestionBn: 'স্যার, প্লাটিলেট নিয়ন্ত্রণে রাখতে কোনো বিশেষ সতর্কতা বা রিপিট টেস্ট দরকার আছে কি?',
  },
  {
    code: 'WBC',
    nameEn: 'Total WBC Count',
    nameBn: 'শ্বেত রক্তকণিকা (রোগ প্রতিরোধ যোদ্ধা)',
    category: 'CBC',
    standardUnit: '/uL',
    normalMin: 4000,
    normalMax: 11000,
    lowAlertThreshold: 3500,
    highAlertThreshold: 15000,
    simpleMeaningBn: 'এরা শরীরের রোগ প্রতিরোধ ব্যবস্থার সৈনিক যারা ব্যাকটেরিয়া ও ভাইরাসকে ধ্বংস করে।',
    ifLowMeaningBn: 'ডব্লিউবিসি কমে গেলে শরীরের রোগ প্রতিরোধ ক্ষমতা দুর্বল হয়ে ঘন ঘন ইনফেকশন হতে পারে।',
    ifHighMeaningBn: 'ডব্লিউবিসি বেড়ে যাওয়া মানে শরীর বর্তমানে কোনো ব্যাকটেরিয়াল বা ভাইরাল ইনফেকশনের বিরুদ্ধে যুদ্ধ করছে।',
    dietAdviceIfAbnormalBn: 'টক দই (প্রোবায়োটিক), রসুন, ভিটামিন-সি সমৃদ্ধ আমলকী, পেয়ারা ও লেবু খান।',
    suggestedDoctorQuestionBn: 'স্যার, শ্বেত রক্তকণিকা বৃদ্ধির জন্য কোনো অ্যান্টিবায়োটিক কোর্স বা চিকিৎসা লাগবে কি?',
  },
  {
    code: 'EOSINOPHIL',
    nameEn: 'Eosinophils (%)',
    nameBn: 'ইওসিনোফিল (অ্যালার্জি ও অ্যাজমা সূচক)',
    category: 'CBC',
    standardUnit: '%',
    normalMin: 1.0,
    normalMax: 6.0,
    highAlertThreshold: 10.0,
    simpleMeaningBn: 'এটি অ্যালার্জি, হাঁপানি (অ্যাজমা) বা পেটের কৃমি সংক্রমণের সাথে সরাসরি যুক্ত শ্বেত রক্তকণিকা।',
    ifLowMeaningBn: 'কম থাকা স্বাভাবিক এবং শরীরের জন্য কোনো ক্ষতির কারণ নয়।',
    ifHighMeaningBn: 'ইওসিনোফিল বেশি থাকা মানে শরীরে ধুলোবালি, ঠাণ্ডা, খাবারে অ্যালার্জি বা কৃমির প্রকোপ রয়েছে।',
    dietAdviceIfAbnormalBn: 'অ্যালার্জি উদ্দীপক খাবার (চিংড়ি, ইলিশ, বেগুন, গরুর মাংস) সাময়িক পরিহার করুন এবং চিকিৎসকের পরামর্শে কৃমিনাশক নিন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার অ্যালার্জি বা ঠান্ডার সমস্যা কমাতে কোনো অ্যান্টি-হিস্টামিন বা চিকিৎসা প্রয়োজন আছে?',
  },

  // =========================================================================
  // 2. DIABETES PANEL (রক্তের সুগার ও ডায়াবেটিস)
  // =========================================================================
  {
    code: 'FBS',
    nameEn: 'Fasting Blood Sugar (FBS)',
    nameBn: 'খালি পেটে রক্তের সুগার',
    category: 'DIABETES',
    standardUnit: 'mg/dL',
    normalMin: 70,
    normalMax: 100,
    highAlertThreshold: 126,
    simpleMeaningBn: 'রাত ৮-১০ ঘণ্টা না খেয়ে সকালে রক্তে শর্করার পরিমাণ যা ইনসুলিন কার্যকারিতা পরিমাপ করে।',
    ifLowMeaningBn: '৭০ এর নিচে নামলে হাইপোগ্লাইসেমিয়া (বুক ধড়ফড়, ঘাম, মাথা ঘোরা)। দ্রুত মিষ্টি বা খাবার খাওয়া দরকার।',
    ifHighMeaningBn: '১০০-১২৫ থাকলে প্রি-ডায়াবেটিস এবং ১২৬+ হলে ডায়াবেটিসের নিশ্চিত লক্ষণ।',
    dietAdviceIfAbnormalBn: 'সাদা ভাত ও চিনির মিষ্টি বর্জন করুন; লাল চালের ভাত, করলা ভাজি ও মেথি ভেজানো পানি খান।',
    suggestedDoctorQuestionBn: 'স্যার, আমার ফাস্টিং সুগার নিয়ন্ত্রণে রাখতে ওষুধের ডোজ পরিবর্তন নাকি ডায়েটই যথেষ্ট?',
  },
  {
    code: 'PPBS',
    nameEn: '2 Hours After Breakfast (2h PPBS / ABF)',
    nameBn: 'খাওয়ার ২ ঘণ্টা পর রক্তের সুগার',
    category: 'DIABETES',
    standardUnit: 'mg/dL',
    normalMin: 80,
    normalMax: 140,
    highAlertThreshold: 200,
    simpleMeaningBn: 'খাবার খাওয়ার পর শরীর খাবার থেকে পাওয়া শর্করা কতটা সফলভাবে কোষে পৌঁছাতে পারছে তা নির্দেশ করে।',
    ifLowMeaningBn: 'খাওয়ার পর সুগার খুব বেশি কমে যাওয়া হাইপোগ্লাইসেমিয়ার ঝুঁকি তৈরি করে।',
    ifHighMeaningBn: '১৪০-১৯৯ প্রি-ডায়াবেটিস এবং ২০০+ হলে ডায়াবেটিস অনিয়ন্ত্রিত বলে গণ্য হয়।',
    dietAdviceIfAbnormalBn: 'ভাতের প্লেটে অর্ধেক পরিমাণ শসা, শাকসবজি ও সালাদ রাখুন এবং খাওয়ার পর ১৫ মিনিট হালকা হাঁটুন।',
    suggestedDoctorQuestionBn: 'স্যার, খাবারের পর সুগার নিয়ন্ত্রণে রাখার জন্য খাওয়ার আগের ওষুধের টাইমিং কীভাবে ঠিক রাখব?',
  },
  {
    code: 'HBA1C',
    nameEn: 'HbA1c (Glycated Hemoglobin)',
    nameBn: 'এইচবিএওয়ানসি (গত ৩ মাসের গড় সুগার)',
    category: 'DIABETES',
    standardUnit: '%',
    normalMin: 4.0,
    normalMax: 5.6,
    highAlertThreshold: 7.0,
    simpleMeaningBn: 'এটি ডায়াবেটিস ব্যবস্থাপনার গোল্ড স্ট্যান্ডার্ড। রক্তকণিকায় জমে থাকা ৩ মাসের গড় শর্করার রেকর্ড।',
    ifLowMeaningBn: 'স্বাভাবিক ও চমৎকার মেটাবলিক স্বাস্থ্য নির্দেশ করে।',
    ifHighMeaningBn: '৫.৭-৬.৪ প্রি-ডায়াবেটিস, ৬.৫+ ডায়াবেটিস এবং ৮.০+ কিডনি, চোখ ও হার্টের মারাত্মক ঝুঁকির সংকেত।',
    dietAdviceIfAbnormalBn: 'কম গ্লাইসেমিক ইনডেক্সযুক্ত দেশি খাবার (লাল আটা, পেয়ারা, ডাল) খান ও প্রতিদিন ৪০ মিনিট দ্রুত হাঁটুন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার HbA1c লক্ষ্যমাত্রা ৬.৫% এর নিচে নামিয়ে আনতে চিকিৎসা পরিকল্পনায় কী পরিবর্তন দরকার?',
  },

  // =========================================================================
  // 3. LIPID PROFILE & CHOLESTEROL (রক্তের চর্বি ও হৃদরোগ ঝুঁকি)
  // =========================================================================
  {
    code: 'CHOL',
    nameEn: 'Total Cholesterol',
    nameBn: 'মোট রক্তের কোলেস্টেরল',
    category: 'LIPID',
    standardUnit: 'mg/dL',
    normalMin: 120,
    normalMax: 200,
    highAlertThreshold: 240,
    simpleMeaningBn: 'রক্তে প্রবাহিত সকল ধরনের চর্বির মোট যোগফল যা কোষ ও হরমোন তৈরিতে কাজে লাগে।',
    ifLowMeaningBn: 'অতিরিক্ত কম কোলেস্টেরল অপুষ্টির কারণ হতে পারে।',
    ifHighMeaningBn: '২০০ এর বেশি হলে রক্তনালীর গায়ে চর্বি জমে ব্লক তৈরি হওয়া ও হার্ট অ্যাটাকের ঝুঁকি বাড়ে।',
    dietAdviceIfAbnormalBn: 'ডালডা, ঘি ও পোড়া তেল বাদ দিন; রান্নায় কম সরিষার তেল ও ওটস খান।',
    suggestedDoctorQuestionBn: 'স্যার, আমার কোলেস্টেরল কমাতে স্ট্যাটিন জাতীয় ওষুধ লাগবে নাকি শরীরচর্চায় কমবে?',
  },
  {
    code: 'TG',
    nameEn: 'Triglycerides (TG)',
    nameBn: 'ট্রাইগ্লিসারাইড (ক্ষতিকর বাড়তি চর্বি)',
    category: 'LIPID',
    standardUnit: 'mg/dL',
    normalMin: 50,
    normalMax: 150,
    highAlertThreshold: 250,
    simpleMeaningBn: 'অতিরিক্ত মিষ্টি, চিনি, সাদা ভাত বা অ্যালকোহল খেলে লিভার যে বাড়তি চর্বি তৈরি করে তাই ট্রাইগ্লিসারাইড।',
    ifLowMeaningBn: '৫০ এর কাছাকাছি থাকা অত্যন্ত ভালো মেটাবলিক ফিটনেস নির্দেশ করে।',
    ifHighMeaningBn: '১৫০ এর উপরে থাকলে ফ্যাটি লিভার, ইনসুলিন রেজিস্ট্যান্স ও প্যানক্রিয়াসের প্রদাহের তীব্র ঝুঁকি থাকে।',
    dietAdviceIfAbnormalBn: 'চিনিযুক্ত মিষ্টি, কোমল পানীয়, বেকারি বিস্কুট ও অতিরিক্ত সাদা ভাত খাওয়া অবিলম্বে বন্ধ করুন।',
    suggestedDoctorQuestionBn: 'স্যার, ট্রাইগ্লিসারাইড বেশি থাকার কারণে আমার ফ্যাটি লিভারের জন্য আল্ট্রাসনোগ্রাম করা দরকার কি?',
  },
  {
    code: 'HDL',
    nameEn: 'HDL Cholesterol (Good Cholesterol)',
    nameBn: 'এইচডিএল (হৃদযন্ত্র রক্ষাকারী ভালো চর্বি)',
    category: 'LIPID',
    standardUnit: 'mg/dL',
    normalMin: 40,
    normalMax: 65,
    lowAlertThreshold: 35,
    simpleMeaningBn: 'এটিকে "ভালো চর্বি" বলা হয় কারণ এটি রক্তনালী থেকে ক্ষতিকর চর্বি ঝাঁট দিয়ে বের করে লিভারে নিয়ে ধ্বংস করে।',
    ifLowMeaningBn: '৪০ এর নিচে নামলে হৃদরোগ ও স্ট্রোকের ঝুঁকি বহুগুণ বেড়ে যায়।',
    ifHighMeaningBn: 'HDL ৬০ এর উপরে থাকা হৃদযন্ত্রের জন্য সুরক্ষা ঢালস্বরূপ।',
    dietAdviceIfAbnormalBn: 'পদ্মার ইলিশ মাছ (ওমেগা-৩), কাঠবাদাম, চিয়াসিড, খাঁটি অলিভ অয়েল ও নিয়মিত অ্যারোবিক ব্যায়াম করুন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার ভালো কোলেস্টেরল (HDL) বাড়ানোর জন্য কোনো বিশেষ খাদ্যাভ্যাস বা ব্যায়াম প্রেসক্রাইব করবেন কি?',
  },
  {
    code: 'LDL',
    nameEn: 'LDL Cholesterol (Bad Cholesterol)',
    nameBn: 'এলডিএল (রক্তনালী বন্ধকারী খারাপ চর্বি)',
    category: 'LIPID',
    standardUnit: 'mg/dL',
    normalMin: 50,
    normalMax: 100,
    highAlertThreshold: 160,
    simpleMeaningBn: 'এটিকে "খারাপ চর্বি" বলা হয় কারণ এটি রক্তনালীর দেয়ালে প্লাক জমিয়ে হার্ট অ্যাটাকের পথ তৈরি করে।',
    ifLowMeaningBn: '৭০-১০০ এর নিচে থাকা হৃদরোগীদের জন্য নিরাপদতম।',
    ifHighMeaningBn: '১০০ এর বেশি থাকা ক্ষতিকর এবং ১৬০ এর উপরে থাকা সরাসরি হার্ট ব্লকেজের রেড অ্যালার্ট।',
    dietAdviceIfAbnormalBn: 'রেড মিট (গরু/খাসি) কমান; রসুন, ইসবগুলের ভুসি ও সবুজ শাকসবজি বেশি করে খান।',
    suggestedDoctorQuestionBn: 'স্যার, আমার খারাপ কোলেস্টেরল (LDL) কমানোর নিরাপদ টার্গেট কত হওয়া উচিত?',
  },

  // =========================================================================
  // 4. RENAL / KIDNEY FUNCTION TEST (RFT - কিডনি ও ইউরিক এসিড)
  // =========================================================================
  {
    code: 'CREAT',
    nameEn: 'Serum Creatinine',
    nameBn: 'সিরাম ক্রিয়েটিনিন (কিডনির ছাঁকন ক্ষমতা)',
    category: 'KIDNEY_RFT',
    standardUnit: 'mg/dL',
    normalMin: 0.6,
    normalMax: 1.2,
    highAlertThreshold: 1.5,
    simpleMeaningBn: 'মাংসপেশির স্বাভাবিক ক্ষয়ে তৈরি বর্জ্য যা কিডনি প্রস্রাবের মাধ্যমে শরীর থেকে বের করে দেয়।',
    ifLowMeaningBn: 'কম থাকা সাধারণত কোনো সমস্যা নয়; দুর্বল মাংসপেশির লক্ষণ হতে পারে।',
    ifHighMeaningBn: '১.৩ এর বেশি থাকা মানে কিডনির ফিল্টার করার ক্ষমতা হ্রাস পাচ্ছে (Kidney Impairment)।',
    dietAdviceIfAbnormalBn: 'পরিমিত পানি পান করুন, ব্যথানাশক পেইনকিলার (NSAID) বর্জন করুন ও অতিরিক্ত প্রোটিন/লবণ নিয়ন্ত্রণ করুন।',
    suggestedDoctorQuestionBn: 'স্যার, ক্রিয়েটিনিন নিয়ন্ত্রণে রাখতে আমার ইউরিন মাইক্রো-অ্যালবুমিন বা eGFR টেস্ট করা প্রয়োজন আছে কি?',
  },
  {
    code: 'URIC_ACID',
    nameEn: 'Serum Uric Acid',
    nameBn: 'ইউরিক এসিড (বাতব্যথা ও জয়েন্ট পেইন)',
    category: 'KIDNEY_RFT',
    standardUnit: 'mg/dL',
    normalMin: 3.5,
    normalMax: 7.0,
    highAlertThreshold: 8.5,
    simpleMeaningBn: 'খাবারের পিউরিন ভেঙে তৈরি হওয়া অম্ল যা রক্তে বেড়ে গেলে পায়ের আঙুল ও গাঁটে তীব্র বাতব্যথা (Gout) তৈরি করে।',
    ifLowMeaningBn: 'কম থাকা ক্ষতিকর নয়।',
    ifHighMeaningBn: '৭.০ এর বেশি হলে পায়ের বৃদ্ধাঙ্গুল ফুলে যাওয়া, তীব্র যন্ত্রণা ও কিডনিতে ইউরিক এসিড পাথর হওয়ার ঝুঁকি থাকে।',
    dietAdviceIfAbnormalBn: 'খাসির মাংস, গরুর কলিজা, পুঁই শাক, অতিরিক্ত মসুর ডাল ও কোমল পানীয় সম্পূর্ণ বর্জন করুন; প্রচুর পানি ও লেবু পানি খান।',
    suggestedDoctorQuestionBn: 'স্যার, ইউরিক এসিড কমানোর জন্য কোনো ইউরিকোস্যুরিক ওষুধ বা বিশেষ ডায়েট চার্ট মেনে চলতে হবে কি?',
  },
  {
    code: 'UREA',
    nameEn: 'Blood Urea Nitrogen / Urea',
    nameBn: 'ব্লাড ইউরিয়া (প্রোটিন বর্জ্য)',
    category: 'KIDNEY_RFT',
    standardUnit: 'mg/dL',
    normalMin: 15,
    normalMax: 45,
    highAlertThreshold: 60,
    simpleMeaningBn: 'লিভারে প্রোটিন ভাঙার পর তৈরি হওয়া বর্জ্য যা কিডনি পরিষ্কার করে।',
    ifLowMeaningBn: 'কম থাকা কম প্রোটিন গ্রহণ বা লিভার সমস্যার সংকেত হতে পারে।',
    ifHighMeaningBn: 'বেশি থাকা পানিশূন্যতা, অতিরিক্ত মাংস গ্রহণ বা কিডনির দুর্বলতার কারণে হতে পারে।',
    dietAdviceIfAbnormalBn: 'পর্যাপ্ত বিশুদ্ধ পানি পান করুন ও চিকিৎসকের পরামর্শ ছাড়া প্রোটিন সাপ্লিমেন্ট নেবেন না।',
    suggestedDoctorQuestionBn: 'স্যার, ইউরিয়া বৃদ্ধির কারণ কি পানিশূন্যতা নাকি কিডনিজনিত?',
  },

  // =========================================================================
  // 5. LIVER FUNCTION TEST (LFT - লিভার ও জন্ডিস)
  // =========================================================================
  {
    code: 'SGPT',
    nameEn: 'SGPT / ALT (Alanine Aminotransferase)',
    nameBn: 'এসজিপিটি (লিভারের কোষীয় এনজাইম)',
    category: 'LIVER_LFT',
    standardUnit: 'U/L',
    normalMin: 10,
    normalMax: 40,
    highAlertThreshold: 80,
    simpleMeaningBn: 'এটি লিভারের মূল এনজাইম। লিভারের কোষে কোনো আঘাত বা চর্বি জমলে এটি রক্তে লিক হয়ে বেড়ে যায়।',
    ifLowMeaningBn: 'কম থাকা সম্পূর্ণ স্বাভাবিক ও স্বাস্থ্যকর।',
    ifHighMeaningBn: '৪০ এর বেশি থাকা ফ্যাটি লিভার, ওষুধের পার্শ্বপ্রতিক্রিয়া বা হেপাটাইটিস ভাইরাসের প্রাথমিক লক্ষণ।',
    dietAdviceIfAbnormalBn: 'তেল-চর্বি ও ফাস্টফুড বর্জন করুন; পেঁপে, লাউ, কাঁচা হলুদ ও গ্রিন টি খান। অপ্রয়োজনীয় ওষুধ খাওয়া বন্ধ করুন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার SGPT বৃদ্ধির পেছনে ফ্যাটি লিভারের মাত্রা জানতে আল্ট্রাসনোগ্রাম বা ফাইব্রোস্ক্যান প্রয়োজন কি?',
  },
  {
    code: 'SGOT',
    nameEn: 'SGOT / AST (Aspartate Aminotransferase)',
    nameBn: 'এসজিওটি (লিভার ও পেশির এনজাইম)',
    category: 'LIVER_LFT',
    standardUnit: 'U/L',
    normalMin: 10,
    normalMax: 40,
    highAlertThreshold: 80,
    simpleMeaningBn: 'এটি লিভারের পাশাপাশি হৃদযন্ত্র ও মাংসপেশিতেও থাকে। কোষের ক্ষতি হলে এর মাত্রা বৃদ্ধি পায়।',
    ifLowMeaningBn: 'স্বাভাবিক মান।',
    ifHighMeaningBn: 'বেশি থাকা লিভার প্রদাহ বা অতিরিক্ত ভারী ব্যায়ামের পর সাময়িক হতে পারে।',
    dietAdviceIfAbnormalBn: 'পর্যাপ্ত বিশ্রাম নিন ও পুষ্টিকর সহজপাচ্য খাবার খান।',
    suggestedDoctorQuestionBn: 'স্যার, SGPT ও SGOT এর অনুপাত দেখে লিভারের সঠিক অবস্থা জানতে কী টেস্ট লাগবে?',
  },
  {
    code: 'BILIRUBIN',
    nameEn: 'Serum Bilirubin (Total)',
    nameBn: 'সিরাম বিলিরুবিন (জন্ডিসের মাত্রা)',
    category: 'LIVER_LFT',
    standardUnit: 'mg/dL',
    normalMin: 0.3,
    normalMax: 1.2,
    highAlertThreshold: 2.0,
    simpleMeaningBn: 'পুরোনো রক্তকণিকা ভাঙার ফলে তৈরি হলুদ রঙের রঞ্জক পদার্থ। লিভার এটি শরীর থেকে নিষ্কাশন করে।',
    ifLowMeaningBn: 'স্বাভাবিক।',
    ifHighMeaningBn: '১.২ এর বেশি হলে চোখ ও প্রস্রাব হলুদ হয়ে জন্ডিসের উপসর্গ দেখা দেয়।',
    dietAdviceIfAbnormalBn: 'বিশুদ্ধ ফুটানো পানি পান করুন, রাস্তার খোলা খাবার বন্ধ রাখুন এবং ডাবের পানি ও আখের রস (ঘরে তৈরি) খান।',
    suggestedDoctorQuestionBn: 'স্যার, জন্ডিসের কারণ জানতে হেপাটাইটিস স্ক্রিনিং (HBsAg, Anti-HCV) করার প্রয়োজন আছে কি?',
  },

  // =========================================================================
  // 6. THYROID PANEL (থাইরয়েড হরমোন)
  // =========================================================================
  {
    code: 'TSH',
    nameEn: 'TSH (Thyroid Stimulating Hormone)',
    nameBn: 'টিএসএইচ (থাইরয়েড হরমোন নিয়ন্ত্রক)',
    category: 'THYROID',
    standardUnit: 'uIU/mL',
    normalMin: 0.4,
    normalMax: 4.2,
    lowAlertThreshold: 0.1,
    highAlertThreshold: 10.0,
    simpleMeaningBn: 'মস্তিষ্কের পিটুইটারি গ্রন্থির হরমোন যা গলার থাইরয়েড গ্রন্থিকে শরীরের মেটাবলিজম চালাতে হুকুম দেয়।',
    ifLowMeaningBn: '০.৪ এর নিচে নামলে হাইপারথাইরয়েডিজম (ওজন কমে যাওয়া, বুক ধড়ফড়, গরম লাগা, অতিরিক্ত অস্থিরতা)।',
    ifHighMeaningBn: '৪.২ এর বেশি হলে হাইপোথাইরয়েডিজম (ওজন বেড়ে যাওয়া, অতিরিক্ত ক্লান্তি, চুল পড়া, কোষ্ঠকাঠিন্য)।',
    dietAdviceIfAbnormalBn: 'আয়োডিনযুক্ত লবণ, সামুদ্রিক মাছ ও সেদ্ধ ডিম খান; চিকিৎসকের থাইরক্সিন ওষুধ নিয়মিত গ্রহণ করুন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার TSH অনুযায়ী থাইরয়েডের ওষুধের পাওয়ার (যেমন Thyrox 25/50 mcg) অ্যাডজাস্ট করা লাগবে কি?',
  },

  // =========================================================================
  // 7. ELECTROLYTES & VITAMINS (ইলেক্ট্রোলাইটস ও ভিটামিন)
  // =========================================================================
  {
    code: 'POTASSIUM',
    nameEn: 'Serum Potassium (K+)',
    nameBn: 'পটাশিয়াম (হৃদস্পন্দন ও স্নায়ু বিদ্যুৎ)',
    category: 'ELECTROLYTES_VIT',
    standardUnit: 'mmol/L',
    normalMin: 3.5,
    normalMax: 5.1,
    lowAlertThreshold: 3.0,
    highAlertThreshold: 5.8,
    simpleMeaningBn: 'হৃদপিণ্ডের নিয়মিত ছন্দ এবং মাংসপেশির সংকোচন-প্রসারণ নিয়ন্ত্রণকারী অত্যন্ত গুরুত্বপূর্ণ খনিজ।',
    ifLowMeaningBn: '৩.৫ এর নিচে নামলে পেশিতে টান ধরা, দুর্বলতা ও অনিয়মিত হৃদস্পন্দন হতে পারে।',
    ifHighMeaningBn: '৫.১ এর বেশি হওয়া (Hyperkalemia) বিপজ্জনক; বিশেষ করে কিডনি রোগীদের হার্ট ব্লক বা কার্ডিয়াক অ্যারেস্টের ঝুঁকি বাড়ায়।',
    dietAdviceIfAbnormalBn: 'পটাশিয়াম কম থাকলে ডাবের পানি ও কলা খান; কিন্তু পটাশিয়াম বেশি থাকলে ডাবের পানি ও পাকা ফল সম্পূর্ণ এড়িয়ে চলুন।',
    suggestedDoctorQuestionBn: 'স্যার, আমার রক্তচাপের ওষুধের কারণে পটাশিয়ামের মাত্রায় কোনো প্রভাব পড়ছে কি?',
  },
  {
    code: 'VIT_D',
    nameEn: 'Vitamin D3 (25-Hydroxy)',
    nameBn: 'ভিটামিন-ডি৩ (হাড় ও রোগ প্রতিরোধ শক্তি)',
    category: 'ELECTROLYTES_VIT',
    standardUnit: 'ng/mL',
    normalMin: 30.0,
    normalMax: 100.0,
    lowAlertThreshold: 20.0,
    simpleMeaningBn: 'ক্যালসিয়াম শোষণ, হাড়ের মজবুতি ও রোগ প্রতিরোধ ক্ষমতা ঠিক রাখতে অপরিহার্য সূর্যালোক ভিটামিন।',
    ifLowMeaningBn: '২০ এর নিচে থাকলে ভিটামিন-ডি ঘাটতি; এর ফলে হাড় ব্যথা, কোমর ব্যথা, অস্টিওপোরোসিস ও ঘন ঘন অসুস্থতা দেখা দেয়।',
    ifHighMeaningBn: '১০০ এর বেশি হওয়া অতিরিক্ত ওভারডোজ নির্দেশ করে।',
    dietAdviceIfAbnormalBn: 'প্রতিদিন সকাল ১০টা থেকে দুপুর ২টার মধ্যে ১৫-২০ মিনিট গায়ে রোদ লাগান; ডিমের কুসুম, ছোট মাছ ও মাশরুম খান।',
    suggestedDoctorQuestionBn: 'স্যার, আমার ভিটামিন-ডি ঘাটতি পূরণে কোনো সাপ্তাহিক ৬০,০০০ আইইউ ক্যাপসুল প্রয়োজন আছে কি?',
  },
];

export const PRESET_LAB_PANELS: Array<{
  id: LabPanelType;
  titleBn: string;
  titleEn: string;
  icon: string;
  color: string;
  defaultAnalytes: Array<{ code: string; value: number; unit: string }>;
}> = [
  {
    id: 'CBC',
    titleBn: '🩸 সিবিসি ও রক্তস্বল্পতা প্যানেল',
    titleEn: 'Complete Blood Count (CBC)',
    icon: 'bloodtype',
    color: '#EF4444',
    defaultAnalytes: [
      { code: 'HB', value: 11.2, unit: 'g/dL' },
      { code: 'ESR', value: 28, unit: 'mm/1st hr' },
      { code: 'PLATELET', value: 240, unit: 'x10^3/uL' },
      { code: 'WBC', value: 7500, unit: '/uL' },
      { code: 'EOSINOPHIL', value: 7.5, unit: '%' },
    ],
  },
  {
    id: 'DIABETES',
    titleBn: '🩺 ডায়াবেটিস ও সুগার প্যানেল',
    titleEn: 'Diabetes & Glycemic Panel',
    icon: 'medication',
    color: '#10B981',
    defaultAnalytes: [
      { code: 'FBS', value: 118, unit: 'mg/dL' },
      { code: 'PPBS', value: 165, unit: 'mg/dL' },
      { code: 'HBA1C', value: 7.2, unit: '%' },
    ],
  },
  {
    id: 'LIPID',
    titleBn: '🫀 লিপিড প্রোফাইল (কোলেস্টেরল)',
    titleEn: 'Lipid Profile & Heart Health',
    icon: 'favorite',
    color: '#F43F5E',
    defaultAnalytes: [
      { code: 'CHOL', value: 215, unit: 'mg/dL' },
      { code: 'TG', value: 210, unit: 'mg/dL' },
      { code: 'HDL', value: 38, unit: 'mg/dL' },
      { code: 'LDL', value: 135, unit: 'mg/dL' },
    ],
  },
  {
    id: 'KIDNEY_RFT',
    titleBn: '🫘 কিডনি ফাংশন ও ইউরিক এসিড',
    titleEn: 'Renal Function Test (RFT)',
    icon: 'shield',
    color: '#F59E0B',
    defaultAnalytes: [
      { code: 'CREAT', value: 1.35, unit: 'mg/dL' },
      { code: 'URIC_ACID', value: 7.8, unit: 'mg/dL' },
      { code: 'UREA', value: 42, unit: 'mg/dL' },
    ],
  },
  {
    id: 'LIVER_LFT',
    titleBn: '🫁 লিভার ফাংশন ও জন্ডিস',
    titleEn: 'Liver Function Test (LFT)',
    icon: 'healing',
    color: '#00B4D8',
    defaultAnalytes: [
      { code: 'SGPT', value: 62, unit: 'U/L' },
      { code: 'SGOT', value: 48, unit: 'U/L' },
      { code: 'BILIRUBIN', value: 0.9, unit: 'mg/dL' },
    ],
  },
  {
    id: 'THYROID',
    titleBn: '🦋 থাইরয়েড হরমোন প্যানেল',
    titleEn: 'Thyroid Hormones (TSH)',
    icon: 'science',
    color: '#8B5CF6',
    defaultAnalytes: [
      { code: 'TSH', value: 6.8, unit: 'uIU/mL' },
    ],
  },
];
