import { BanglaFoodItem } from '@/types/bangla-food-gi';

export const BANGLA_FOOD_CATALOG: BanglaFoodItem[] = [
  // ==========================================
  // 1. RICE, GRAINS & BREADS (ভাত ও খাদ্যশস্য)
  // ==========================================
  {
    id: 'bf_red_rice',
    nameBn: 'লাল চালের ভাত (ঢেঁকি ছাঁটা)',
    nameEn: 'Red Rice / Brown Rice (Cooked)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ কাপ (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 54,
    giLevel: 'LOW',
    glPerServing: 18,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 111,
      proteinG: 2.6,
      carbsG: 23.5,
      fatG: 0.9,
      fiberG: 2.8,
      potassiumMg: 79,
      sodiumMg: 4,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'সাদা পলিশড চালের নিখুঁত বিকল্প',
    clinicalNotesBn: 'উচ্চ আঁশ ও ম্যাগনেসিয়াম থাকায় ইনসুলিন সংবেদনশীলতা বাড়ায় ও সুগার নিয়ন্ত্রণে সাহায্য করে।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_white_rice_miniket',
    nameBn: 'মিনিকেট / নাজিরশাইল সাদা ভাত',
    nameEn: 'Polished White Rice (Miniket/Nazirshail)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ কাপ (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 73,
    giLevel: 'HIGH',
    glPerServing: 30,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 130,
      proteinG: 2.7,
      carbsG: 28.2,
      fatG: 0.3,
      fiberG: 0.4,
      potassiumMg: 35,
      sodiumMg: 1,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'লাল চাল বা বাসমতী চাল খান',
    clinicalNotesBn: 'পলিশিং প্রক্রিয়ায় ফাইবার নষ্ট হয়, তাই খাওয়ার ২০-৩০ মিনিটের মধ্যে দ্রুত সুগার স্পাইক ঘটায়।',
  },
  {
    id: 'bf_basmati_rice',
    nameBn: 'বাসমতী চালের ভাত (সেদ্ধ)',
    nameEn: 'Basmati Rice (Cooked)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ কাপ (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 58,
    giLevel: 'MEDIUM',
    glPerServing: 22,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 121,
      proteinG: 3.5,
      carbsG: 25.2,
      fatG: 0.4,
      fiberG: 1.2,
      potassiumMg: 55,
      sodiumMg: 2,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'মিনিকেট চালের চেয়ে ভালো',
    clinicalNotesBn: 'অন্যান্য সাদা চালের তুলনায় অ্যামাইলোজ বেশি থাকায় মাঝারি গতির পরিপাক হয়।',
  },
  {
    id: 'bf_panta_bhat',
    nameBn: 'পান্তা ভাত (ফার্মেন্টেড)',
    nameEn: 'Panta Bhat (Fermented Rice)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ বাটি (২০০ গ্রাম)',
    servingWeightG: 200,
    giValue: 52,
    giLevel: 'LOW',
    glPerServing: 16,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 95,
      proteinG: 2.1,
      carbsG: 19.5,
      fatG: 0.2,
      fiberG: 1.5,
      potassiumMg: 90,
      sodiumMg: 10,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'অতিরিক্ত লবণ ও পোড়া মরিচ ছাড়া খান',
    clinicalNotesBn: 'সারারাত ফার্মান্টেশনের ফলে রেসিস্ট্যান্ট স্টার্চ ও প্রোবায়োটিক তৈরি হয় যা সুগার স্পাইক কমায়।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_lal_atta_ruti',
    nameBn: 'লাল আটার হাতে তৈরি রুটি',
    nameEn: 'Whole Wheat Lal Atta Roti',
    category: 'RICE_GRAINS',
    servingSizeBn: '১টি মাঝারি রুটি (৪০ গ্রাম)',
    servingWeightG: 40,
    giValue: 52,
    giLevel: 'LOW',
    glPerServing: 11,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 247,
      proteinG: 9.8,
      carbsG: 49.0,
      fatG: 1.5,
      fiberG: 9.2,
      potassiumMg: 280,
      sodiumMg: 5,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'পরোটার জায়গায় লাল আটার শুকনো রুটি আদর্শ',
    clinicalNotesBn: 'চোকরযুক্ত লাল আটায় প্রচুর দ্রবণীয় আঁশ থাকে যা পাকস্থলী থেকে গ্লুকোজ নিঃসরণ ধীর করে।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_maida_paratha',
    nameBn: 'তেলে ভাজা ময়দার পরোটা',
    nameEn: 'Refined Flour Oil Paratha',
    category: 'RICE_GRAINS',
    servingSizeBn: '১টি পরোটা (৮০ গ্রাম)',
    servingWeightG: 80,
    giValue: 82,
    giLevel: 'HIGH',
    glPerServing: 32,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 330,
      proteinG: 6.2,
      carbsG: 46.0,
      fatG: 14.5,
      fiberG: 1.1,
      potassiumMg: 95,
      sodiumMg: 180,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'তেল ছাড়া লাল আটার শুকনো রুটি খান',
    clinicalNotesBn: 'রিফাইন্ড ময়দা ও ডালডা/পোড়া তেল সরাসরি লিভারে ট্রাইগ্লিসারাইড জমায় এবং ইনসুলিন রেজিস্ট্যান্স বাড়ায়।',
  },
  {
    id: 'bf_chira',
    nameBn: 'চিঁড়া (শুকনো বা ভেজানো)',
    nameEn: 'Flattened Rice (Chira / Poha)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১/২ কাপ (৫০ গ্রাম)',
    servingWeightG: 50,
    giValue: 64,
    giLevel: 'MEDIUM',
    glPerServing: 24,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 346,
      proteinG: 6.6,
      carbsG: 77.3,
      fatG: 1.2,
      fiberG: 2.1,
      potassiumMg: 110,
      sodiumMg: 8,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'টক দই ও শসার সাথে পরিমিত চিঁড়া খান',
    clinicalNotesBn: 'চিঁড়ার সাথে মিষ্টি বা গুড় মেশালে সুগার দ্রুত বাড়ে; টক দই বা চিয়াসিডের সাথে খাওয়া নিরাপদ।',
  },
  {
    id: 'bf_muri',
    nameBn: 'মুড়ি (হাতে ভাজা / প্যাকেট)',
    nameEn: 'Puffed Rice (Muri)',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ বাটি (৩০ গ্রাম)',
    servingWeightG: 30,
    giValue: 75,
    giLevel: 'HIGH',
    glPerServing: 19,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 383,
      proteinG: 6.5,
      carbsG: 87.0,
      fatG: 0.5,
      fiberG: 1.4,
      potassiumMg: 90,
      sodiumMg: 15,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'মুড়ির সাথে ছোলা বুট বা বাদাম মিশিয়ে খান',
    clinicalNotesBn: 'মুড়ির GI বেশি হলেও এক বাটিতে ওজন কম থাকায় GL মাঝারি। শসা ও বাদামের সাথে খেলে সুগার স্পাইক হয় না।',
  },
  {
    id: 'bf_khichuri_oats',
    nameBn: 'সবজি ও ডাল দিয়ে ওটস খিচুড়ি',
    nameEn: 'Oats & Vegetable Moong Khichuri',
    category: 'RICE_GRAINS',
    servingSizeBn: '১ বাটি (২০০ গ্রাম)',
    servingWeightG: 200,
    giValue: 45,
    giLevel: 'LOW',
    glPerServing: 12,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 115,
      proteinG: 5.5,
      carbsG: 17.2,
      fatG: 2.8,
      fiberG: 4.2,
      potassiumMg: 220,
      sodiumMg: 60,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'পোলাও বা চালের বিরিয়ানীর সেরা পুষ্টিকর বিকল্প',
    clinicalNotesBn: 'ওটসের বিটা-গ্লুকান ফাইবার রক্তে কোলেস্টেরল ও গ্লুকোজ লেভেল দ্রুত নামিয়ে আনে।',
    isTraditionalSuperfood: true,
  },

  // ==========================================
  // 2. FISH, MEAT & EGGS (মাছ, মাংস ও ডিম)
  // ==========================================
  {
    id: 'bf_ilish_mach',
    nameBn: 'পদ্মার ইলিশ মাছ (পাতলা ঝোল)',
    nameEn: 'Hilsa Fish Curry (Ilish Mach)',
    category: 'FISH_MEAT',
    servingSizeBn: '১ টুকরো (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 270,
      proteinG: 21.8,
      carbsG: 0.0,
      fatG: 19.4,
      fiberG: 0.0,
      potassiumMg: 290,
      sodiumMg: 75,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'MODERATE',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ডুবো তেলে কড়া না ভেজে হালকা ঝোল করে খান',
    clinicalNotesBn: 'প্রচুর ওমেগা-৩ ফ্যাটি এসিড থাকায় হার্ট ভালো রাখে এবং রক্তে ভালো কোলেস্টেরল (HDL) বাড়ায়।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_rui_katla',
    nameBn: 'রুই / কাতলা মাছের হালকা ঝোল',
    nameEn: 'Rohu / Katla Fish Curry',
    category: 'FISH_MEAT',
    servingSizeBn: '১ টুকরো (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 128,
      proteinG: 19.5,
      carbsG: 0.0,
      fatG: 4.8,
      fiberG: 0.0,
      potassiumMg: 310,
      sodiumMg: 65,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'দৈনিক প্রোটিনের নিরাপদ উৎস',
    clinicalNotesBn: 'জিরো কার্বোহাইড্রেট ও সহজপাচ্য লিন প্রোটিন থাকায় সুগার বাড়ায় না ও লিভারে ফ্যাট কমায়।',
  },
  {
    id: 'bf_shing_magur',
    nameBn: 'শিং / মাগুর মাছের ঝোল',
    nameEn: 'Catfish / Shing-Magur Curry',
    category: 'FISH_MEAT',
    servingSizeBn: '১টি মাছ (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 98,
      proteinG: 22.1,
      carbsG: 0.0,
      fatG: 1.2,
      fiberG: 0.0,
      potassiumMg: 350,
      sodiumMg: 55,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'রোগমুক্তির পথ্য ও দুর্বলতা দূরীকরণে সেরা',
    clinicalNotesBn: 'কম চর্বি ও উচ্চ আয়রন ও প্রোটিন থাকায় ডায়াবেটিস ও দুর্বল রোগীর আদর্শ পুষ্টি।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_choto_mach',
    nameBn: 'কাচকি / মলা ছোট মাছের চচ্চড়ি',
    nameEn: 'Small Indigenous Fish (Kachki/Mola)',
    category: 'FISH_MEAT',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 105,
      proteinG: 18.2,
      carbsG: 0.0,
      fatG: 3.1,
      fiberG: 0.0,
      potassiumMg: 280,
      sodiumMg: 70,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'কাটা সহ চিবিয়ে খেলে প্রচুর ক্যালসিয়াম মেলে',
    clinicalNotesBn: 'ভিটামিন-এ এবং বায়ো-অ্যাক্টিভ ক্যালসিয়ামের চমৎকার প্রাকৃতিক উৎস।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_deshi_chicken',
    nameBn: 'দেশি মুরগির পাতলা ঝোল',
    nameEn: 'Deshi Chicken Curry (Skinless)',
    category: 'FISH_MEAT',
    servingSizeBn: '১ বাটি (১২০ গ্রাম)',
    servingWeightG: 120,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 145,
      proteinG: 24.5,
      carbsG: 0.0,
      fatG: 4.8,
      fiberG: 0.0,
      potassiumMg: 260,
      sodiumMg: 70,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'গরু বা খাসির মাংসের জায়গায় দেশি মুরগি খান',
    clinicalNotesBn: 'চামড়া ছাড়া দেশি মুরগির মাংসে সম্পৃক্ত চর্বি অত্যন্ত কম, যা লিভার ও হৃদযন্ত্রকে সুস্থ রাখে।',
  },
  {
    id: 'bf_beef_bhuna',
    nameBn: 'গরুর মাংস ভুনা / কালিয়া',
    nameEn: 'Beef Bhuna Curry',
    category: 'FISH_MEAT',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 250,
      proteinG: 22.0,
      carbsG: 1.0,
      fatG: 17.5,
      fiberG: 0.0,
      potassiumMg: 310,
      sodiumMg: 190,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'AVOID',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'চর্বি ছাঁটা লিন মাংস অল্প তেলে রান্না করে খান',
    clinicalNotesBn: 'উচ্চ স্যাচুরেটেড ফ্যাট ফ্যাটি লিভার বাড়ায় এবং পিউরিন বেশি থাকায় ইউরিক এসিড বাড়িয়ে বাতব্যথা সৃষ্টি করে।',
  },
  {
    id: 'bf_mutton_rezala',
    nameBn: 'খাসির মাংসের রেজালা',
    nameEn: 'Mutton Rezala Curry',
    category: 'FISH_MEAT',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 285,
      proteinG: 20.5,
      carbsG: 2.0,
      fatG: 21.8,
      fiberG: 0.0,
      potassiumMg: 290,
      sodiumMg: 210,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'AVOID',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'AVOID',
    smartSwapBn: 'খাসির বদলে মাছ বা দেশি মুরগি বেছে নিন',
    clinicalNotesBn: 'উচ্চ পিউরিন ও কোলেস্টেরল সমৃদ্ধ; গাউট/ইউরিক এসিড ও কিডনি রোগীদের জন্য বর্জনীয়।',
  },
  {
    id: 'bf_egg_boiled',
    nameBn: 'সেদ্ধ ডিম (কুসুম সহ)',
    nameEn: 'Boiled Whole Egg',
    category: 'FISH_MEAT',
    servingSizeBn: '১টি ডিম (৫০ গ্রাম)',
    servingWeightG: 50,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 155,
      proteinG: 13.0,
      carbsG: 1.1,
      fatG: 11.0,
      fiberG: 0.0,
      potassiumMg: 126,
      sodiumMg: 124,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ভাজার চেয়ে সেদ্ধ ডিম শ্রেষ্ঠ',
    clinicalNotesBn: 'ডিমে কোলিন থাকে যা ফ্যাটি লিভার রিভার্সালে সাহায্য করে এবং সুগার নিয়ন্ত্রণে রাখে।',
    isTraditionalSuperfood: true,
  },

  // ==========================================
  // 3. VEGETABLES & BHORTA (দেশি শাকসবজি ও ভর্তা)
  // ==========================================
  {
    id: 'bf_korola_vaji',
    nameBn: 'করলা / উচ্ছে ভাজি',
    nameEn: 'Bitter Gourd Stir Fry (Korola Vaji)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 15,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 34,
      proteinG: 1.8,
      carbsG: 4.2,
      fatG: 1.2,
      fiberG: 3.5,
      potassiumMg: 296,
      sodiumMg: 8,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ডায়াবেটিস রোগীদের অমৃত তুল্য',
    clinicalNotesBn: 'করলায় রয়েছে ক্যারান্টিন ও পলিপেপটাইড-পি যা প্রাকৃতিক ইনসুলিনের মতো রক্তে সুগার কমাতে সরাসরি কাজ করে।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_lal_shak',
    nameBn: 'লাল শাক ভাজি',
    nameEn: 'Red Amaranth Leaves (Lal Shak Vaji)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 15,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 45,
      proteinG: 3.2,
      carbsG: 5.0,
      fatG: 1.5,
      fiberG: 3.8,
      potassiumMg: 340,
      sodiumMg: 20,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'অল্প তেলে রসুন ও কালোজিরা দিয়ে রান্না করুন',
    clinicalNotesBn: 'প্রচুর অ্যান্টিঅক্সিডেন্ট ও ডায়াবেটিক-ফ্রেন্ডলি ফাইবার সমৃদ্ধ যা অন্ত্রে সুগার শোষণ ধীর করে।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_palong_shak',
    nameBn: 'পালং শাকের তরকারি',
    nameEn: 'Spinach Curry (Palong Shak)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 15,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 38,
      proteinG: 2.9,
      carbsG: 3.6,
      fatG: 1.2,
      fiberG: 2.6,
      potassiumMg: 558,
      sodiumMg: 79,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'MODERATE',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'কিডনি রোগীদের অতিরিক্ত না খাওয়াই ভালো',
    clinicalNotesBn: 'পটাশিয়াম ও অক্সালেট বেশি থাকায় সিকেডি ও কিডনি স্টোন রোগীদের সীমিত খাওয়া উচিত।',
  },
  {
    id: 'bf_lau_torkari',
    nameBn: 'লাউ দিয়ে ছোট মাছ বা ডাল',
    nameEn: 'Bottle Gourd Curry (Lau Torkari)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 20,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 22,
      proteinG: 1.1,
      carbsG: 3.4,
      fatG: 0.4,
      fiberG: 2.1,
      potassiumMg: 150,
      sodiumMg: 12,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'গরমের দিনে শরীর ঠান্ডা রাখতে সেরা',
    clinicalNotesBn: '৯৬% পানি ও দ্রবণীয় আঁশ থাকায় সুগার স্পাইক সম্পূর্ণ শূন্য রাখে এবং শরীর হাইড্রেটেড রাখে।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_begun_bhuna',
    nameBn: 'বেগুন ভাজি / বেগুন ভর্তা',
    nameEn: 'Eggplant Fry / Bharta (Begun)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 20,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 65,
      proteinG: 1.4,
      carbsG: 5.8,
      fatG: 4.2,
      fiberG: 3.0,
      potassiumMg: 229,
      sodiumMg: 15,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'SAFE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'তেলে কড়া ভাজার বদলে বেগুন পুড়িয়ে ভর্তা খান',
    clinicalNotesBn: 'বেগুন প্রচুর তেল শোষণ করে; তাই ভাজার বদলে রোস্ট বা ভর্তা বানালে ক্যালরি অনেক কমে।',
  },
  {
    id: 'bf_alu_bhorta',
    nameBn: 'আলু ভর্তা (সরিষার তেল ও পেঁয়াজ)',
    nameEn: 'Mashed Potato (Alu Bhorta)',
    category: 'VEGETABLES',
    servingSizeBn: '১ টেবিল চামচ (৫০ গ্রাম)',
    servingWeightG: 50,
    giValue: 78,
    giLevel: 'HIGH',
    glPerServing: 14,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 120,
      proteinG: 2.0,
      carbsG: 20.5,
      fatG: 3.5,
      fiberG: 1.8,
      potassiumMg: 380,
      sodiumMg: 50,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'কাঁচা পেঁপে বা পটল ভর্তা বিকল্প হতে পারে',
    clinicalNotesBn: 'সেদ্ধ চটকানো আলুর স্টার্চ খুব দ্রুত শোষিত হয়ে রক্তের সুগার দ্রুত বাড়িয়ে দেয়।',
  },
  {
    id: 'bf_dherosh_vaji',
    nameBn: 'ঢ্যাঁড়শ ভাজি (Okra / Lady Finger)',
    nameEn: 'Lady Finger / Okra Stir Fry (Dherosh)',
    category: 'VEGETABLES',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 20,
    giLevel: 'LOW',
    glPerServing: 1,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 42,
      proteinG: 2.0,
      carbsG: 5.2,
      fatG: 1.6,
      fiberG: 3.2,
      potassiumMg: 299,
      sodiumMg: 10,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ডায়াবেটিস রোগীদের নিয়মিত পথ্য',
    clinicalNotesBn: 'ঢ্যাঁড়শের মিউসিলেজ (আঠালো অংশ) ক্ষুদ্রান্ত্রে কার্বোহাইড্রেট পরিপাক ধীর করে সুগার স্পাইক রোধ করে।',
    isTraditionalSuperfood: true,
  },

  // ==========================================
  // 4. BANGLADESHI FRUITS (দেশি ফলমূল)
  // ==========================================
  {
    id: 'bf_peara',
    nameBn: 'দেশি সবুজ পেয়ারা',
    nameEn: 'Bangladeshi Green Guava (Peara)',
    category: 'FRUITS',
    servingSizeBn: '১টি মাঝারি পেয়ারা (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 12,
    giLevel: 'LOW',
    glPerServing: 2,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 68,
      proteinG: 2.6,
      carbsG: 14.3,
      fatG: 1.0,
      fiberG: 5.4,
      potassiumMg: 417,
      sodiumMg: 2,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'পাকা আমের সেরা স্বাস্থ্যকর বিকল্প',
    clinicalNotesBn: 'অত্যন্ত কম গ্লাইসেমিক ইনডেক্স ও উচ্চ ফাইবার; ডায়াবেটিস ও ফ্যাটি লিভারের রোগীদের এক নম্বর সুপারফ্রুট।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_kacha_aam',
    nameBn: 'কাঁচা আম (টক আম)',
    nameEn: 'Raw Green Mango (Kacha Aam)',
    category: 'FRUITS',
    servingSizeBn: '১টি ছোট আম (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 35,
    giLevel: 'LOW',
    glPerServing: 4,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 44,
      proteinG: 0.7,
      carbsG: 11.0,
      fatG: 0.2,
      fiberG: 2.4,
      potassiumMg: 160,
      sodiumMg: 2,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'চিনি ছাড়া কাঁচা আমের জুস বা সালাদ খান',
    clinicalNotesBn: 'পেকটিন ও ম্যালিক এসিড থাকে যা হজমে সাহায্য করে এবং যকৃতের কার্যক্ষমতা বাড়ায়।',
  },
  {
    id: 'bf_paka_aam_himsagar',
    nameBn: 'পাকা আম (হিমসাগর / ল্যাংড়া)',
    nameEn: 'Ripe Sweet Mango (Himsagar/Langra)',
    category: 'FRUITS',
    servingSizeBn: '১/২টি আম বা ১ কাপ কুচি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 60,
    giLevel: 'MEDIUM',
    glPerServing: 16,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 75,
      proteinG: 0.8,
      carbsG: 18.0,
      fatG: 0.4,
      fiberG: 1.6,
      potassiumMg: 168,
      sodiumMg: 1,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'একবারে বেশি না খেয়ে মাত্র ১-২ টুকরো খান',
    clinicalNotesBn: 'প্রচুর ফ্রুক্টোজ থাকে। ডায়াবেটিস রোগীরা ভাত বা কার্বোহাইড্রেট কম খেয়ে ফল হিসেবে দিনে ১ টুকরো খেতে পারেন।',
  },
  {
    id: 'bf_kathal',
    nameBn: 'পাকা কাঁঠাল (জাতীয় ফল)',
    nameEn: 'Ripe Jackfruit Pods (Kathal)',
    category: 'FRUITS',
    servingSizeBn: '৪-৫টি কোঁয়া (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 75,
    giLevel: 'HIGH',
    glPerServing: 20,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 95,
      proteinG: 1.7,
      carbsG: 23.2,
      fatG: 0.6,
      fiberG: 1.5,
      potassiumMg: 448,
      sodiumMg: 3,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'AVOID',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'কাঁচা এঁচোড় বা পেয়ারা খান',
    clinicalNotesBn: 'অত্যন্ত উচ্চ সুগার ও উচ্চ পটাশিয়াম; ডায়াবেটিস ও কিডনি রোগীদের রক্তে বিপজ্জনক সুগার ও পটাশিয়াম স্পাইক ঘটায়।',
  },
  {
    id: 'bf_jambura',
    nameBn: 'জাম্বুরা / বাতাবি লেবু',
    nameEn: 'Pomelo / Grapefruit (Jambura)',
    category: 'FRUITS',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 25,
    giLevel: 'LOW',
    glPerServing: 3,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 38,
      proteinG: 0.8,
      carbsG: 9.6,
      fatG: 0.0,
      fiberG: 1.0,
      potassiumMg: 216,
      sodiumMg: 1,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'মিষ্টি ফলের বদলে জাম্বুরা খান',
    clinicalNotesBn: 'ভিটামিন-সি ও নারিনজেনিন ফ্ল্যাভোনয়েড সমৃদ্ধ যা লিভারের চর্বি গলাতে এবং ইনসুলিন সেনসিটিভিটি বাড়াতে দারুণ সহায়ক।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_kalo_jam',
    nameBn: 'কালো জাম (Black Plum)',
    nameEn: 'Blackberry / Java Plum (Kalo Jam)',
    category: 'FRUITS',
    servingSizeBn: '১ কাপ (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 25,
    giLevel: 'LOW',
    glPerServing: 3,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 60,
      proteinG: 0.7,
      carbsG: 14.0,
      fatG: 0.2,
      fiberG: 0.9,
      potassiumMg: 55,
      sodiumMg: 14,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ডায়াবেটিস রোগীদের মৌসুমী সুপারফ্রুট',
    clinicalNotesBn: 'জাম্বোলিন যৌগ রক্তে স্টার্চকে সুগারে রূপান্তর হওয়া বাধা দেয়। বীজের গুঁড়াও ডায়াবেটিসে উপকারি।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_lichu',
    nameBn: 'পাকা লিচু',
    nameEn: 'Lychee / Litchi Fruit',
    category: 'FRUITS',
    servingSizeBn: '৫-৬টি লিচু (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 70,
    giLevel: 'HIGH',
    glPerServing: 16,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 66,
      proteinG: 0.8,
      carbsG: 16.5,
      fatG: 0.4,
      fiberG: 1.3,
      potassiumMg: 171,
      sodiumMg: 1,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'পেয়ারা বা ড্রাগন ফল বেছে নিন',
    clinicalNotesBn: 'উচ্চ গ্লাইসেমিক ইনডেক্স; খালি পেটে খেলে সুগার ওঠানামা করতে পারে, ডায়াবেটিস রোগীদের পরিহার করা উচিত।',
  },
  {
    id: 'bf_dragon_fruit',
    nameBn: 'লাল / সাদা ড্রাগন ফল',
    nameEn: 'Dragon Fruit (Pitaya)',
    category: 'FRUITS',
    servingSizeBn: '১/২টি ফল (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 48,
    giLevel: 'LOW',
    glPerServing: 5,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 60,
      proteinG: 1.2,
      carbsG: 12.5,
      fatG: 0.6,
      fiberG: 3.0,
      potassiumMg: 190,
      sodiumMg: 0,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'মিষ্টি ফলের স্বাস্থ্যকর বিকল্প',
    clinicalNotesBn: 'বেটালাইন অ্যান্টিঅক্সিডেন্ট ও প্রি-বায়োটিক ফাইবার থাকায় রক্তনালীর প্রদাহ কমায়।',
    isTraditionalSuperfood: true,
  },

  // ==========================================
  // 5. LENTILS, BEANS & PULSES (ডাল ও শুঁটি)
  // ==========================================
  {
    id: 'bf_moshur_dal_patla',
    nameBn: 'মসুর ডাল (পাতলা ঝোল)',
    nameEn: 'Red Lentil Soup (Moshur Dal)',
    category: 'LENTILS_BEANS',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 32,
    giLevel: 'LOW',
    glPerServing: 6,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 78,
      proteinG: 5.8,
      carbsG: 12.0,
      fatG: 0.8,
      fiberG: 3.2,
      potassiumMg: 240,
      sodiumMg: 45,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'MODERATE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'ভাতের পরিমাণ কমিয়ে ডাল বেশি খান',
    clinicalNotesBn: 'কম GI ও উদ্ভিজ্জ প্রোটিন; ভাতের সাথে খেলে সামগ্রিক মিলের গ্লাইসেমিক লোড অনেক কমিয়ে দেয়।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_moong_dal',
    nameBn: 'মুগ ডাল (ভুনা বা সেদ্ধ)',
    nameEn: 'Yellow Moong Dal Curry',
    category: 'LENTILS_BEANS',
    servingSizeBn: '১ বাটি (১৫০ গ্রাম)',
    servingWeightG: 150,
    giValue: 38,
    giLevel: 'LOW',
    glPerServing: 8,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 95,
      proteinG: 7.2,
      carbsG: 14.5,
      fatG: 1.2,
      fiberG: 4.1,
      potassiumMg: 280,
      sodiumMg: 50,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'সহজপাচ্য ও গ্যাস্ট্রিক রোগীদের জন্য মসুরের চেয়ে ভালো',
    clinicalNotesBn: 'মুগ ডাল পেটে গ্যাস কম তৈরি করে এবং লো-পিউরিন হওয়ায় ইউরিক এসিড রোগীদের জন্য নিরাপদ।',
  },
  {
    id: 'bf_chhola_bhuna',
    nameBn: 'ছোলা বুট ভুনা (সেদ্ধ/হালকা তেল)',
    nameEn: 'Chickpeas Curry (Chhola Bhuna)',
    category: 'LENTILS_BEANS',
    servingSizeBn: '১ বাটি (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 28,
    giLevel: 'LOW',
    glPerServing: 6,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 140,
      proteinG: 8.5,
      carbsG: 21.0,
      fatG: 2.8,
      fiberG: 6.8,
      potassiumMg: 290,
      sodiumMg: 60,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'সিঙাড়া বা পুরির জায়গায় ছোলা বুট খান',
    clinicalNotesBn: 'উচ্চ আঁশ ও রেজিস্ট্যান্ট স্টার্চ থাকায় এটি রক্তের সুগার স্পাইক সম্পূর্ণ প্রতিরোধ করে দীর্ঘক্ষণ পেট ভরা রাখে।',
    isTraditionalSuperfood: true,
  },

  // ==========================================
  // 6. STREET FOOD, SWEETS & FESTIVE (মিষ্টি ও উৎসবের খাবার)
  // ==========================================
  {
    id: 'bf_roshogolla',
    nameBn: 'ঐতিহ্যবাহী রসগোল্লা (১টি)',
    nameEn: 'Traditional Bengali Roshogolla',
    category: 'SNACKS_SWEETS',
    servingSizeBn: '১টি মাঝারি রসগোল্লা (৫০ গ্রাম)',
    servingWeightG: 50,
    giValue: 88,
    giLevel: 'HIGH',
    glPerServing: 24,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 290,
      proteinG: 4.5,
      carbsG: 55.0,
      fatG: 6.0,
      fiberG: 0.0,
      potassiumMg: 60,
      sodiumMg: 25,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'SAFE',
    smartSwapBn: 'টক দই বা ছানার মিষ্টি (চিনি ছাড়া)',
    clinicalNotesBn: 'উচ্চ ঘনত্বের সুক্রোজ চিনির শিরা সরাসরি লিভারে ফ্রুক্টোজ লোড ও রক্তে তাৎক্ষণিক বিপজ্জনক সুগার স্পাইক তৈরি করে।',
  },
  {
    id: 'bf_kachchi_biryani',
    nameBn: 'ঢাকাই কাচ্চি বিরিয়ানি (বাসমতী/চিনিগুঁড়া)',
    nameEn: 'Dhaka Kachchi Biryani (Mutton/Beef)',
    category: 'SNACKS_SWEETS',
    servingSizeBn: '১ প্লেট (৩৫০ গ্রাম)',
    servingWeightG: 350,
    giValue: 78,
    giLevel: 'HIGH',
    glPerServing: 45,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 240,
      proteinG: 9.5,
      carbsG: 28.5,
      fatG: 11.0,
      fiberG: 1.1,
      potassiumMg: 220,
      sodiumMg: 340,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'AVOID',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'AVOID',
    smartSwapBn: 'চিকেন ওটস খিচুড়ি বা লাল চালের পোলাও',
    clinicalNotesBn: 'চর্বি, ডালডা ও ঘি-মিশ্রিত পলিশড চাল ইনসুলিন প্রতিরোধ তীব্র করে। সাথে শসা-সালাদ খেলে স্পাইক কিছুটা প্রশমিত হয়।',
  },
  {
    id: 'bf_fuchka',
    nameBn: 'ফুচকা (টক পানি ও আলু-ছোলা পুর)',
    nameEn: 'Fuchka / Pani Puri (5 pcs)',
    category: 'SNACKS_SWEETS',
    servingSizeBn: '৫টি ফুচকা (১০০ গ্রাম)',
    servingWeightG: 100,
    giValue: 68,
    giLevel: 'MEDIUM',
    glPerServing: 18,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 195,
      proteinG: 3.8,
      carbsG: 32.0,
      fatG: 5.5,
      fiberG: 2.2,
      potassiumMg: 150,
      sodiumMg: 280,
    },
    diabetesRating: 'MODERATE',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'তেঁতুলের টকে চিনি না দিয়ে কাঁচা মরিচ ও ধনেপাতা দিন',
    clinicalNotesBn: 'ময়দার খোল ও আলুর পুরের কারণে সুগার বাড়ে; তবে টক পানির সাইট্রিক এসিড হজমে সহায়তা করে।',
  },
  {
    id: 'bf_shahi_haleem',
    nameBn: 'শাহি হালিম (ডাল ও মাংস মিশ্রিত)',
    nameEn: 'Shahi Haleem (Multi-Lentil & Meat)',
    category: 'SNACKS_SWEETS',
    servingSizeBn: '১ বাটি (২০০ গ্রাম)',
    servingWeightG: 200,
    giValue: 48,
    giLevel: 'LOW',
    glPerServing: 12,
    glLevel: 'MEDIUM',
    nutrientsPer100g: {
      calories: 165,
      proteinG: 11.2,
      carbsG: 16.0,
      fatG: 6.8,
      fiberG: 4.5,
      potassiumMg: 310,
      sodiumMg: 260,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'MODERATE',
    uricAcidRating: 'AVOID',
    kidneySafetyRating: 'MODERATE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'গরুর মাংসের বদলে মুরগির হালিম খান এবং তেল/বেরেস্তা কম দিন',
    clinicalNotesBn: 'হালিমে পাঁচ মিশালি ডাল ও গম থাকায় GI কম। তবে ইউরিক এসিডের রোগীদের জন্য উচ্চ পিউরিনযুক্ত হওয়ায় সীমিত খাওয়া দরকার।',
  },
  {
    id: 'bf_singara',
    nameBn: 'সিঙাড়া (১টি তেলে ভাজা)',
    nameEn: 'Bangladeshi Potato Singara',
    category: 'SNACKS_SWEETS',
    servingSizeBn: '১টি সিঙাড়া (৬০ গ্রাম)',
    servingWeightG: 60,
    giValue: 80,
    giLevel: 'HIGH',
    glPerServing: 22,
    glLevel: 'HIGH',
    nutrientsPer100g: {
      calories: 310,
      proteinG: 4.8,
      carbsG: 42.0,
      fatG: 14.2,
      fiberG: 1.5,
      potassiumMg: 190,
      sodiumMg: 220,
    },
    diabetesRating: 'AVOID',
    fattyLiverRating: 'AVOID',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'সিদ্ধ ডিম বা একমুঠো চিনেবাদাম খান',
    clinicalNotesBn: 'ময়দার শক্ত খোল ও আলুর পুর ডুবো তেলে ভাজায় ট্রান্সফ্যাট ও হাই-জিআই তৈরি হয়।',
  },

  // ==========================================
  // 7. BEVERAGES & DRINKS (পানীয় ও শরবত)
  // ==========================================
  {
    id: 'bf_daber_pani',
    nameBn: 'কচি ডাবের পানি (প্রাকৃতিক)',
    nameEn: 'Fresh Green Coconut Water (Daber Pani)',
    category: 'BEVERAGES',
    servingSizeBn: '১ গ্লাস (২৫০ মিলি)',
    servingWeightG: 250,
    giValue: 45,
    giLevel: 'LOW',
    glPerServing: 4,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 19,
      proteinG: 0.7,
      carbsG: 3.7,
      fatG: 0.2,
      fiberG: 1.1,
      potassiumMg: 250,
      sodiumMg: 105,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'AVOID', // Crucial warning for CKD!
    hypertensionRating: 'RECOMMENDED',
    smartSwapBn: 'কোমল পানীয়ের ১০০% স্বাস্থ্যকর বিকল্প',
    clinicalNotesBn: 'প্রচুর ইলেক্ট্রোলাইট ও পটাশিয়াম থাকে যা প্রেশার কমায়। কিন্তু কিডনি (CKD) রোগীদের জন্য হাইপারক্যালেমিয়া ঝুঁকি থাকায় নিষিদ্ধ।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_borhani',
    nameBn: 'ঐতিহ্যবাহী বোরহানি (টক দই ও পুদিনা)',
    nameEn: 'Traditional Borhani (Spiced Yogurt Drink)',
    category: 'BEVERAGES',
    servingSizeBn: '১ গ্লাস (২০০ মিলি)',
    servingWeightG: 200,
    giValue: 28,
    giLevel: 'LOW',
    glPerServing: 3,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 55,
      proteinG: 3.2,
      carbsG: 4.8,
      fatG: 2.5,
      fiberG: 0.5,
      potassiumMg: 180,
      sodiumMg: 140,
    },
    diabetesRating: 'SAFE',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'MODERATE',
    smartSwapBn: 'চিনি বা অতিরিক্ত বিট লবণ ছাড়া ঘরে পাতা টক দই দিয়ে বানান',
    clinicalNotesBn: 'প্রোবায়োটিক ও জিরা-পুদিনা চর্বি হজমে সাহায্য করে এবং সুগার নিয়ন্ত্রণে রাখে।',
  },
  {
    id: 'bf_rong_cha',
    nameBn: 'চিনি ছাড়া আদা ও লেবু দিয়ে লাল চা',
    nameEn: 'Sugar-Free Ginger & Lemon Black Tea',
    category: 'BEVERAGES',
    servingSizeBn: '১ কাপ (১৫০ মিলি)',
    servingWeightG: 150,
    giValue: 0,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 2,
      proteinG: 0.1,
      carbsG: 0.4,
      fatG: 0.0,
      fiberG: 0.0,
      potassiumMg: 35,
      sodiumMg: 3,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'RECOMMENDED',
    smartSwapBn: 'দুধ-চিনির চায়ের সেরা বিকল্প',
    clinicalNotesBn: 'পলিফেনল ও অ্যান্টিঅক্সিডেন্ট ইনসুলিন সংবেদনশীলতা বাড়ায় ও প্রদাহ কমায়।',
    isTraditionalSuperfood: true,
  },
  {
    id: 'bf_isabgol_tokma',
    nameBn: 'ইসবগুলের ভুসি ও তোকমা দানার পানি',
    nameEn: 'Psyllium Husk & Basil Seeds (Isabgol Tokma)',
    category: 'BEVERAGES',
    servingSizeBn: '১ গ্লাস (২৫০ মিলি)',
    servingWeightG: 250,
    giValue: 10,
    giLevel: 'LOW',
    glPerServing: 0,
    glLevel: 'LOW',
    nutrientsPer100g: {
      calories: 12,
      proteinG: 0.4,
      carbsG: 1.8,
      fatG: 0.2,
      fiberG: 4.5,
      potassiumMg: 45,
      sodiumMg: 5,
    },
    diabetesRating: 'RECOMMENDED',
    fattyLiverRating: 'RECOMMENDED',
    uricAcidRating: 'SAFE',
    kidneySafetyRating: 'SAFE',
    hypertensionRating: 'RECOMMENDED',
    smartSwapBn: 'খাবারের ২০ মিনিট আগে খেলে সুগার স্পাইক ৩০% পর্যন্ত কমে',
    clinicalNotesBn: 'উচ্চ মিউসিলেজ আঁশ অন্ত্রের দেয়ালে জেল তৈরি করে গ্লুকোজ ও কোলেস্টেরল দ্রুত শোষণে বাধা দেয়।',
    isTraditionalSuperfood: true,
  },
];
