import { EmergencyContactItem } from '@/types/emergency-hotline';

export const EMERGENCY_HOTLINE_CATALOG: EmergencyContactItem[] = [
  // =========================================================================
  // 1. NATIONAL GOVERNMENT HELPLINES (জাতীয় সরকারি জরুরি হেল্পলাইন)
  // =========================================================================
  {
    id: 'emg_999',
    name: 'National Emergency Service (999)',
    nameBn: 'জাতীয় জরুরি সেবা (৯৯৯)',
    category: 'NATIONAL_GOVT',
    city: 'ALL_BD',
    areaDescriptionBn: 'সারাদেশে পুলিশ, অ্যাম্বুলেন্স ও ফায়ার সার্ভিসের জন্য টোল-ফ্রি',
    primaryPhone: '999',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['জরুরি অ্যাম্বুলেন্স', 'পুলিশ সহায়তা', 'ফায়ার সার্ভিস'],
    badgeColor: '#EF4444',
    isVerified: true,
  },
  {
    id: 'emg_16263',
    name: 'Shastho Batayon (16263)',
    nameBn: 'স্বাস্থ্য বাতায়ন (১৬২৬৩)',
    category: 'NATIONAL_GOVT',
    city: 'ALL_BD',
    areaDescriptionBn: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয় — ২৪ ঘণ্টা সরকারি ডাক্তার পরামর্শ',
    primaryPhone: '16263',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['২৪/৭ ডাক্তার পরামর্শ', 'টেলিমেডিসিন', 'হাসপাতাল তথ্য'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'emg_333',
    name: 'National Citizen Helpline (333)',
    nameBn: 'জাতীয় নাগরিক সেবা (৩৩৩)',
    category: 'NATIONAL_GOVT',
    city: 'ALL_BD',
    areaDescriptionBn: 'সরকারি কর্মকর্তা, দুর্যোগ ও জরুরি মানবিক সহায়তা কেন্দ্র',
    primaryPhone: '333',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি তথ্য', 'জরুরি খাদ্য ও ত্রাণ', 'বিশেষজ্ঞ পরামর্শ'],
    badgeColor: '#3B82F6',
    isVerified: true,
  },
  {
    id: 'emg_10655',
    name: 'IEDCR Disease Control Helpline',
    nameBn: 'আইইডিসিআর কন্ট্রোল রুম (১০৬৫৫)',
    category: 'NATIONAL_GOVT',
    city: 'ALL_BD',
    areaDescriptionBn: 'রোগতত্ত্ব, রোগ নিয়ন্ত্রণ ও গবেষণা ইনস্টিটিউট (IEDCR)',
    primaryPhone: '10655',
    alternatePhone: '01937110011',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সংক্রামক রোগ তথ্য', 'মহামারী সহায়তা', 'করোনা/ডেঙ্গু গাইড'],
    badgeColor: '#8B5CF6',
    isVerified: true,
  },
  {
    id: 'emg_199',
    name: 'Fire Service & Civil Defence',
    nameBn: 'ফায়ার সার্ভিস কন্ট্রোল রুম (১৯৯)',
    category: 'NATIONAL_GOVT',
    city: 'ALL_BD',
    areaDescriptionBn: 'জরুরি অগ্নিনির্বাপণ, সড়ক দুর্ঘটনা ও উদ্ধার অভিযান',
    primaryPhone: '199',
    alternatePhone: '02223355555',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['অগ্নিনির্বাপণ', 'উদ্ধারকারী অ্যাম্বুলেন্স', 'দুর্ঘটনা সহায়তা'],
    badgeColor: '#F97316',
    isVerified: true,
  },

  // =========================================================================
  // 2. AMBULANCE & ICU SERVICES (বিভাগভিত্তিক অ্যাম্বুলেন্স)
  // =========================================================================
  // DHAKA
  {
    id: 'amb_alif_dhaka',
    name: 'Alif ICU Ambulance Service',
    nameBn: 'আলিফ আইসিইউ ও এসি অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'ঢাকা ও দেশের যেকোনো জেলায় দ্রুত রোগী স্থানান্তর (২৪ ঘণ্টা)',
    primaryPhone: '01713205555',
    alternatePhone: '01817205555',
    whatsappPhone: '+8801713205555',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['ভেন্টিলেটর সহ ICU', 'NICU বেবি ইনকিউবেটর', 'AC/নন-এসি', 'ফ্রিজার অ্যাম্বুলেন্স'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },
  {
    id: 'amb_dmch_dhaka',
    name: 'Dhaka Medical College Hospital Ambulance',
    nameBn: 'ঢাকা মেডিকেল কলেজ হাসপাতাল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'বকশীবাজার, ঢাকা — সরকারি সার্বক্ষণিক সেবা',
    primaryPhone: '0255165001',
    alternatePhone: '01711234567',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'জরুরি ইমার্জেন্সি শিফট'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'amb_markazul_dhaka',
    name: 'Al-Markazul Islami Ambulance',
    nameBn: 'আল-মারকাযুল ইসলামী অ্যাম্বুলেন্স সার্ভিস',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'মোহাম্মদপুর, ঢাকা — সাশ্রয়ী মূল্যে অ্যাম্বুলেন্স ও ফ্রিজার সার্ভিস',
    primaryPhone: '01711822842',
    alternatePhone: '01911364567',
    whatsappPhone: '+8801711822842',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['আইসিইউ অ্যাম্বুলেন্স', 'লাশবাহী ফ্রিজার ভ্যান', 'সাশ্রয়ী ভাড়া'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },
  {
    id: 'amb_square_dhaka',
    name: 'Square Hospital Critical Care Ambulance',
    nameBn: 'স্কয়ার হাসপাতাল ক্রিটিক্যাল কেয়ার অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'পান্থপথ, ঢাকা — অ্যাডভান্সড লাইফ সাপোর্ট (ALS) ও ডাক্তার সহ',
    primaryPhone: '01713377775',
    alternatePhone: '10616',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['কার্ডিয়াক ICU অ্যাম্বুলেন্স', 'অন-বোর্ড ডাক্তার ও নার্স', 'পোর্টেবল ভেন্টিলেটর'],
    badgeColor: '#0284C7',
    isVerified: true,
  },
  {
    id: 'amb_united_dhaka',
    name: 'United Hospital Emergency Ambulance',
    nameBn: 'ইউনাইটেড হাসপাতাল ইমার্জেন্সি অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'গুলশান-২, ঢাকা — আন্তর্জাতিক মানের লাইফ সাপোর্ট',
    primaryPhone: '10666',
    alternatePhone: '01914001234',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['অ্যাডভান্সড লাইফ সাপোর্ট (ALS)', 'NICU ইনকিউবেটর', 'পোর্টেবল ডিফিব্রিলেটর'],
    badgeColor: '#0284C7',
    isVerified: true,
  },
  {
    id: 'amb_evercare_dhaka',
    name: 'Evercare Hospital Emergency Hotline',
    nameBn: 'এভারকেয়ার হাসপাতাল অ্যাম্বুলেন্স ও ইমার্জেন্সি',
    category: 'AMBULANCE_ICU',
    city: 'DHAKA',
    areaDescriptionBn: 'বসুন্ধরা আবাসিক এলাকা, ঢাকা',
    primaryPhone: '10678',
    alternatePhone: '01713047461',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['ইমার্জেন্সি ট্রমা টিম', 'আইসিইউ অ্যাম্বুলেন্স', 'কার্ডিয়াক মনিটরিং'],
    badgeColor: '#0284C7',
    isVerified: true,
  },

  // CHITTAGONG
  {
    id: 'amb_cmch_ctg',
    name: 'Chittagong Medical College Hospital Ambulance',
    nameBn: 'চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'CHITTAGONG',
    areaDescriptionBn: 'কে.বি. ফজলুল কাদের রোড, পাঁচলাইশ, চট্টগ্রাম',
    primaryPhone: '031619598',
    alternatePhone: '01711223344',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'জরুরি ট্রমা রেসপন্স'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'amb_max_ctg',
    name: 'Max Hospital ICU Ambulance Chittagong',
    nameBn: 'ম্যাক্স হাসপাতাল আইসিইউ অ্যাম্বুলেন্স চট্টগ্রাম',
    category: 'AMBULANCE_ICU',
    city: 'CHITTAGONG',
    areaDescriptionBn: 'মেহেদীবাগ, চট্টগ্রাম — ২৪ ঘণ্টা এসি ও আইসিইউ সেবা',
    primaryPhone: '01713998877',
    alternatePhone: '031622514',
    whatsappPhone: '+8801713998877',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['ICU সাপোর্ট', 'অক্সিজেন ও ভেন্টিলেটর', 'চট্টগ্রাম ও ঢাকা রুট'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },

  // SYLHET
  {
    id: 'amb_somch_sylhet',
    name: 'Sylhet MAG Osmani Medical College Ambulance',
    nameBn: 'সিলেট এমএজি ওসমানী মেডিকেল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'SYLHET',
    areaDescriptionBn: 'মেডিকেল রোড, কাজলশাহ, সিলেট',
    primaryPhone: '0821713667',
    alternatePhone: '01711334455',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'সিলেট বিভাগ ও ঢাকা রেফারেল'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'amb_mount_adora_sylhet',
    name: 'Mount Adora Hospital ICU Ambulance',
    nameBn: 'মাউন্ট এডোরা হাসপাতাল অ্যাম্বুলেন্স সিলেট',
    category: 'AMBULANCE_ICU',
    city: 'SYLHET',
    areaDescriptionBn: 'নয়া সড়ক / আখালিয়া, সিলেট',
    primaryPhone: '01798333222',
    alternatePhone: '0821727777',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['অ্যাডভান্সড লাইফ সাপোর্ট (ALS)', 'কার্ডিয়াক মনিটর', 'অক্সিজেন'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },

  // RAJSHAHI
  {
    id: 'amb_rmch_rajshahi',
    name: 'Rajshahi Medical College Hospital Ambulance',
    nameBn: 'রাজশাহী মেডিকেল কলেজ হাসপাতাল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'RAJSHAHI',
    areaDescriptionBn: 'লক্ষ্মীপুর, রাজশাহী',
    primaryPhone: '0721772150',
    alternatePhone: '01711445566',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'উত্তরবঙ্গ রেফারেল'],
    badgeColor: '#10B981',
    isVerified: true,
  },

  // KHULNA
  {
    id: 'amb_kmch_khulna',
    name: 'Khulna Medical College Hospital Ambulance',
    nameBn: 'খুলনা মেডিকেল কলেজ হাসপাতাল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'KHULNA',
    areaDescriptionBn: 'বয়রা, খুলনা',
    primaryPhone: '041761509',
    alternatePhone: '01711556677',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'খুলনা বিভাগীয় সার্ভিস'],
    badgeColor: '#10B981',
    isVerified: true,
  },

  // BARISAL
  {
    id: 'amb_sbmch_barisal',
    name: 'Sher-e-Bangla Medical College Ambulance',
    nameBn: 'শের-ই-বাংলা মেডিকেল কলেজ অ্যাম্বুলেন্স বরিশাল',
    category: 'AMBULANCE_ICU',
    city: 'BARISAL',
    areaDescriptionBn: 'বান্দ রোড, বরিশাল',
    primaryPhone: '04312173544',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'বরিশাল ও ঢাকা ওয়াটার/রোড ট্রান্সফার'],
    badgeColor: '#10B981',
    isVerified: true,
  },

  // RANGPUR
  {
    id: 'amb_rmc_rangpur',
    name: 'Rangpur Medical College Hospital Ambulance',
    nameBn: 'রংপুর মেডিকেল কলেজ হাসপাতাল অ্যাম্বুলেন্স',
    category: 'AMBULANCE_ICU',
    city: 'RANGPUR',
    areaDescriptionBn: 'মেডিকেল পূর্ব গেট, রংপুর',
    primaryPhone: '052162335',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['সরকারি অ্যাম্বুলেন্স', 'উত্তরবঙ্গ ইমার্জেন্সি'],
    badgeColor: '#10B981',
    isVerified: true,
  },

  // =========================================================================
  // 3. 24/7 MEDICAL OXYGEN CYLINDERS (মেডিকেল অক্সিজেন সিলিন্ডার)
  // =========================================================================
  {
    id: 'oxy_linde_bd',
    name: 'Linde Bangladesh Medical Oxygen',
    nameBn: 'লিন্ডে বাংলাদেশ মেডিকেল অক্সিজেন হেল্পলাইন',
    category: 'OXYGEN_CYLINDER',
    city: 'ALL_BD',
    areaDescriptionBn: 'সারাদেশে হাসপাতাল ও বাসায় হাই-গ্রেড মেডিকেল অক্সিজেন সিলিন্ডার',
    primaryPhone: '09606546333',
    alternatePhone: '01713045678',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['মেডিকেল অক্সিজেন রিফিল', 'ফ্লোমিটার ও ক্যানুলা', '২৪ ঘণ্টা জরুরি সাপোর্ট'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },
  {
    id: 'oxy_spectra_bd',
    name: 'Spectra Oxygen Home Delivery 24/7',
    nameBn: 'স্পেক্ট্রা অক্সিজেন হোম ডেলিভারি ২৪/৭',
    category: 'OXYGEN_CYLINDER',
    city: 'DHAKA',
    areaDescriptionBn: 'ঢাকা ও পার্শ্ববর্তী এলাকায় জরুরি অক্সিজেন সিলিন্ডার স্থাপন',
    primaryPhone: '01713338800',
    alternatePhone: '01911445566',
    whatsappPhone: '+8801713338800',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['অক্সিজেন সিলিন্ডার ও ট্রলি', 'অক্সিজেন কনসেনট্রেটর', 'জরুরি ডেলিভারি'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },
  {
    id: 'oxy_vitalcare_dhaka',
    name: 'VitalCare 24h Oxygen Express',
    nameBn: 'ভাইটাল কেয়ার ২৪ ঘণ্টা অক্সিজেন এক্সপ্রেস',
    category: 'OXYGEN_CYLINDER',
    city: 'DHAKA',
    areaDescriptionBn: 'উত্তরা, ধানমন্ডি, গুলশান ও মিরপুর অঞ্চলে ৩০ মিনিটে হোম ডেলিভারি',
    primaryPhone: '01819556677',
    whatsappPhone: '+8801819556677',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['অক্সিজেন সিলিন্ডার সেটআপ', 'পালস অক্সিমিটার', 'ফ্রি ট্রায়াল ও ইন্সটলেশন'],
    badgeColor: '#00B4D8',
    isVerified: true,
  },

  // =========================================================================
  // 4. 24/7 PHARMACIES & NIGHT HOME DELIVERY (২৪/৭ নাইট ফার্মেসি)
  // =========================================================================
  {
    id: 'phm_lazz_central',
    name: 'Lazz Pharma 24/7 Central Hotline',
    nameBn: 'লাজ ফার্মা ২৪/৭ সেন্ট্রাল হটলাইন (কলাবাগান)',
    category: 'PHARMACY_24_7',
    city: 'DHAKA',
    areaDescriptionBn: 'কলাবাগান সেন্ট্রাল ব্রাঞ্চ — দিন-রাত ২৪ ঘণ্টা খোলা ও ডেলিভারি',
    primaryPhone: '09613222777',
    alternatePhone: '01711534346',
    whatsappPhone: '+8801711534346',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['২৪/৭ ফার্মেসি কাউন্টার', 'জরুরি প্রেসক্রিপশন মেডিসিন', 'হোম ডেলিভারি'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'phm_arogga_24',
    name: 'Arogga 24/7 Online Medicine Express',
    nameBn: 'আরোগ্য ২৪/৭ অনলাইন মেডিসিন হেল্পলাইন',
    category: 'PHARMACY_24_7',
    city: 'ALL_BD',
    areaDescriptionBn: 'সারাদেশে জেনুইন প্রেসক্রিপশন ও ওটিসি মেডিসিন ডেলিভারি',
    primaryPhone: '01810117100',
    whatsappPhone: '+8801810117100',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['অনলাইন অর্ডার ও ট্র্যাকিং', 'ক্যাশ অন ডেলিভারি', 'ডিসকাউন্ট মেডিসিন'],
    badgeColor: '#0284C7',
    isVerified: true,
  },
  {
    id: 'phm_tamanna_dhaka',
    name: 'Tamanna Pharmacy 24 Hours',
    nameBn: 'তামান্না ফার্মেসি ২৪ ঘণ্টা নাইট ব্রাঞ্চ',
    category: 'PHARMACY_24_7',
    city: 'DHAKA',
    areaDescriptionBn: 'ধানমন্ডি ও মিরপুর রোড — রাতে যেকোনো লাইফ সেভিং ড্রাগ',
    primaryPhone: '01715123456',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['নাইট কাউন্টার', 'ইনসুলিন ও বায়োলজিক্স', 'আইসিইউ মেডিসিন'],
    badgeColor: '#10B981',
    isVerified: true,
  },
  {
    id: 'phm_dmc_gate',
    name: 'Dhaka Medical Main Gate 24/7 Pharmacy Hub',
    nameBn: 'ঢাকা মেডিকেল জরুরি বিভাগ গেট নাইট ফার্মেসি হাব',
    category: 'PHARMACY_24_7',
    city: 'DHAKA',
    areaDescriptionBn: 'বকশীবাজার, চাঁনখারপুল — সার্বক্ষণিক জরুরি ও ট্রমা ওষুধ',
    primaryPhone: '01819345678',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['ইমার্জেন্সি ট্রমা ড্রাগস', 'ব্লাড ট্রান্সফিউশন সেট', 'সার্জিক্যাল আইটেমস'],
    badgeColor: '#10B981',
    isVerified: true,
  },

  // =========================================================================
  // 5. EMERGENCY BLOOD BANKS (জরুরি ব্লাড ব্যাংক ও ডোনার হেল্পলাইন)
  // =========================================================================
  {
    id: 'bld_quantum_dhaka',
    name: 'Quantum Foundation Blood Lab',
    nameBn: 'কোয়ান্টাম ব্লাড ব্যাংক সেন্ট্রাল',
    category: 'BLOOD_BANK',
    city: 'DHAKA',
    areaDescriptionBn: 'শান্তিনগর, ঢাকা — সার্বক্ষণিক রক্ত ও প্লাটিলেট সরবরাহ কেন্দ্র',
    primaryPhone: '01714010869',
    alternatePhone: '029357990',
    whatsappPhone: '+8801714010869',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['হোল ব্লাড', 'প্লাটিলেট কনসেনট্রেট (PRP)', 'ফ্রেশ ফ্রোজেন প্লাজমা (FFP)'],
    badgeColor: '#EF4444',
    isVerified: true,
  },
  {
    id: 'bld_red_crescent',
    name: 'Bangladesh Red Crescent Blood Center',
    nameBn: 'বাংলাদেশ রেড ক্রিসেন্ট রক্ত কেন্দ্র',
    category: 'BLOOD_BANK',
    city: 'ALL_BD',
    areaDescriptionBn: '৭/৫ ঔরঙ্গজেব রোড, মোহাম্মদপুর, ঢাকা',
    primaryPhone: '029116563',
    alternatePhone: '01811458524',
    is24x7: true,
    isGovernment: true,
    servicesProvidedBn: ['নিরাপদ রক্ত পরিসঞ্চালন', 'ক্রস-ম্যাচিং ও স্ক্রিনিং', 'থ্যালাসেমিয়া সাপোর্ট'],
    badgeColor: '#EF4444',
    isVerified: true,
  },
  {
    id: 'bld_sandhani_central',
    name: 'Sandhani Central Blood Bank (DMC Unit)',
    nameBn: 'সন্ধানী কেন্দ্রীয় ব্লাড ব্যাংক (ডিএমসি ইউনিট)',
    category: 'BLOOD_BANK',
    city: 'DHAKA',
    areaDescriptionBn: 'ঢাকা মেডিকেল কলেজ ভবন, ঢাকা',
    primaryPhone: '029668690',
    alternatePhone: '01712282555',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['স্বেচ্ছায় রক্তদান', 'জরুরি ডোনার সমন্বয়', 'ব্লাড টেস্ট'],
    badgeColor: '#EF4444',
    isVerified: true,
  },
  {
    id: 'bld_badhan_central',
    name: 'Badhan Blood Transfusion Network',
    nameBn: 'বাঁধন কেন্দ্রীয় রক্ত সহায়তা নেটওয়ার্ক',
    category: 'BLOOD_BANK',
    city: 'ALL_BD',
    areaDescriptionBn: 'টিএসসি, ঢাকা বিশ্ববিদ্যালয় ও সকল পাবলিক বিশ্ববিদ্যালয় শাখা',
    primaryPhone: '01534982674',
    alternatePhone: '01717889900',
    is24x7: true,
    isGovernment: false,
    servicesProvidedBn: ['বিনামূল্যে রক্তের গ্রুপ নির্ণয়', 'জরুরি ডোনার সন্ধান', 'সারাদেশে নেটওয়ার্ক'],
    badgeColor: '#EF4444',
    isVerified: true,
  },
];
