import { GenericMoleculeGroup, MedicineBrandItem } from '@/types/generic-medicine';

export const GENERIC_MEDICINE_CATALOG: GenericMoleculeGroup[] = [
  // =========================================================================
  // 1. ANALGESICS & FEVER (প্যারাসিটামল ও পেইন কিলার)
  // =========================================================================
  {
    id: 'gen_paracetamol_plain',
    genericName: 'Paracetamol',
    bengaliGenericName: 'প্যারাসিটামল ৫০০ মিগ্রা',
    therapeuticClass: 'ANALGESIC_FEVER',
    classLabelBn: 'জ্বর ও সাধারণ ব্যথা নাশক',
    standardStrengths: ['500 mg', '665 mg'],
    overviewBn:
      'জ্বর, মাথা ব্যথা, শরীর ব্যথা ও দাঁতের ব্যথায় ব্যবহৃত ফার্স্ট-লাইন ব্যথানাশক ঔষধ।',
    brands: [
      {
        id: 'br_napa_500',
        brandName: 'Napa',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 1.2,
        stripSize: 10,
        stripPriceBdt: 12.0,
        indicationsEn: 'Fever, headache, toothache, body ache',
        indicationsBn: 'জ্বর, সাধারণ মাথাব্যথা ও গা-হাত-পা ব্যথা',
        adultDose: '১-২টি ট্যাবলেট প্রতি ৪-৬ ঘণ্টা পর পর (দৈনিক সর্বোচ্চ ৮টি)',
        safetyWarningsBn: 'দৈনিক ৪,০০০ মিগ্রা-র বেশি গ্রহণ লিভারের স্থায়ী ক্ষতি করতে পারে।',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_ace_500',
        brandName: 'Ace',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 1.2,
        stripSize: 10,
        stripPriceBdt: 12.0,
        indicationsEn: 'Fever, body pain, mild analgesia',
        indicationsBn: 'জ্বর, ইনফ্লুয়েঞ্জা ও সাধারণ ব্যথা',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_fast_500',
        brandName: 'Fast',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'The Acme Laboratories Ltd.',
        shortCompany: 'Acme',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 1.2,
        stripSize: 10,
        stripPriceBdt: 12.0,
        indicationsEn: 'Fever and mild to moderate pain',
        indicationsBn: 'জ্বর ও শরীর ব্যথা',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_renova_500',
        brandName: 'Renova',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Renata Limited',
        shortCompany: 'Renata',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 1.2,
        stripSize: 10,
        stripPriceBdt: 12.0,
        indicationsEn: 'Pyrexia & headache',
        indicationsBn: 'জ্বর ও মাথা ব্যথা',
        adultDose: '১টি ট্যাবলেট প্রতি ৬ ঘণ্টায়',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_pyralgin_500',
        brandName: 'Pyralgin',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Opsonin Pharma Limited',
        shortCompany: 'Opsonin',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 1.2,
        stripSize: 10,
        stripPriceBdt: 12.0,
        indicationsEn: 'Fever and pain relief',
        indicationsBn: 'জ্বর ও ব্যথা উপশম',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_napa_extend',
        brandName: 'Napa Extend',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '665 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.0,
        stripSize: 10,
        stripPriceBdt: 20.0,
        indicationsEn: 'Persistent backache, osteoarthritis & persistent pain',
        indicationsBn: 'দীর্ঘস্থায়ী কোমর ব্যথা, জয়েন্ট পেইন ও জ্বর (৮ ঘণ্টা কার্যকর)',
        adultDose: '২টি ট্যাবলেট প্রতি ৮ ঘণ্টা পর পর (দৈনিক সর্বোচ্চ ৬টি)',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_ace_xr',
        brandName: 'Ace XR',
        genericName: 'Paracetamol',
        genericId: 'gen_paracetamol_plain',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '665 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.0,
        stripSize: 10,
        stripPriceBdt: 20.0,
        indicationsEn: 'Sustained relief from pain and fever up to 8 hours',
        indicationsBn: '৮ ঘণ্টা পর্যন্ত একটানা দীর্ঘস্থায়ী ব্যথা ও জ্বর নিয়ন্ত্রণ',
        adultDose: '২টি ট্যাবলেট প্রতি ৮ ঘণ্টায়',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  {
    id: 'gen_paracetamol_caffeine',
    genericName: 'Paracetamol + Caffeine',
    bengaliGenericName: 'প্যারাসিটামল ৫০০ মিগ্রা + ক্যাফেইন ৬৫ মিগ্রা',
    therapeuticClass: 'ANALGESIC_FEVER',
    classLabelBn: 'তীব্র মাথাব্যথা ও এক্সট্রা পেইন কিলার',
    standardStrengths: ['500 mg + 65 mg'],
    overviewBn:
      'ক্যাফেইন প্যারাসিটামলের শোষণের গতি বাড়িয়ে তীব্র মাথাব্যথা ও মাইগ্রেন দ্রুত উপশম করে।',
    brands: [
      {
        id: 'br_napa_extra',
        brandName: 'Napa Extra',
        genericName: 'Paracetamol + Caffeine',
        genericId: 'gen_paracetamol_caffeine',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '500 mg + 65 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.5,
        stripSize: 10,
        stripPriceBdt: 25.0,
        indicationsEn: 'Severe headache, migraine, toothache, fever with body ache',
        indicationsBn: 'তীব্র মাথাব্যথা, মাইগ্রেন, দাঁত ব্যথা ও তীব্র জ্বর',
        adultDose: '১-২টি ট্যাবলেট প্রতি ৪-৬ ঘণ্টায় (দৈনিক সর্বোচ্চ ৮টি)',
        safetyWarningsBn: 'অতিরিক্ত চা/কফি পানের সাথে এটি খেলে অনিদ্রা বা অস্থিরতা হতে পারে।',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_ace_plus',
        brandName: 'Ace Plus',
        genericName: 'Paracetamol + Caffeine',
        genericId: 'gen_paracetamol_caffeine',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '500 mg + 65 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.5,
        stripSize: 10,
        stripPriceBdt: 25.0,
        indicationsEn: 'Severe headache, migraine and pain',
        indicationsBn: 'তীব্র মাথাব্যথা, স্নায়বিক যন্ত্রণা ও গা ব্যথা',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_fast_plus',
        brandName: 'Fast Plus',
        genericName: 'Paracetamol + Caffeine',
        genericId: 'gen_paracetamol_caffeine',
        manufacturer: 'The Acme Laboratories Ltd.',
        shortCompany: 'Acme',
        strength: '500 mg + 65 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.5,
        stripSize: 10,
        stripPriceBdt: 25.0,
        indicationsEn: 'Tension headache, migraine',
        indicationsBn: 'টেনশন হেডেক ও দ্রুত ব্যথানাশক',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_renova_extra',
        brandName: 'Renova Extra',
        genericName: 'Paracetamol + Caffeine',
        genericId: 'gen_paracetamol_caffeine',
        manufacturer: 'Renata Limited',
        shortCompany: 'Renata',
        strength: '500 mg + 65 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.5,
        stripSize: 10,
        stripPriceBdt: 25.0,
        indicationsEn: 'Headache & migraine relief',
        indicationsBn: 'তীব্র মাথাব্যথা ও জ্বর',
        adultDose: '১-২টি ট্যাবলেট প্রতি ৬ ঘণ্টায়',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_fevein_extra',
        brandName: 'Fevein Extra',
        genericName: 'Paracetamol + Caffeine',
        genericId: 'gen_paracetamol_caffeine',
        manufacturer: 'Healthcare Pharmaceuticals Ltd.',
        shortCompany: 'Healthcare',
        strength: '500 mg + 65 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 2.5,
        stripSize: 10,
        stripPriceBdt: 25.0,
        indicationsEn: 'Fast fever and headache relief',
        indicationsBn: 'মাথাব্যথা ও জ্বরে দ্রুত কার্যকর',
        adultDose: '১-২টি ট্যাবলেট দিনে ৩-৪ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  // =========================================================================
  // 2. GASTRIC, ACIDITY & PPIs (গ্যাস্ট্রিক ও আলসার প্রতিরোধী)
  // =========================================================================
  {
    id: 'gen_omeprazole',
    genericName: 'Omeprazole',
    bengaliGenericName: 'ওমিপ্রাজল ২০ মিগ্রা',
    therapeuticClass: 'GASTRIC_PPI',
    classLabelBn: 'গ্যাস্ট্রিক ও এসিডিটি প্রতিরোধী (PPI)',
    standardStrengths: ['20 mg', '40 mg'],
    overviewBn:
      'পাকস্থলীর প্রোটন পাম্প ব্লক করে অতিরিক্ত হাইড্রোক্লোরিক এসিড নিঃসরণ কমায় ও গ্যাস্ট্রিক আলসার নিরাময় করে।',
    brands: [
      {
        id: 'br_seclo_20',
        brandName: 'Seclo',
        genericName: 'Omeprazole',
        genericId: 'gen_omeprazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '20 mg',
        dosageForm: 'CAPSULE',
        unitPriceBdt: 6.0,
        stripSize: 10,
        stripPriceBdt: 60.0,
        indicationsEn: 'Gastric ulcer, GERD, acid reflux, heartburn',
        indicationsBn: 'গ্যাস্ট্রিক আলসার, বুক জ্বালাপোড়া ও এসিডিটি',
        adultDose: '১টি ক্যাপসুল দিনে ১-২ বার (খাবারের ৩০ মিনিট পূর্বে)',
        safetyWarningsBn: 'সবসময় সকালে খালি পেটে বা খাবারের আধা ঘণ্টা আগে সেবনীয়।',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_losectil_20',
        brandName: 'Losectil',
        genericName: 'Omeprazole',
        genericId: 'gen_omeprazole',
        manufacturer: 'Eskayef Pharmaceuticals Ltd. (SK+F)',
        shortCompany: 'SK+F',
        strength: '20 mg',
        dosageForm: 'CAPSULE',
        unitPriceBdt: 6.0,
        stripSize: 10,
        stripPriceBdt: 60.0,
        indicationsEn: 'Peptic ulcer, reflux esophagitis',
        indicationsBn: 'পেপটিক আলসার, বুক জ্বালা ও বদহজম',
        adultDose: '১টি ক্যাপসুল সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_proceptin_20',
        brandName: 'Proceptin',
        genericName: 'Omeprazole',
        genericId: 'gen_omeprazole',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '20 mg',
        dosageForm: 'CAPSULE',
        unitPriceBdt: 6.0,
        stripSize: 10,
        stripPriceBdt: 60.0,
        indicationsEn: 'Acid peptic disorder, GERD',
        indicationsBn: 'এসিড পেপটিক ডিজঅর্ডার ও আলসার',
        adultDose: '১টি ক্যাপসুল সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_ome_a_20',
        brandName: 'Ome-A',
        genericName: 'Omeprazole',
        genericId: 'gen_omeprazole',
        manufacturer: 'Aristopharma Ltd.',
        shortCompany: 'Aristopharma',
        strength: '20 mg',
        dosageForm: 'CAPSULE',
        unitPriceBdt: 5.0,
        stripSize: 10,
        stripPriceBdt: 50.0,
        indicationsEn: 'Affordable proton pump inhibitor for hyperacidity',
        indicationsBn: 'সাশ্রয়ী মূল্যে এসিডিটি ও আলসার নিরাময়',
        adultDose: '১টি ক্যাপসুল সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_omez_20',
        brandName: 'Omez',
        genericName: 'Omeprazole',
        genericId: 'gen_omeprazole',
        manufacturer: 'Renata Limited',
        shortCompany: 'Renata',
        strength: '20 mg',
        dosageForm: 'CAPSULE',
        unitPriceBdt: 6.0,
        stripSize: 10,
        stripPriceBdt: 60.0,
        indicationsEn: 'Heartburn, reflux & gastritis',
        indicationsBn: 'গ্যাস্ট্রাইটিস ও বুক জ্বালা',
        adultDose: '১টি ক্যাপসুল সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  {
    id: 'gen_esomeprazole',
    genericName: 'Esomeprazole',
    bengaliGenericName: 'ইসোমিপ্রাজল ২০/৪০ মিগ্রা',
    therapeuticClass: 'GASTRIC_PPI',
    classLabelBn: 'শক্তিশালী গ্যাস্ট্রিক ও রিফ্লাক্স প্রতিরোধী',
    standardStrengths: ['20 mg', '40 mg'],
    overviewBn:
      'ওমিপ্রাজলের আধুনিক এস-আইসোমার, যা আরও দীর্ঘস্থায়ীভাবে পাকস্থলীর এসিড নিয়ন্ত্রণ করে।',
    brands: [
      {
        id: 'br_sergel_20',
        brandName: 'Sergel',
        genericName: 'Esomeprazole',
        genericId: 'gen_esomeprazole',
        manufacturer: 'Healthcare Pharmaceuticals Ltd.',
        shortCompany: 'Healthcare',
        strength: '20 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 14,
        stripPriceBdt: 112.0,
        indicationsEn: 'GERD, erosive esophagitis, Zollinger-Ellison syndrome',
        indicationsBn: 'তীব্র গ্যাস্ট্রিক রিফ্লাক্স, বুক জ্বালা ও আলসার',
        adultDose: '১টি ট্যাবলেট দিনে ১-২ বার (খাবারের ৩০ মিনিট পূর্বে)',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_maxpro_20',
        brandName: 'Maxpro',
        genericName: 'Esomeprazole',
        genericId: 'gen_esomeprazole',
        manufacturer: 'Aristopharma Ltd.',
        shortCompany: 'Aristopharma',
        strength: '20 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 10,
        stripPriceBdt: 80.0,
        indicationsEn: 'Acid reflux, duodenal & gastric ulcer',
        indicationsBn: 'এসিডিটি, বুক জ্বালা ও পেট ফাঁপা',
        adultDose: '১টি ট্যাবলেট সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_nexum_20',
        brandName: 'Nexum',
        genericName: 'Esomeprazole',
        genericId: 'gen_esomeprazole',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '20 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 14,
        stripPriceBdt: 112.0,
        indicationsEn: 'Acid peptic disease, NSAID-induced ulcer prevention',
        indicationsBn: 'পেইন কিলারের সাথে গ্যাস্ট্রিক আলসার প্রতিরোধে',
        adultDose: '১টি ট্যাবলেট সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_esotid_20',
        brandName: 'Esotid',
        genericName: 'Esomeprazole',
        genericId: 'gen_esomeprazole',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '20 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 7.5,
        stripSize: 10,
        stripPriceBdt: 75.0,
        indicationsEn: 'Hyperacidity & reflux control',
        indicationsBn: 'এসিডিটি ও টক ঢেকুর নিরাময়',
        adultDose: '১টি ট্যাবলেট সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_opton_20',
        brandName: 'Opton',
        genericName: 'Esomeprazole',
        genericId: 'gen_esomeprazole',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '20 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 10,
        stripPriceBdt: 80.0,
        indicationsEn: 'GERD & gastric ulceration',
        indicationsBn: 'বুক জ্বালা ও দীর্ঘস্থায়ী এসিডিটি',
        adultDose: '১টি ট্যাবলেট সকালে খালি পেটে',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  // =========================================================================
  // 3. RESPIRATORY, ASTHMA & ALLERGY (অ্যালার্জি ও শ্বাসকষ্ট)
  // =========================================================================
  {
    id: 'gen_montelukast',
    genericName: 'Montelukast Sodium',
    bengaliGenericName: 'মন্টেলুকাস্ট ১০ মিগ্রা',
    therapeuticClass: 'RESPIRATORY_ALLERGY',
    classLabelBn: 'অ্যাজমা, শ্বাসকষ্ট ও এলার্জিক রাইনাইটিস',
    standardStrengths: ['10 mg', '5 mg', '4 mg'],
    overviewBn:
      'লিউকেট্রিন রিসেপ্টর এন্টাগনিস্ট যা শ্বাসনালীর সংকোচন রোধ করে শ্বাসপ্রশ্বাস সহজ ও অ্যালার্জি দূর করে।',
    brands: [
      {
        id: 'br_monas_10',
        brandName: 'Monas',
        genericName: 'Montelukast Sodium',
        genericId: 'gen_montelukast',
        manufacturer: 'The Acme Laboratories Ltd.',
        shortCompany: 'Acme',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 17.0,
        stripSize: 10,
        stripPriceBdt: 170.0,
        indicationsEn: 'Chronic asthma, allergic rhinitis, bronchospasm prevention',
        indicationsBn: 'হাঁপানি (অ্যাজমা), দীর্ঘস্থায়ী কাশি, নাক বন্ধ ও শ্বাসকষ্ট',
        adultDose: '১টি ট্যাবলেট প্রতিদিন রাতে ঘুমানোর পূর্বে',
        safetyWarningsBn: 'সর্বদা রাতে ঘুমানোর আগে সেবন করা সবচেয়ে কার্যকর।',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_montene_10',
        brandName: 'Montene',
        genericName: 'Montelukast Sodium',
        genericId: 'gen_montelukast',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 17.0,
        stripSize: 10,
        stripPriceBdt: 170.0,
        indicationsEn: 'Asthma & allergic rhinitis symptoms',
        indicationsBn: 'হাঁপানি ও ঠান্ডা-কাশি জনিত শ্বাসকষ্ট',
        adultDose: '১টি ট্যাবলেট প্রতিদিন রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_odmon_10',
        brandName: 'Odmon',
        genericName: 'Montelukast Sodium',
        genericId: 'gen_montelukast',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 17.0,
        stripSize: 10,
        stripPriceBdt: 170.0,
        indicationsEn: 'Prophylaxis of asthma, seasonal allergies',
        indicationsBn: 'সিজনাল অ্যালার্জি ও হাঁপানির টান',
        adultDose: '১টি ট্যাবলেট রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_lumona_10',
        brandName: 'Lumona',
        genericName: 'Montelukast Sodium',
        genericId: 'gen_montelukast',
        manufacturer: 'Healthcare Pharmaceuticals Ltd.',
        shortCompany: 'Healthcare',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 16.5,
        stripSize: 10,
        stripPriceBdt: 165.0,
        indicationsEn: 'Allergic asthma, cold and sneezing relief',
        indicationsBn: 'অ্যালার্জি জনিত হাঁচি, সর্দি ও শ্বাসকষ্ট',
        adultDose: '১টি ট্যাবলেট রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_provair_10',
        brandName: 'Provair',
        genericName: 'Montelukast Sodium',
        genericId: 'gen_montelukast',
        manufacturer: 'UniMed UniHealth Pharmaceuticals',
        shortCompany: 'UniMed',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 17.0,
        stripSize: 10,
        stripPriceBdt: 170.0,
        indicationsEn: 'Bronchial asthma prevention',
        indicationsBn: 'ব্রঙ্কিয়াল অ্যাজমা প্রতিরোধক',
        adultDose: '১টি ট্যাবলেট রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  {
    id: 'gen_fexofenadine',
    genericName: 'Fexofenadine Hydrochloride',
    bengaliGenericName: 'ফেক্সোফেনাডিন ১২০/১৮০ মিগ্রা',
    therapeuticClass: 'RESPIRATORY_ALLERGY',
    classLabelBn: 'নন-সিডেটিভ অ্যালার্জি ও চুলকানি নিরাময়',
    standardStrengths: ['120 mg', '180 mg', '60 mg'],
    overviewBn:
      'দ্বিতীয় প্রজন্মের অ্যান্টিহিস্টামিন যা ঘুম না এনেই চুলকানি, নাক দিয়ে পানি পড়া ও স্কিন অ্যালার্জি দূর করে।',
    brands: [
      {
        id: 'br_fexo_120',
        brandName: 'Fexo',
        genericName: 'Fexofenadine Hydrochloride',
        genericId: 'gen_fexofenadine',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '120 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 9.0,
        stripSize: 10,
        stripPriceBdt: 90.0,
        indicationsEn: 'Allergic rhinitis, urticaria, skin itch, watery eyes',
        indicationsBn: 'হাঁচি, নাক দিয়ে পানি পড়া, স্কিন অ্যালার্জি ও চুলকানি',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        safetyWarningsBn: 'ঘুমের ভাব হয় না, ফলে গাড়ি চালানো বা কাজের সময়েও নিরাপদ।',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_fixal_120',
        brandName: 'Fixal',
        genericName: 'Fexofenadine Hydrochloride',
        genericId: 'gen_fexofenadine',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '120 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 9.0,
        stripSize: 10,
        stripPriceBdt: 90.0,
        indicationsEn: 'Seasonal allergies, chronic idiopathic urticaria',
        indicationsBn: 'সিজনাল অ্যালার্জি ও ত্বকের লালচে ফুসকুড়ি',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_fexodine_120',
        brandName: 'Fexodine',
        genericName: 'Fexofenadine Hydrochloride',
        genericId: 'gen_fexofenadine',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '120 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.5,
        stripSize: 10,
        stripPriceBdt: 85.0,
        indicationsEn: 'Non-drowsy allergy relief',
        indicationsBn: 'ঘুমহীন অ্যালার্জি ও চুলকানি উপশম',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_rinar_120',
        brandName: 'Rinar',
        genericName: 'Fexofenadine Hydrochloride',
        genericId: 'gen_fexofenadine',
        manufacturer: 'Healthcare Pharmaceuticals Ltd.',
        shortCompany: 'Healthcare',
        strength: '120 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 9.0,
        stripSize: 10,
        stripPriceBdt: 90.0,
        indicationsEn: 'Allergic rhinitis and eczema itch',
        indicationsBn: 'এলার্জিক রাইনাইটিস ও একজিমা চুলকানি',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: true,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  // =========================================================================
  // 4. ANTIBIOTICS (অ্যান্টিবায়োটিক)
  // =========================================================================
  {
    id: 'gen_azithromycin',
    genericName: 'Azithromycin',
    bengaliGenericName: 'অ্যাজিথ্রোমাইসিন ৫০০ মিগ্রা',
    therapeuticClass: 'ANTIBIOTIC',
    classLabelBn: 'ম্যাক্রোলাইড অ্যান্টিবায়োটিক',
    standardStrengths: ['500 mg', '250 mg'],
    overviewBn:
      'গলা ব্যথা, টনসিলাইটিস, টাইফয়েড ও শ্বাসতন্ত্রের ব্যাকটেরিয়াল ইনফেকশনে ব্যবহৃত ৩-৫ দিনের অ্যান্টিবায়োটিক কোর্স।',
    brands: [
      {
        id: 'br_zithrin_500',
        brandName: 'Zithrin',
        genericName: 'Azithromycin',
        genericId: 'gen_azithromycin',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 35.0,
        stripSize: 6,
        stripPriceBdt: 210.0,
        indicationsEn: 'Throat infection, tonsillitis, RTI, enteric fever',
        indicationsBn: 'গলা ব্যথা, টনসিলাইটিস, ফুসফুসে ইনফেকশন ও টাইফয়েড',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার (খাবারের ১ ঘণ্টা আগে বা ২ ঘণ্টা পরে)',
        safetyWarningsBn: 'চিকিৎসকের প্রেসক্রিপশন অনুযায়ী পূর্ণ কোর্স (৩-৫ দিন) শেষ করুন।',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_azithrocin_500',
        brandName: 'Azithrocin',
        genericName: 'Azithromycin',
        genericId: 'gen_azithromycin',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 35.0,
        stripSize: 6,
        stripPriceBdt: 210.0,
        indicationsEn: 'Respiratory tract infections & skin soft tissue infection',
        indicationsBn: 'শ্বাসতন্ত্রের সংক্রমণ ও স্কিন ইনফেকশন',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_tridosil_500',
        brandName: 'Tridosil',
        genericName: 'Azithromycin',
        genericId: 'gen_azithromycin',
        manufacturer: 'Healthcare Pharmaceuticals Ltd.',
        shortCompany: 'Healthcare',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 35.0,
        stripSize: 6,
        stripPriceBdt: 210.0,
        indicationsEn: 'Broad spectrum macrolide antibiotic',
        indicationsBn: 'ব্যাকটেরিয়াল ইনফেকশন ও সাইনোসাইটিস',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_azith_500',
        brandName: 'Azith',
        genericName: 'Azithromycin',
        genericId: 'gen_azithromycin',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 35.0,
        stripSize: 6,
        stripPriceBdt: 210.0,
        indicationsEn: 'Bacterial chest and ENT infections',
        indicationsBn: 'কান, নাক, গলা ও বুকের ইনফেকশন',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_odazyth_500',
        brandName: 'Odazyth',
        genericName: 'Azithromycin',
        genericId: 'gen_azithromycin',
        manufacturer: 'Renata Limited',
        shortCompany: 'Renata',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 35.0,
        stripSize: 6,
        stripPriceBdt: 210.0,
        indicationsEn: 'Pneumonia and severe bronchitis',
        indicationsBn: 'নিউমোনিয়া ও ব্রঙ্কাইটিস ইনফেকশন',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  // =========================================================================
  // 5. CARDIOVASCULAR, HYPERTENSION & STATINS (রক্তচাপ ও কোলেস্টেরল)
  // =========================================================================
  {
    id: 'gen_losartan',
    genericName: 'Losartan Potassium',
    bengaliGenericName: 'লোসারটান পটাশিয়াম ৫০ মিগ্রা',
    therapeuticClass: 'CARDIOVASCULAR_BP',
    classLabelBn: 'উচ্চ রক্তচাপ ও হার্ট প্রটেকশন (ARB)',
    standardStrengths: ['50 mg', '25 mg', '100 mg'],
    overviewBn:
      'অ্যানজিওটেনসিন রিসেপ্টর ব্লকার (ARB) যা রক্তনালী শিথিল করে রক্তচাপ নিয়ন্ত্রণ ও কিডনি সুরক্ষা নিশ্চিত করে।',
    brands: [
      {
        id: 'br_angilock_50',
        brandName: 'Angilock',
        genericName: 'Losartan Potassium',
        genericId: 'gen_losartan',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '50 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 10,
        stripPriceBdt: 80.0,
        indicationsEn: 'Hypertension, diabetic nephropathy, stroke risk reduction',
        indicationsBn: 'উচ্চ রক্তচাপ (হাই প্রেশার) ও ডায়াবেটিক কিডনি সুরক্ষা',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার সকালে/রাতে',
        safetyWarningsBn: 'ডাক্তারের পরামর্শ ছাড়া হঠাৎ ওষুধ বন্ধ করবেন না।',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_osartil_50',
        brandName: 'Osartil',
        genericName: 'Losartan Potassium',
        genericId: 'gen_losartan',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '50 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 10,
        stripPriceBdt: 80.0,
        indicationsEn: 'Essential hypertension & left ventricular hypertrophy',
        indicationsBn: 'উচ্চ রক্তচাপ ও হার্ট অ্যাটাক ঝুঁকি কমানো',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_losan_50',
        brandName: 'Losan',
        genericName: 'Losartan Potassium',
        genericId: 'gen_losartan',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '50 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 8.0,
        stripSize: 10,
        stripPriceBdt: 80.0,
        indicationsEn: 'High BP management',
        indicationsBn: 'ব্লাড প্রেশার নিয়ন্ত্রণ',
        adultDose: '১টি ট্যাবলেট দিনে ১ বার',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  {
    id: 'gen_rosuvastatin',
    genericName: 'Rosuvastatin Calcium',
    bengaliGenericName: 'রসুভাস্ট্যাটিন ১০/২০ মিগ্রা',
    therapeuticClass: 'CARDIOVASCULAR_BP',
    classLabelBn: 'রক্তে খারাপ কোলেস্টেরল (LDL) ও ট্রাইগ্লিসারাইড হ্রাসকারী',
    standardStrengths: ['10 mg', '20 mg', '5 mg'],
    overviewBn:
      'এইচএমজি-কোএ রিডাকটেজ ইনহিবিটর যা লিভারে এলডিএল (LDL) কোলেস্টেরল উৎপাদন কমিয়ে হার্ট অ্যাটাক ও স্ট্রোক প্রতিরোধ করে।',
    brands: [
      {
        id: 'br_lipicon_10',
        brandName: 'Lipicon',
        genericName: 'Rosuvastatin Calcium',
        genericId: 'gen_rosuvastatin',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 25.0,
        stripSize: 10,
        stripPriceBdt: 250.0,
        indicationsEn: 'Hypercholesterolemia, dyslipidemia, atherosclerosis prevention',
        indicationsBn: 'রক্তে অতিরিক্ত চর্বি/কোলেস্টেরল ও রক্তনালী ব্লক প্রতিরোধ',
        adultDose: '১টি ট্যাবলেট প্রতিদিন রাতে ঘুমানোর পূর্বে',
        safetyWarningsBn: 'সবসময় রাতে সেবন করুন; নিয়মিত লিভার এনজাইম পরীক্ষা করুন।',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_rosuva_10',
        brandName: 'Rosuva',
        genericName: 'Rosuvastatin Calcium',
        genericId: 'gen_rosuvastatin',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 25.0,
        stripSize: 10,
        stripPriceBdt: 250.0,
        indicationsEn: 'Primary hyperlipidemia & mixed dyslipidemia',
        indicationsBn: 'উচ্চ কোলেস্টেরল ও হার্টের সুস্থতা',
        adultDose: '১টি ট্যাবলেট রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_rosutec_10',
        brandName: 'Rosutec',
        genericName: 'Rosuvastatin Calcium',
        genericId: 'gen_rosuvastatin',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '10 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 24.0,
        stripSize: 10,
        stripPriceBdt: 240.0,
        indicationsEn: 'Cholesterol lowering statin',
        indicationsBn: 'কোলেস্টেরল কমানো ও ধমনীর চর্বি পরিষ্কার',
        adultDose: '১টি ট্যাবলেট রাতে',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
    ],
  },

  // =========================================================================
  // 6. DIABETES (ডায়াবেটিস নিয়ন্ত্রণ)
  // =========================================================================
  {
    id: 'gen_metformin',
    genericName: 'Metformin Hydrochloride',
    bengaliGenericName: 'মেটফরমিন ৫০০/৮৫০ মিগ্রা',
    therapeuticClass: 'DIABETES',
    classLabelBn: 'টাইপ-২ ডায়াবেটিসে ইনসুলিন সেন্সিটাইজার',
    standardStrengths: ['500 mg', '850 mg', '1000 mg'],
    overviewBn:
      'লিভারে অতিরিক্ত গ্লুকোজ উৎপাদন কমায় এবং শরীরের টিস্যুতে ইনসুলিনের কার্যকারিতা বাড়ায়।',
    brands: [
      {
        id: 'br_comet_500',
        brandName: 'Comet',
        genericName: 'Metformin Hydrochloride',
        genericId: 'gen_metformin',
        manufacturer: 'Square Pharmaceuticals PLC',
        shortCompany: 'Square',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 4.0,
        stripSize: 10,
        stripPriceBdt: 40.0,
        indicationsEn: 'Type 2 diabetes mellitus, insulin resistance, PCOS',
        indicationsBn: 'টাইপ-২ ডায়াবেটিস ও পিসিওএস (PCOS) গ্লুকোজ নিয়ন্ত্রণ',
        adultDose: '১টি ট্যাবলেট দিনে ১-২ বার (ভারী খাবারের সাথে বা ঠিক পরে)',
        safetyWarningsBn: 'গ্যাস্ট্রিক বা পেটের অস্বস্তি এড়াতে ভরা পেটে সেবন করুন।',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_daomet_500',
        brandName: 'Daomet',
        genericName: 'Metformin Hydrochloride',
        genericId: 'gen_metformin',
        manufacturer: 'Beximco Pharmaceuticals Ltd.',
        shortCompany: 'Beximco',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 4.0,
        stripSize: 10,
        stripPriceBdt: 40.0,
        indicationsEn: 'Glycemic control in type 2 diabetes',
        indicationsBn: 'রক্তের সুগার নিয়ন্ত্রণে প্রথম সারির ওষুধ',
        adultDose: '১টি ট্যাবলেট খাবারের পর',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
      {
        id: 'br_informet_500',
        brandName: 'Informet',
        genericName: 'Metformin Hydrochloride',
        genericId: 'gen_metformin',
        manufacturer: 'Incepta Pharmaceuticals Ltd.',
        shortCompany: 'Incepta',
        strength: '500 mg',
        dosageForm: 'TABLET',
        unitPriceBdt: 4.0,
        stripSize: 10,
        stripPriceBdt: 40.0,
        indicationsEn: 'Oral anti-diabetic biguanide',
        indicationsBn: 'টাইপ-২ ডায়াবেটিস নিয়ন্ত্রণে কার্যকর',
        adultDose: '১টি ট্যাবলেট খাবারের পর',
        isOtc: false,
        companyTier: 'TOP_TIER',
      },
    ],
  },
];
