import {
  DiagnosticCenterId,
  DiagnosticCenterInfo,
  LabTestPriceItem,
} from '@/types/lab-cost-comparator';

export const DIAGNOSTIC_CENTERS: DiagnosticCenterInfo[] = [
  {
    id: 'POPULAR',
    nameEn: 'Popular Diagnostic Centre',
    nameBn: 'পপুলার ডায়াগনস্টিক সেন্টার',
    shortName: 'Popular',
    tier: 'HIGH_ACCURACY_STANDARD',
    branchCountBn: '৩৫+ ব্রাঞ্চ (ঢাকা, ধানমন্ডি, শান্তিনগর, চট্টগ্রাম ও সারা দেশ)',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ২০০ (ঢাকা মেট্রো)',
    hotline: '09613787801',
    website: 'https://populardiagnostic.com',
    discountNoteBn: 'সন্ধ্যা ও বিভিন্ন ক্রেডিট কার্ডে ১০% পর্যন্ত ছাড়।',
    rating: 4.8,
    color: '#0284C7',
  },
  {
    id: 'IBN_SINA',
    nameEn: 'Ibn Sina Diagnostic & Consultation',
    nameBn: 'ইবনে সিনা ডায়াগনস্টিক সেন্টার',
    shortName: 'Ibn Sina',
    tier: 'AFFORDABLE_MASS',
    branchCountBn: '২৫+ ব্রাঞ্চ (ধানমন্ডি, মিরপুর, উত্তরা, বাড্ডা, সিলেট)',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ১৫০ (সরাসরি বুকিং)',
    hotline: '10615',
    website: 'https://ibnsinatrust.com',
    discountNoteBn: 'তুলনামূলক সাশ্রয়ী টেস্ট মূল্য ও নিয়মিত মেডিকেল ক্যাম্প ডিসকাউন্ট।',
    rating: 4.7,
    color: '#10B981',
  },
  {
    id: 'LABAID',
    nameEn: 'Labaid Diagnostic',
    nameBn: 'ল্যাবএইড ডায়াগনস্টিক',
    shortName: 'Labaid',
    tier: 'PREMIUM_CORPORATE',
    branchCountBn: '৩০+ ব্রাঞ্চ (গুলশান, ধানমন্ডি, বনানী ও বিভাগীয় শহর)',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ২৫০',
    hotline: '10606',
    website: 'https://labaidgroup.com',
    discountNoteBn: 'ল্যাবএইড কার্ড হোল্ডারদের জন্য ১০-১৫% প্রিভিলেজ ছাড়।',
    rating: 4.6,
    color: '#E11D48',
  },
  {
    id: 'PRAAVA',
    nameEn: 'Praava Health Digital Lab',
    nameBn: 'প্রাভা হেলথ ডায়াগনস্টিক',
    shortName: 'Praava',
    tier: 'PREMIUM_CORPORATE',
    branchCountBn: 'বনানী ফ্ল্যাগশিপ ও হোম কালেকশন ভ্যান নেটওয়ার্ক',
    homeSampleAvailable: true,
    homeSampleFeeBn: 'ফ্রি (৳ ২,০০০+ টেস্টে) নতুবা ৳ ২০০',
    hotline: '10648',
    website: 'https://praavahealth.com',
    discountNoteBn: 'আন্তর্জাতিক ল্যাব স্ট্যান্ডার্ড ও অ্যাপে ডিজিটাল রিপোর্ট।',
    rating: 4.8,
    color: '#8B5CF6',
  },
  {
    id: 'THYROCARE',
    nameEn: 'Thyrocare Bangladesh',
    nameBn: 'থাইরোকেয়ার বাংলাদেশ',
    shortName: 'Thyrocare',
    tier: 'AFFORDABLE_MASS',
    branchCountBn: 'অটোমেটেড সেন্ট্রাল ল্যাব ও ডোরস্টেপ পিকআপ',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ১০০ (ফ্রি ৩০০০+ টেস্টে)',
    hotline: '09666737373',
    website: 'https://thyrocarebd.com',
    discountNoteBn: 'থাইরয়েড, ভিটামিন ও কম্বো হেলথ প্যাকেজে ৪০% পর্যন্ত সাশ্রয়ী।',
    rating: 4.5,
    color: '#F59E0B',
  },
  {
    id: 'MEDINOVA',
    nameEn: 'Medinova Medical Services',
    nameBn: 'মেদিনোভা মেডিকেল সার্ভিসেস',
    shortName: 'Medinova',
    tier: 'AFFORDABLE_MASS',
    branchCountBn: 'ধানমন্ডি, মালিবাগ ও মিরপুর ব্রাঞ্চ',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ২০০',
    hotline: '01711594488',
    website: 'https://medinova.com.bd',
    discountNoteBn: 'ঐতিহ্যবাহী নির্ভরযোগ্য ডায়াগনস্টিক ও সাশ্রয়ী ইউএসজি টেস্ট।',
    rating: 4.4,
    color: '#06B6D4',
  },
  {
    id: 'SQUARE',
    nameEn: 'Square Hospital Laboratory',
    nameBn: 'স্কয়ার হসপিটাল ল্যাবরেটরি',
    shortName: 'Square',
    tier: 'PREMIUM_CORPORATE',
    branchCountBn: 'পান্থপথ ও উত্তরা সেন্টার',
    homeSampleAvailable: true,
    homeSampleFeeBn: '৳ ৫০০',
    hotline: '10616',
    website: 'https://squarehospital.com',
    discountNoteBn: 'টারশিয়ারি সুপার-স্পেশালিটি টেস্ট ও জেসিআই (JCI) এক্রিডিটেশন।',
    rating: 4.9,
    color: '#EC4899',
  },
  {
    id: 'BIRDEM',
    nameEn: 'BIRDEM General Hospital Lab',
    nameBn: 'বারডেম জেনারেল হসপিটাল ল্যাব',
    shortName: 'BIRDEM',
    tier: 'SPECIALIZED_ENDOCRINE',
    branchCountBn: 'শাহবাগ ও সেগুনবাগিচা',
    homeSampleAvailable: false,
    homeSampleFeeBn: 'প্রযোজ্য নয়',
    hotline: '028616641',
    website: 'https://dab-bd.org',
    discountNoteBn: 'ডায়াবেটিস ও হরমোন টেস্টের জাতীয় রেফারেন্স ল্যাব।',
    rating: 4.7,
    color: '#14B8A6',
  },
  {
    id: 'BSMMU_GOVT',
    nameEn: 'BSMMU & Govt Diagnostic',
    nameBn: 'বিএসএমএমইউ (পিজি) ও সরকারি ল্যাব',
    shortName: 'BSMMU (Govt)',
    tier: 'GOVT_SUBSIDIZED',
    branchCountBn: 'শাহবাগ ও সরকারি মেডিকেল কলেজসমূহ',
    homeSampleAvailable: false,
    homeSampleFeeBn: 'প্রযোজ্য নয়',
    hotline: '0255165600',
    discountNoteBn: 'সরকারি সর্বোচ্চ ভর্তুকিপ্রাপ্ত মূল্য (সকাল ৮টা থেকে দুপুর ২টা)।',
    rating: 4.3,
    color: '#64748B',
  },
];

export const LAB_TEST_DATABASE: LabTestPriceItem[] = [
  // =========================================================================
  // 1. BLOOD ROUTINE
  // =========================================================================
  {
    id: 'test_cbc',
    code: 'CBC',
    nameEn: 'CBC with ESR (Complete Blood Count)',
    nameBn: 'সিবিসি ও ইএসআর (রক্তের সাধারণ পরীক্ষা)',
    shortDescriptionBn: 'হিমোগ্লোবিন, শ্বেত রক্তকণিকা (WBC), অনুচক্রিকা (Platelet) ও রক্তস্বল্পতা নির্ণয়।',
    category: 'BLOOD_ROUTINE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'খালি পেটে থাকার প্রয়োজন নেই। যে কোনো সময় রক্ত দেওয়া যায়।',
    prices: {
      POPULAR: 450,
      IBN_SINA: 400,
      LABAID: 550,
      PRAAVA: 450,
      THYROCARE: 380,
      MEDINOVA: 400,
      SQUARE: 950,
      BIRDEM: 350,
      BSMMU_GOVT: 150,
    },
    averagePrice: 450,
  },
  {
    id: 'test_blood_group',
    code: 'ABO_RH',
    nameEn: 'Blood Grouping & Rh Factor',
    nameBn: 'ব্লাড গ্রুপিং ও আরএইচ ফ্যাক্টর',
    shortDescriptionBn: 'রক্তের গ্রুপ (A, B, AB, O) এবং পজিটিভ/নেগেটিভ টাইপ নির্ধারণ।',
    category: 'BLOOD_ROUTINE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'কোনো প্রস্তুতির দরকার নেই।',
    prices: {
      POPULAR: 200,
      IBN_SINA: 150,
      LABAID: 250,
      PRAAVA: 200,
      THYROCARE: 150,
      MEDINOVA: 150,
      SQUARE: 450,
      BIRDEM: 150,
      BSMMU_GOVT: 80,
    },
    averagePrice: 200,
  },
  {
    id: 'test_crp',
    code: 'CRP',
    nameEn: 'C-Reactive Protein (Quantitative CRP)',
    nameBn: 'সিআরপি (শরীরের প্রদাহ ও ইনফেকশন মার্কার)',
    shortDescriptionBn: 'শরীরের তীব্র প্রদাহ, ব্যাকটেরিয়াল ইনফেকশন ও হার্ট রিস্ক নির্দেশক।',
    category: 'BLOOD_ROUTINE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'সাধারণ খাবার খাওয়ার পর যে কোনো সময় পরীক্ষা করা যায়।',
    prices: {
      POPULAR: 600,
      IBN_SINA: 550,
      LABAID: 750,
      PRAAVA: 600,
      THYROCARE: 450,
      MEDINOVA: 500,
      SQUARE: 1200,
      BIRDEM: 450,
      BSMMU_GOVT: 200,
    },
    averagePrice: 600,
  },

  // =========================================================================
  // 2. DIABETES & GLUCOSE
  // =========================================================================
  {
    id: 'test_hba1c',
    code: 'HBA1C',
    nameEn: 'HbA1c (Glycated Hemoglobin)',
    nameBn: 'এইচবিএওয়ানসি (বিগত ৩ মাসের গড় সুগার)',
    shortDescriptionBn: 'ডায়াবেটিস নিয়ন্ত্রণের গোল্ড স্ট্যান্ডার্ড পরীক্ষা।',
    category: 'DIABETES_GLUCOSE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'খালি পেটে থাকা বাধ্যতামূলক নয়, দিনের যে কোনো সময় রক্ত দেওয়া যায়।',
    prices: {
      POPULAR: 1000,
      IBN_SINA: 900,
      LABAID: 1200,
      PRAAVA: 900,
      THYROCARE: 750,
      MEDINOVA: 850,
      SQUARE: 1800,
      BIRDEM: 700,
      BSMMU_GOVT: 350,
    },
    averagePrice: 950,
  },
  {
    id: 'test_fbs',
    code: 'FBS',
    nameEn: 'Fasting Blood Sugar (FBS)',
    nameBn: 'ফাস্টিং ব্লাড গ্লুকোজ (খালি পেটে সুগার)',
    shortDescriptionBn: 'সকালে খালি পেটে রক্তের গ্লুকোজের মাত্রা নির্ণয়।',
    category: 'DIABETES_GLUCOSE',
    specimenType: 'BLOOD',
    fastingHours: 8,
    preparationRuleBn: '🥣 রাতে ৮ থেকে ১০ ঘণ্টা না খেয়ে সকালে রক্ত দিতে হবে। পানি পান করা যাবে।',
    prices: {
      POPULAR: 200,
      IBN_SINA: 150,
      LABAID: 250,
      PRAAVA: 180,
      THYROCARE: 150,
      MEDINOVA: 150,
      SQUARE: 450,
      BIRDEM: 120,
      BSMMU_GOVT: 60,
    },
    averagePrice: 200,
  },
  {
    id: 'test_2habf',
    code: '2HABF',
    nameEn: 'Blood Sugar 2 Hours After Breakfast (2HABF)',
    nameBn: 'নাস্তার ২ ঘণ্টা পর ব্লাড সুগার',
    shortDescriptionBn: 'খাবার খাওয়ার পর অগ্ন্যাশয় পর্যাপ্ত ইনসুলিন নিঃসরণ করছে কি না তা যাচাই।',
    category: 'DIABETES_GLUCOSE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'নাস্তার প্রথম লোকমা খাওয়ার ঠিক ২ ঘণ্টা পর রক্ত দিতে হবে।',
    prices: {
      POPULAR: 200,
      IBN_SINA: 150,
      LABAID: 250,
      PRAAVA: 180,
      THYROCARE: 150,
      MEDINOVA: 150,
      SQUARE: 450,
      BIRDEM: 120,
      BSMMU_GOVT: 60,
    },
    averagePrice: 200,
  },

  // =========================================================================
  // 3. KIDNEY & LIVER
  // =========================================================================
  {
    id: 'test_creatinine',
    code: 'S_CREATININE',
    nameEn: 'Serum Creatinine with eGFR',
    nameBn: 'সিরাম ক্রিয়েটিনিন ও কিডনি ফিল্ট্রেশন (eGFR)',
    shortDescriptionBn: 'কিডনির কার্যক্ষমতা ও রক্ত ছাঁকার হার পরিমাপের প্রধান পরীক্ষা।',
    category: 'KIDNEY_LIVER',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'টেস্টের আগের রাতে অতিরিক্ত গরুর মাংস বা রেড মিট না খাওয়ার পরামর্শ দেওয়া হয়।',
    prices: {
      POPULAR: 400,
      IBN_SINA: 350,
      LABAID: 450,
      PRAAVA: 380,
      THYROCARE: 300,
      MEDINOVA: 350,
      SQUARE: 850,
      BIRDEM: 300,
      BSMMU_GOVT: 150,
    },
    averagePrice: 400,
  },
  {
    id: 'test_sgpt',
    code: 'SGPT_ALT',
    nameEn: 'SGPT / ALT (Liver Enzyme)',
    nameBn: 'এসজিপিটি / এএলটি (লিভারের এনজাইম পরীক্ষা)',
    shortDescriptionBn: 'ফ্যাটি লিভার, জন্ডিস ও লিভারের কোষের ক্ষতি নির্ণয়।',
    category: 'KIDNEY_LIVER',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'খালি পেটে থাকার প্রয়োজন নেই।',
    prices: {
      POPULAR: 450,
      IBN_SINA: 400,
      LABAID: 500,
      PRAAVA: 400,
      THYROCARE: 300,
      MEDINOVA: 400,
      SQUARE: 900,
      BIRDEM: 300,
      BSMMU_GOVT: 150,
    },
    averagePrice: 430,
  },
  {
    id: 'test_uric_acid',
    code: 'S_URIC_ACID',
    nameEn: 'Serum Uric Acid',
    nameBn: 'সিরাম ইউরিক এসিড (বাত ও জয়েন্টে ব্যথা)',
    shortDescriptionBn: 'পায়ের আঙুল বা গিঁটে তীব্র ব্যথা ও গাউট (Gout) রোগ ডায়াগনোসিস।',
    category: 'KIDNEY_LIVER',
    specimenType: 'BLOOD',
    fastingHours: 4,
    preparationRuleBn: '৪ ঘণ্টা হালকা খালি পেটে টেস্ট করা ভালো।',
    prices: {
      POPULAR: 450,
      IBN_SINA: 400,
      LABAID: 500,
      PRAAVA: 400,
      THYROCARE: 300,
      MEDINOVA: 380,
      SQUARE: 850,
      BIRDEM: 300,
      BSMMU_GOVT: 150,
    },
    averagePrice: 420,
  },
  {
    id: 'test_bilirubin',
    code: 'S_BILIRUBIN',
    nameEn: 'Serum Bilirubin (Total, Direct & Indirect)',
    nameBn: 'সিরাম বিলিরুবিন (জন্ডিস পরীক্ষা)',
    shortDescriptionBn: 'চোখ ও প্রস্রাব হলুদ হওয়া বা হেপাটাইটিস ভাইরাসে জন্ডিসের মাত্রা যাচাই।',
    category: 'KIDNEY_LIVER',
    specimenType: 'BLOOD',
    fastingHours: 4,
    preparationRuleBn: 'হালকা না খেয়ে রক্ত দেওয়া উত্তম।',
    prices: {
      POPULAR: 450,
      IBN_SINA: 400,
      LABAID: 500,
      PRAAVA: 400,
      THYROCARE: 300,
      MEDINOVA: 380,
      SQUARE: 900,
      BIRDEM: 300,
      BSMMU_GOVT: 150,
    },
    averagePrice: 430,
  },

  // =========================================================================
  // 4. HEART & LIPID
  // =========================================================================
  {
    id: 'test_lipid_profile',
    code: 'LIPID_PROFILE',
    nameEn: 'Lipid Profile (Cholesterol, HDL, LDL, TG)',
    nameBn: 'লিপিড প্রোফাইল (রক্তের চর্বি ও কোলেস্টেরল প্যানেল)',
    shortDescriptionBn: 'টোটাল কোলেস্টেরল, ভালো চর্বি (HDL), খারাপ চর্বি (LDL) ও ট্রাইগ্লিসারাইড।',
    category: 'HEART_LIPID',
    specimenType: 'BLOOD',
    fastingHours: 12,
    preparationRuleBn: '🥣 অত্যন্ত গুরুত্বপূর্ণ: টেস্টের আগে টানা ১০ থেকে ১২ ঘণ্টা সম্পূর্ণ না খেয়ে থাকতে হবে (শুধু পানি পান করা যাবে)।',
    prices: {
      POPULAR: 1400,
      IBN_SINA: 1250,
      LABAID: 1650,
      PRAAVA: 1300,
      THYROCARE: 1100,
      MEDINOVA: 1200,
      SQUARE: 2400,
      BIRDEM: 1000,
      BSMMU_GOVT: 500,
    },
    averagePrice: 1350,
  },
  {
    id: 'test_ecg',
    code: 'ECG_12L',
    nameEn: 'ECG (12-Lead Electrocardiogram)',
    nameBn: 'ইসিজি (হার্টের বৈদ্যুতিক তরঙ্গ ও রিদম)',
    shortDescriptionBn: 'বুক ধড়ফড়ানি, হার্ট অ্যাটাক রিস্ক ও হৃদস্পন্দনের তারতম্য দেখা।',
    category: 'HEART_LIPID',
    specimenType: 'IMAGING',
    fastingHours: 0,
    preparationRuleBn: 'কোনো উপবাসের দরকার নেই। পরীক্ষার সময় শান্ত হয়ে শুয়ে থাকতে হবে।',
    prices: {
      POPULAR: 450,
      IBN_SINA: 400,
      LABAID: 550,
      PRAAVA: 500,
      THYROCARE: 400,
      MEDINOVA: 400,
      SQUARE: 1100,
      BIRDEM: 350,
      BSMMU_GOVT: 150,
    },
    averagePrice: 480,
  },
  {
    id: 'test_echo',
    code: 'ECHO_2D',
    nameEn: '2D Echocardiography with Color Doppler',
    nameBn: 'ইকোকার্ডিওগ্রাম (হার্টের আল্ট্রাসনোগ্রাম)',
    shortDescriptionBn: 'হার্টের পাম্পিং ক্ষমতা (EF %), ভালভ ও চেম্বারের গঠন পরীক্ষা।',
    category: 'HEART_LIPID',
    specimenType: 'IMAGING',
    fastingHours: 0,
    preparationRuleBn: 'কোনো প্রস্তুতির দরকার নেই।',
    prices: {
      POPULAR: 2500,
      IBN_SINA: 2200,
      LABAID: 3200,
      PRAAVA: 2800,
      THYROCARE: 2200,
      MEDINOVA: 2200,
      SQUARE: 5500,
      BIRDEM: 2000,
      BSMMU_GOVT: 800,
    },
    averagePrice: 2600,
  },

  // =========================================================================
  // 5. THYROID & HORMONES
  // =========================================================================
  {
    id: 'test_tsh',
    code: 'TSH',
    nameEn: 'Thyroid Stimulating Hormone (TSH)',
    nameBn: 'টিএসএইচ (থাইরয়েড হরমোন স্ক্রিনিং)',
    shortDescriptionBn: 'হাইপোথাইরয়েড বা হাইপারথাইরয়েড সমস্যা ও ওজন বৃদ্ধির কারণ নির্ণয়।',
    category: 'THYROID_HORMONE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'সকালে থাইরয়েডের ওষুধ (যেমন Thyrox) খাওয়ার পূর্বেই রক্ত দেওয়া সবচেয়ে ভালো।',
    prices: {
      POPULAR: 800,
      IBN_SINA: 700,
      LABAID: 950,
      PRAAVA: 750,
      THYROCARE: 550,
      MEDINOVA: 700,
      SQUARE: 1500,
      BIRDEM: 600,
      BSMMU_GOVT: 300,
    },
    averagePrice: 780,
  },
  {
    id: 'test_vit_d',
    code: 'VIT_D3',
    nameEn: 'Vitamin D (25-Hydroxy Vitamin D)',
    nameBn: 'ভিটামিন ডি (হাড় ও রোগ প্রতিরোধ ক্ষমতা)',
    shortDescriptionBn: 'শরীরের হাড় ক্ষয়, জয়েন্টে ব্যথা ও ইমিউনিটি ঘাটতি নির্ণয়।',
    category: 'THYROID_HORMONE',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'খালি পেটে থাকার প্রয়োজন নেই।',
    prices: {
      POPULAR: 3000,
      IBN_SINA: 2800,
      LABAID: 3500,
      PRAAVA: 2800,
      THYROCARE: 2200,
      MEDINOVA: 2600,
      SQUARE: 4500,
      BIRDEM: 2500,
      BSMMU_GOVT: 1200,
    },
    averagePrice: 2900,
  },
  {
    id: 'test_vit_b12',
    code: 'VIT_B12',
    nameEn: 'Vitamin B12 (Cyanocobalamin)',
    nameBn: 'ভিটামিন বি১২ (নার্ভ ও রক্তস্বল্পতা)',
    shortDescriptionBn: 'হাত-পা ঝিমঝিম করা, অবশ লাগা ও স্মৃতিশক্তি কমে যাওয়ার কারণ অনুসন্ধান।',
    category: 'THYROID_HORMONE',
    specimenType: 'BLOOD',
    fastingHours: 6,
    preparationRuleBn: '৬ ঘণ্টা না খেয়ে রক্ত দেওয়া ভালো।',
    prices: {
      POPULAR: 2200,
      IBN_SINA: 2000,
      LABAID: 2600,
      PRAAVA: 2200,
      THYROCARE: 1600,
      MEDINOVA: 1900,
      SQUARE: 3500,
      BIRDEM: 1800,
      BSMMU_GOVT: 800,
    },
    averagePrice: 2200,
  },

  // =========================================================================
  // 6. IMAGING & ULTRASOUND
  // =========================================================================
  {
    id: 'test_usg_whole_abd',
    code: 'USG_ABD',
    nameEn: 'USG of Whole Abdomen with PVR',
    nameBn: 'হোল এবডোমেন আল্ট্রাসনোগ্রাম (সম্পূর্ণ পেট স্ক্যান)',
    shortDescriptionBn: 'লিভার (ফ্যাটি লিভার), পিত্তথলির পাথর, কিডনি ও মূত্রথলির সমস্যা দেখা।',
    category: 'IMAGING_ULTRASOUND',
    specimenType: 'IMAGING',
    fastingHours: 6,
    preparationRuleBn: '🥣 ৬ ঘণ্টা না খেয়ে যেতে হবে এবং প্রচুর পানি পান করে প্রস্রাবের পর্যাপ্ত চাপ রাখতে হবে।',
    prices: {
      POPULAR: 2000,
      IBN_SINA: 1800,
      LABAID: 2500,
      PRAAVA: 2200,
      THYROCARE: 1800,
      MEDINOVA: 1800,
      SQUARE: 4000,
      BIRDEM: 1600,
      BSMMU_GOVT: 600,
    },
    averagePrice: 2100,
  },
  {
    id: 'test_xray_chest',
    code: 'XRAY_CHEST',
    nameEn: 'Chest X-Ray (P/A View Digital)',
    nameBn: 'বুকের ডিজিটাল এক্স-রে (ফুসফুস ও হার্ট)',
    shortDescriptionBn: 'ফুসফুসে নিউমোনিয়া, কফ জমা ও হার্টের আকার পরীক্ষা।',
    category: 'IMAGING_ULTRASOUND',
    specimenType: 'IMAGING',
    fastingHours: 0,
    preparationRuleBn: 'ধাতব গয়না বা বোতাম ছাড়া সুতির পোশাক পরা ভালো। গর্ভবতীদের এক্স-রে নিষেধ।',
    prices: {
      POPULAR: 750,
      IBN_SINA: 650,
      LABAID: 900,
      PRAAVA: 800,
      THYROCARE: 650,
      MEDINOVA: 700,
      SQUARE: 1600,
      BIRDEM: 550,
      BSMMU_GOVT: 250,
    },
    averagePrice: 780,
  },

  // =========================================================================
  // 7. URINE & STOOL
  // =========================================================================
  {
    id: 'test_urine_re',
    code: 'URINE_RE',
    nameEn: 'Urine R/M/E (Routine & Microscopic)',
    nameBn: 'ইউরিন আর/ই (প্রস্রাবের রুটিন পরীক্ষা)',
    shortDescriptionBn: 'প্রস্রাবে ইনফেকশন (Pus cells), সুগার, প্রোটিন বা অ্যালবুমিন লিকেজ দেখা।',
    category: 'URINE_STOOL',
    specimenType: 'URINE',
    fastingHours: 0,
    preparationRuleBn: 'সকালের প্রথম প্রস্রাবের মাঝের অংশ (Mid-stream urine) সংগ্রহ করা সবচেয়ে ভালো।',
    prices: {
      POPULAR: 300,
      IBN_SINA: 250,
      LABAID: 350,
      PRAAVA: 280,
      THYROCARE: 200,
      MEDINOVA: 250,
      SQUARE: 600,
      BIRDEM: 200,
      BSMMU_GOVT: 100,
    },
    averagePrice: 280,
  },
  {
    id: 'test_electrolytes',
    code: 'S_ELECTROLYTES',
    nameEn: 'Serum Electrolytes (Na+, K+, Cl-, HCO3-)',
    nameBn: 'সিরাম ইলেক্ট্রোলাইটস (লবণ ও পটাশিয়ামের মাত্রা)',
    shortDescriptionBn: 'শরীরে পানিশূন্যতা, দুর্বলতা ও লবণ-পটাশিয়ামের ভারসাম্য পরিমাপ।',
    category: 'KIDNEY_LIVER',
    specimenType: 'BLOOD',
    fastingHours: 0,
    preparationRuleBn: 'খালি পেটে থাকার দরকার নেই।',
    prices: {
      POPULAR: 1100,
      IBN_SINA: 1000,
      LABAID: 1300,
      PRAAVA: 1100,
      THYROCARE: 850,
      MEDINOVA: 1000,
      SQUARE: 2000,
      BIRDEM: 800,
      BSMMU_GOVT: 400,
    },
    averagePrice: 1100,
  },
];
