import {
  EpdsQuestion,
  KramerJaundiceZone,
  PostpartumDietItem,
} from '@/types/postpartum-newborn-shield';

export const KRAMER_JAUNDICE_ZONES: KramerJaundiceZone[] = [
  {
    zoneNumber: 1,
    bodyAreaBn: 'মাথা ও চোখ (Head & Neck)',
    bodyAreaEn: 'Head and Neck',
    estimatedBilirubinMgDl: '৪ – ৬ mg/dL',
    severity: 'MILD_PHYSIOLOGICAL',
    severityLabelBn: '🟢 মৃদু স্বাভাবিক (Physiological)',
    severityColor: '#10B981',
    clinicalExplanationBn: 'নবজাতকের যকৃৎ এখনও পুরোপুরি পরিপক্ব না হওয়ায় প্রসবের ২-৩ দিনের মধ্যে এটি হওয়া অত্যন্ত স্বাভাবিক।',
    actionAdviceBn: 'বাচ্চাকে দিনে ৮-১২ বার ঘন ঘন বুকের দুধ খাওয়ান এবং সকালের মিষ্টি রোদে (১০-১৫ মিনিট) চোখ ঢেকে রাখুন।',
    isEmergencyRedFlag: false,
  },
  {
    zoneNumber: 2,
    bodyAreaBn: 'বুক ও ওপরের পেট (Upper Trunk to Umbilicus)',
    bodyAreaEn: 'Upper Trunk to Umbilicus',
    estimatedBilirubinMgDl: '৬ – ৮ mg/dL',
    severity: 'MILD_PHYSIOLOGICAL',
    severityLabelBn: '🟢 সহনশীল মাত্রা (Mild Jaundice)',
    severityColor: '#10B981',
    clinicalExplanationBn: 'বিলিরুবিনের মাত্রা সামান্য বেড়েছে তবে এখনও নিরাপদ সীমার মধ্যে আছে।',
    actionAdviceBn: 'বুকের দুধ খাওয়ানোর হার বাড়ান। পর্যাপ্ত দুধ খেলে মল ও প্রস্রাবের মাধ্যমে বাড়তি বিলিরুবিন বের হয়ে যায়।',
    isEmergencyRedFlag: false,
  },
  {
    zoneNumber: 3,
    bodyAreaBn: 'তলপেট ও ঊরু থেকে হাঁটু পর্যন্ত (Lower Trunk to Knees)',
    bodyAreaEn: 'Lower Trunk to Knees',
    estimatedBilirubinMgDl: '৮ – ১২ mg/dL',
    severity: 'MODERATE',
    severityLabelBn: '🟡 মাঝারি পর্যবেক্ষণ (Moderate)',
    severityColor: '#F59E0B',
    clinicalExplanationBn: 'জন্ডিস নাভি পেরিয়ে হাঁটুর দিকে নামছে। এটি রক্তে বিলিরুবিন দ্রুত বৃদ্ধির লক্ষণ।',
    actionAdviceBn: 'শিশু বিশেষজ্ঞের (Pediatrician) পরামর্শ নিন এবং সিরাম বিলিরুবিন (Serum Bilirubin Total/Direct) টেস্ট করান।',
    isEmergencyRedFlag: false,
  },
  {
    zoneNumber: 4,
    bodyAreaBn: 'হাত ও পায়ের নিচের অংশ (Arms & Lower Legs)',
    bodyAreaEn: 'Arms and Lower Legs',
    estimatedBilirubinMgDl: '১২ – ১৫ mg/dL',
    severity: 'SIGNIFICANT',
    severityLabelBn: '🟠 উচ্চ মাত্রা (Significant Jaundice)',
    severityColor: '#F97316',
    clinicalExplanationBn: 'বিলিরুবিন বিপজ্জনক সীমার কাছাকাছি। মস্তিষ্কে প্রবেশের ঝুঁকি তৈরি হতে পারে।',
    actionAdviceBn: 'অবিলম্বে হাসপাতালে নিন। হাসপাতালে ব্লু-লাইট ফটোথেরাপি (Phototherapy) শুরু করতে হতে পারে।',
    isEmergencyRedFlag: false,
  },
  {
    zoneNumber: 5,
    bodyAreaBn: 'হাতের তালু ও পায়ের তলা (Palms & Soles)',
    bodyAreaEn: 'Palms and Soles',
    estimatedBilirubinMgDl: '> ১৫ mg/dL',
    severity: 'CRITICAL_DANGER',
    severityLabelBn: '🚨 চরম বিপদ সংকেত (Kernicterus Risk)',
    severityColor: '#EF4444',
    clinicalExplanationBn: 'চরম বিপজ্জনক মাত্রা! বিলিরুবিন রক্ত-মস্তিষ্ক প্রাচীর ভেদ করে নবজাতকের মস্তিষ্কের স্থায়ী ক্ষতি (Kernicterus) করতে পারে।',
    actionAdviceBn: 'কোনো মুহূর্ত দেরি না করে নিকটস্থ স্পেশালাইজড নিওনেটাল আইসিইউ (NICU) হাসপাতালে ভর্তি করান।',
    isEmergencyRedFlag: true,
  },
];

export const POSTPARTUM_DIET_CATALOG: PostpartumDietItem[] = [
  {
    id: 'post_1',
    category: 'GALACTAGOGUE_MILK',
    categoryLabelBn: '🥛 বুকের দুধ বৃদ্ধিকারক',
    nameBn: 'রসুন ও কালিজিরা ভর্তা',
    scientificBenefitBn: 'কালিজিরার থাইমোকুইনোন ও ফ্যাটি এসিড প্রোল্যাকটিন হরমোন উদ্দীপিত করে বুকের দুধের উৎপাদন দ্বিগুণ করে।',
    howToPrepareBn: 'হালকা ভাজা কালিজিরা সামান্য রসুনের কোয়া দিয়ে বেটে প্রতিদিন ভাতের সাথে খান।',
  },
  {
    id: 'post_2',
    category: 'GALACTAGOGUE_MILK',
    categoryLabelBn: '🥛 বুকের দুধ বৃদ্ধিকারক',
    nameBn: 'কাঁচা পেঁপে ও লাউয়ের পাতলা ঝোল',
    scientificBenefitBn: 'প্রচুর এনজাইম, পানি ও খনিজ থাকে যা মায়ের ডিহাইড্রেশন দূর করে তরল দুধের প্রবাহ সচল রাখে।',
    howToPrepareBn: 'শিং বা মাগুর মাছ দিয়ে কাঁচা পেঁপে ও লাউয়ের হালকা ঝোল রান্না করে দুপুরের খাবারে রাখুন।',
  },
  {
    id: 'post_3',
    category: 'WOUND_HEALING',
    categoryLabelBn: '🩹 সিজার/নরমাল ক্ষত নিরাময়',
    nameBn: 'শিং ও জিয়ল মাছের ঝোল',
    scientificBenefitBn: 'সহজলভ্য উচ্চ প্রোটিন ও জৈব আয়রন রক্তস্বল্পতা পূরণ করে এবং সিজারিয়ান সেলাই দ্রুত শুকায়।',
    howToPrepareBn: 'অতিরিক্ত তেল-মসলা ছাড়া আদা-জিরা দিয়ে হালকা ঝোল রান্না করুন।',
  },
  {
    id: 'post_4',
    category: 'WOUND_HEALING',
    categoryLabelBn: '🩹 সিজার/নরমাল ক্ষত নিরাময়',
    nameBn: 'ডিম ও দুগ্ধজাত খাবার',
    scientificBenefitBn: 'টিস্যু পুনর্গঠনে অ্যালবামিন ও ক্যালসিয়াম সরবরাহ করে। প্রসবের পর মা ও শিশুর হাড় মজবুত রাখে।',
    howToPrepareBn: 'প্রতিদিন অন্তত ১টি সিদ্ধ ডিম এবং ১ গ্লাস হালকা গরম দুধ পান করুন।',
  },
  {
    id: 'post_5',
    category: 'FLUID_HYDRATION',
    categoryLabelBn: '💧 পর্যাপ্ত তরল ও ইলেক্ট্রোলাইট',
    nameBn: 'জিরা পানি ও তাজা স্যুপ',
    scientificBenefitBn: 'মায়ের পরিপাকতন্ত্রের গ্যাস কমায় এবং ল্যাকটেশনের জন্য প্রয়োজনীয় অতিরিক্ত তরল চাহিদা পূরণ করে।',
    howToPrepareBn: 'পানিতে জিরা ফুটিয়ে কুসুম গরম অবস্থায় দিনে ২-৩ বার পান করুন।',
  },
];

export const EPDS_QUESTIONS_LIST: EpdsQuestion[] = [
  {
    id: 'epds_1',
    questionBn: 'গত ৭ দিনে আপনি কি মন খুলে হাসতে বা জীবনে আনন্দ অনুভব করতে পেরেছেন?',
    options: [
      { score: 0, textBn: 'সবসময়ের মতোই আনন্দের সাথে' },
      { score: 1, textBn: 'আগের চেয়ে কিছুটা কম' },
      { score: 2, textBn: 'খুব সামান্যই পেরেছি' },
      { score: 3, textBn: 'একদমই পারিনি' },
    ],
  },
  {
    id: 'epds_2',
    questionBn: 'গত ৭ দিনে কোনো কারণ ছাড়াই কি অতিরিক্ত দুশ্চিন্তা বা আতঙ্ক অনুভব করেছেন?',
    options: [
      { score: 0, textBn: 'একদমই না' },
      { score: 1, textBn: 'খুব কদাচিৎ' },
      { score: 2, textBn: 'মাঝে মাঝেই' },
      { score: 3, textBn: 'হ্যাঁ, প্রায় সারাক্ষণই' },
    ],
  },
  {
    id: 'epds_3',
    questionBn: 'বাচ্চার যত্ন নিতে গিয়ে কি নিজেকে অতিরিক্ত ক্লান্ত ও সবকিছু নিয়ন্ত্রণের বাইরে মনে হচ্ছে?',
    options: [
      { score: 0, textBn: 'না, সুন্দরভাবে সামলাতে পারছি' },
      { score: 1, textBn: 'মাঝে মাঝে একটু কঠিন লাগে' },
      { score: 2, textBn: 'বেশিরভাগ সময়ই অতিরিক্ত চাপ লাগে' },
      { score: 3, textBn: 'হ্যাঁ, একদমই একা সামলাতে পারছি না' },
    ],
  },
  {
    id: 'epds_4',
    questionBn: 'বাচ্চা ঘুমিয়ে থাকলেও কি মন খারাপ বা উদ্বেগের কারণে আপনার ঘুমাতে সমস্যা হচ্ছে?',
    options: [
      { score: 0, textBn: 'না, সুযোগ পেলেই শান্তিতে ঘুমাতে পারি' },
      { score: 1, textBn: 'কদাচিৎ ঘুম ভেঙে যায়' },
      { score: 2, textBn: 'মাঝে মাঝেই দুশ্চিন্তায় ঘুম আসে না' },
      { score: 3, textBn: 'হ্যাঁ, সারারাত নির্ঘুম ও অস্থির কাটে' },
    ],
  },
  {
    id: 'epds_5',
    questionBn: 'গত ৭ দিনে কি অকারণে মন খারাপ হয়ে কান্না পেয়েছে বা নিজেকে অসহায় মনে হয়েছে?',
    options: [
      { score: 0, textBn: 'একদমই না' },
      { score: 1, textBn: 'খুব কম' },
      { score: 2, textBn: 'মাঝে মাঝে কান্না পায়' },
      { score: 3, textBn: 'হ্যাঁ, প্রায় প্রতিদিন কান্নাকাটি করেছি' },
    ],
  },
];
