import {
  RamadanFoodItem,
  SixPointSugarCheckSlot,
} from '@/types/ramadan-fasting';

export const BANGLADESHI_RAMADAN_FOODS: RamadanFoodItem[] = [
  // --- IFTAR CORE & LOW/MED SPIKE ---
  {
    id: 'food_khejur_ajwa',
    nameEn: 'Date (Ajwa / Maryam)',
    nameBn: 'খেজুর (আজওয়া / মরিয়ম)',
    category: 'IFTAR_CORE',
    servingUnitBn: '১টি মাঝারি',
    defaultQuantity: 1,
    caloriesPerUnit: 23,
    carbsGrams: 6,
    proteinGrams: 0.2,
    fatGrams: 0.1,
    fiberGrams: 0.8,
    giValue: 42,
    spikeFactor: 'LOW',
    healthTipBn: 'দ্রুত প্রাকৃতিক শক্তি ও পটাশিয়াম যোগায়। ডায়াবেটিস রোগীরা ১-২টির বেশি খাবেন না।',
    safeLimitBn: 'সর্বোচ্চ ১ থেকে ২টি',
  },
  {
    id: 'food_chhola_seddho',
    nameEn: 'Boiled Chhola with Raw Ginger',
    nameBn: 'সেদ্ধ ছোলা ও কাঁচা আদা-শসা',
    category: 'IFTAR_CORE',
    servingUnitBn: '১ ছোট বাটি (১০০ গ্রাম)',
    defaultQuantity: 1,
    caloriesPerUnit: 140,
    carbsGrams: 22,
    proteinGrams: 8.5,
    fatGrams: 2.2,
    fiberGrams: 6.8,
    giValue: 28,
    spikeFactor: 'LOW',
    healthTipBn: 'উচ্চ আঁশ ও প্রোটিন থাকায় সুগার স্পাইক হতে দেয় না। অতিরিক্ত তেল ছাড়া তৈরি করুন।',
    safeLimitBn: '১ মাঝারি বাটি',
  },
  {
    id: 'food_halim_mutton',
    nameEn: 'Shahi Halim (Lentil & Meat Stew)',
    nameBn: 'হালিম (ডাল ও মাংসের মিশ্রণ)',
    category: 'IFTAR_CORE',
    servingUnitBn: '১ কাপ (১৫০ গ্রাম)',
    defaultQuantity: 1,
    caloriesPerUnit: 240,
    carbsGrams: 20,
    proteinGrams: 16,
    fatGrams: 10,
    fiberGrams: 4.5,
    giValue: 45,
    spikeFactor: 'MEDIUM',
    healthTipBn: 'প্রোটিন সমৃদ্ধ হলেও অতিরিক্ত তেল ও লবণ প্রেশার রোগীদের জন্য ঝুঁকিপূর্ণ।',
    safeLimitBn: '১ ছোট কাপ',
  },
  {
    id: 'food_tok_doi_borhani',
    nameEn: 'Low-Fat Tok Doi / Borhani',
    nameBn: 'টক দই / চিনি ছাড়া বোরহানি',
    category: 'IFTAR_CORE',
    servingUnitBn: '১ গ্লাস (২০০ মিলি)',
    defaultQuantity: 1,
    caloriesPerUnit: 90,
    carbsGrams: 6,
    proteinGrams: 7,
    fatGrams: 3,
    fiberGrams: 0.5,
    giValue: 25,
    spikeFactor: 'LOW',
    healthTipBn: 'প্রোবায়োটিক হজমে সাহায্য করে এবং অ্যাসিডিটি দূর করে।',
    safeLimitBn: '১ থেকে ২ গ্লাস',
  },

  // --- FRIED SNACKS (HIGH SPIKE & OIL) ---
  {
    id: 'food_peyaju',
    nameEn: 'Peyaju (Lentil Fritter)',
    nameBn: 'পেঁয়াজু (ডালের ভাজা)',
    category: 'FRIED_SNACK',
    servingUnitBn: '১টি মাঝারি',
    defaultQuantity: 2,
    caloriesPerUnit: 75,
    carbsGrams: 8,
    proteinGrams: 2.5,
    fatGrams: 4.2,
    fiberGrams: 1.2,
    giValue: 58,
    spikeFactor: 'MEDIUM',
    healthTipBn: 'ডুবো তেলে ভাজা পেঁয়াজু রক্তনালীতে কোলেস্টেরল বাড়ায় ও বুকজ্বালা তৈরি করে।',
    safeLimitBn: 'সর্বোচ্চ ১টি (এয়ারফ্রাই হলে ভালো)',
  },
  {
    id: 'food_beguni',
    nameEn: 'Beguni (Eggplant Fritter)',
    nameBn: 'বেগুনি (বেসন ও বেগুন ভাজা)',
    category: 'FRIED_SNACK',
    servingUnitBn: '১টি মাঝারি',
    defaultQuantity: 1,
    caloriesPerUnit: 95,
    carbsGrams: 11,
    proteinGrams: 2,
    fatGrams: 5.5,
    fiberGrams: 1.5,
    giValue: 62,
    spikeFactor: 'HIGH',
    healthTipBn: 'বেগুন প্রচুর তেল শোষণ করে, যা ফ্যাটি লিভার ও বদহজমের কারণ।',
    safeLimitBn: 'সর্বোচ্চ ১টি বা পরিহারযোগ্য',
  },
  {
    id: 'food_alur_chop',
    nameEn: 'Alur Chop (Potato Cake)',
    nameBn: 'আলুর চপ',
    category: 'FRIED_SNACK',
    servingUnitBn: '১টি মাঝারি',
    defaultQuantity: 1,
    caloriesPerUnit: 110,
    carbsGrams: 16,
    proteinGrams: 2,
    fatGrams: 5,
    fiberGrams: 1.2,
    giValue: 74,
    spikeFactor: 'HIGH',
    healthTipBn: 'আলু এবং তেল একসাথে থাকায় দ্রুত রক্তে সুগার বৃদ্ধি করে।',
    safeLimitBn: 'অর্ধেক বা পরিহার করুন',
  },
  {
    id: 'food_jilapi',
    nameEn: 'Jilapi / Jalebi (Sugar Syrup Sweet)',
    nameBn: 'জিলাপি (চিনির সিরার মিষ্টি)',
    category: 'SWEET_DESSERT',
    servingUnitBn: '১ প্যাঁচ (৫০ গ্রাম)',
    defaultQuantity: 1,
    caloriesPerUnit: 190,
    carbsGrams: 36,
    proteinGrams: 1.5,
    fatGrams: 5,
    fiberGrams: 0.2,
    giValue: 88,
    spikeFactor: 'EXTREME',
    healthTipBn: 'চিনির ঘনত্ব অতি উচ্চ। ইফতারের ২০ মিনিটের মধ্যে রক্তে সুগার ১৮+ mmol/L এ তুলতে পারে!',
    safeLimitBn: 'ডায়াবেটিস রোগীদের জন্য সম্পূর্ণ বর্জনীয়',
  },

  // --- BEVERAGES & SHERBETS ---
  {
    id: 'food_isabgol_lemon',
    nameEn: 'Isabgol & Chia Lemon Water',
    nameBn: 'চিনি ছাড়া ইসুবগুল ও লেবুর পানি',
    category: 'BEVERAGE',
    servingUnitBn: '১ গ্লাস (২৫০ মিলি)',
    defaultQuantity: 1,
    caloriesPerUnit: 25,
    carbsGrams: 4,
    proteinGrams: 1,
    fatGrams: 0.5,
    fiberGrams: 3.5,
    giValue: 15,
    spikeFactor: 'LOW',
    healthTipBn: 'আদর্শ ইফতার পানীয়। এটি কোষ্ঠকাঠিন্য দূর করে এবং সুগার স্থিতিশীল রাখে।',
    safeLimitBn: '১ থেকে ২ গ্লাস',
  },
  {
    id: 'food_dab_er_pani',
    nameEn: 'Tender Coconut Water',
    nameBn: 'ডাবের পানি (প্রাকৃতিক ইলেক্ট্রোলাইট)',
    category: 'BEVERAGE',
    servingUnitBn: '১ গ্লাস (২০০ মিলি)',
    defaultQuantity: 1,
    caloriesPerUnit: 45,
    carbsGrams: 9,
    proteinGrams: 1.5,
    fatGrams: 0.2,
    fiberGrams: 1.0,
    giValue: 48,
    spikeFactor: 'LOW',
    healthTipBn: 'পটাশিয়াম ও ইলেক্ট্রোলাইটে ভরপুর। কিডনি রোগীদের ডাবের পানি চিকিৎসকের অনুমতি ছাড়া খাওয়া নিষেধ।',
    safeLimitBn: '১ গ্লাস (কিডনি রোগী ছাড়া)',
  },
  {
    id: 'food_rooh_afza_tang',
    nameEn: 'Commercial Sugar Syrup / Rooh Afza / Tang',
    nameBn: 'চিনির শরবত / রুহ আফজা / ট্যাং',
    category: 'BEVERAGE',
    servingUnitBn: '১ গ্লাস (২৫০ মিলি)',
    defaultQuantity: 1,
    caloriesPerUnit: 140,
    carbsGrams: 34,
    proteinGrams: 0,
    fatGrams: 0,
    fiberGrams: 0,
    giValue: 85,
    spikeFactor: 'EXTREME',
    healthTipBn: 'খালি পেটে দ্রুত চিনি শোষণ হয়ে তীব্র গ্লুকোজ স্পাইক ঘটায়।',
    safeLimitBn: 'সম্পূর্ণ পরিহারযোগ্য',
  },

  // --- SUHOOR COMPLEX CARBS & PROTEIN ---
  {
    id: 'food_lal_chaal_bhaat',
    nameEn: 'Brown Rice / Lal Chaal Bhaat',
    nameBn: 'লাল চালের ভাত',
    category: 'SUHOOR_CARB',
    servingUnitBn: '১ কাপ (১৫০ গ্রাম)',
    defaultQuantity: 1,
    caloriesPerUnit: 165,
    carbsGrams: 34,
    proteinGrams: 3.8,
    fatGrams: 1.2,
    fiberGrams: 3.2,
    giValue: 50,
    spikeFactor: 'LOW',
    healthTipBn: 'ধীরগতির শর্করা (Complex Carb)। সারাদিন ধীরে ধীরে শক্তি যোগায় ও ক্ষুধা কমায়।',
    safeLimitBn: '১ থেকে ১.৫ কাপ',
  },
  {
    id: 'food_oats_khichuri',
    nameEn: 'Oats & Vegetable Khichuri',
    nameBn: 'ওটস ও সবজি খিচুড়ি',
    category: 'SUHOOR_CARB',
    servingUnitBn: '১ বাটি (২০০ গ্রাম)',
    defaultQuantity: 1,
    caloriesPerUnit: 180,
    carbsGrams: 28,
    proteinGrams: 6.5,
    fatGrams: 3.5,
    fiberGrams: 5.2,
    giValue: 48,
    spikeFactor: 'LOW',
    healthTipBn: 'বিটা-গ্লুকান আঁশ রক্তের কোলেস্টেরল কমায় ও ১৪ ঘণ্টা তৃষ্ণা নিয়ন্ত্রণে সাহায্য করে।',
    safeLimitBn: '১ বড় বাটি',
  },
  {
    id: 'food_deshi_fish_jhol',
    nameEn: 'Deshi Rui Fish Curry with Lau',
    nameBn: 'লাউ দিয়ে রুই/কাতল মাছের পাতলা ঝোল',
    category: 'SUHOOR_PROTEIN',
    servingUnitBn: '১ টুকরা মাছ + ঝোল',
    defaultQuantity: 1,
    caloriesPerUnit: 140,
    carbsGrams: 3,
    proteinGrams: 18,
    fatGrams: 6,
    fiberGrams: 2,
    giValue: 15,
    spikeFactor: 'LOW',
    healthTipBn: 'লাউয়ে ৯৫% পানি থাকে, যা সেহরির পর সারাদিন শরীরের পানিশূন্যতা রোধ করে।',
    safeLimitBn: '১-২ টুকরা মাছ ও প্রচুর ঝোল',
  },
  {
    id: 'food_egg_white_dim',
    nameEn: 'Boiled Egg (White / Whole)',
    nameBn: 'সেদ্ধ ডিম',
    category: 'SUHOOR_PROTEIN',
    servingUnitBn: '১টি সম্পূর্ণ ডিম',
    defaultQuantity: 1,
    caloriesPerUnit: 72,
    carbsGrams: 0.5,
    proteinGrams: 6.3,
    fatGrams: 4.8,
    fiberGrams: 0,
    giValue: 0,
    spikeFactor: 'LOW',
    healthTipBn: 'উচ্চমানের প্রোটিন ক্ষুধা কম রাখে ও পেশী সুরক্ষা করে।',
    safeLimitBn: '১ থেকে ২টি',
  },
];

export const SIX_POINT_SUGAR_CHECK_SLOTS: SixPointSugarCheckSlot[] = [
  {
    id: 'slot_pre_suhoor',
    slotNameEn: 'Pre-Suhoor (Fasting Baseline)',
    slotNameBn: '১. সেহরির ঠিক আগে (ভোর ৩:৩০ - ৪:০০)',
    timeWindowBn: 'সেহরি খাওয়ার আগে',
    targetRangeBn: '৫.০ - ৭.০ mmol/L',
    criticalThresholdMin: 3.9,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'সেহরির আগে ব্লাড সুগার কম থাকলে সারাদিন হাইপো হওয়ার ঝুঁকি বেড়ে যায়।',
  },
  {
    id: 'slot_post_suhoor',
    slotNameEn: '2-Hours Post-Suhoor',
    slotNameBn: '২. সেহরির ২ ঘণ্টা পর (সকাল ৭:০০)',
    timeWindowBn: 'সেহরি শেষ করার ২ ঘণ্টা পর',
    targetRangeBn: '৭.০ - ১০.০ mmol/L',
    criticalThresholdMin: 4.5,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'সেহরির খাবারে অতিরিক্ত কার্বোহাইড্রেট নেওয়া হয়েছে কি না তা যাচাই করা যায়।',
  },
  {
    id: 'slot_midday',
    slotNameEn: 'Mid-Day (Crucial Hypo Check)',
    slotNameBn: '৩. দুপুর ১২:০০ - ১:০০ (হাইপো চেকিং)',
    timeWindowBn: 'দুপুর ১২টা থেকে ১টার মধ্যে',
    targetRangeBn: '৫.৫ - ৮.০ mmol/L',
    criticalThresholdMin: 3.9,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'সবচেয়ে ঝুঁকিপূর্ণ সময়! সুগার < ৩.৯ mmol/L হলে কোনোভাবেই রোজা রাখা যাবে না, সাথে সাথে ভাঙতে হবে।',
  },
  {
    id: 'slot_pre_iftar',
    slotNameEn: 'Pre-Iftar (Late Afternoon)',
    slotNameBn: '৪. ইফতারের ঠিক আগে (বিকাল ৫:৩০ - ৬:০০)',
    timeWindowBn: 'ইফতারের আধা ঘণ্টা আগে',
    targetRangeBn: '৪.৫ - ৭.০ mmol/L',
    criticalThresholdMin: 3.9,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'দিনের সর্বনিম্ন সুগার পয়েন্ট। < ৩.৯ mmol/L হলে অবিলম্বে দ্রুত চিনি বা খেজুর খেতে হবে।',
  },
  {
    id: 'slot_post_iftar',
    slotNameEn: '2-Hours Post-Iftar (Spike Check)',
    slotNameBn: '৫. ইফতারের ২ ঘণ্টা পর (রাত ৮:৩০)',
    timeWindowBn: 'ইফতার শেষ করার ২ ঘণ্টা পর',
    targetRangeBn: '৭.০ - ১০.০ mmol/L',
    criticalThresholdMin: 4.0,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'ইফতারের ভাজাপোড়া, শরবত ও ফলের কারণে বিপজ্জনক সুগার স্পাইক (> ১১ mmol/L) হলো কি না বোঝা যায়।',
  },
  {
    id: 'slot_bedtime',
    slotNameEn: 'Bedtime / Post-Tarawih',
    slotNameBn: '৬. ঘুমানোর আগে / তারাবীহর পর (রাত ১১:০০)',
    timeWindowBn: 'রাতে ঘুমানোর আগে',
    targetRangeBn: '৬.০ - ৮.৫ mmol/L',
    criticalThresholdMin: 4.5,
    criticalThresholdMax: 16.7,
    whyImportantBn: 'রাতের ঘুমের মধ্যে নিশাচর হাইপোগ্লাইসেমিয়া (Nocturnal Hypoglycemia) প্রতিরোধ করে।',
  },
];

export const RAMADAN_DRUG_CLASS_RULES = [
  {
    classKey: 'METFORMIN',
    keywords: ['metformin', 'glucophage', 'comet', 'glysup', 'metfo'],
    adviceBn: 'সকালের ডোজ সরাসরি ইফতারে নেবেন। রাতের ডোজ সেহরিতে নেবেন। কোনো ডোজ কমানোর প্রয়োজন নেই।',
    warningLevel: 'INFO' as const,
    precautionBn: 'মেটফরমিনে হাইপোগ্লাইসেমিয়ার ঝুঁকি কম। ইফতারের ভারী খাবারের সময় নেওয়াই সর্বোত্তম।',
  },
  {
    classKey: 'SULFONYLUREA',
    keywords: ['gliclazide', 'glimepiride', 'amaryl', 'secrin', 'diamicron', 'glipizide'],
    adviceBn: 'সকালের সম্পূর্ণ ডোজ ইফতারের শুরুতে নেবেন। সেহরির ডোজ সাধারণত অর্ধেক (৫০%) করতে হবে বা চিকিৎসকের পরামর্শে বন্ধ রাখতে হবে।',
    warningLevel: 'CRITICAL_DOCTOR_ALERT' as const,
    precautionBn: 'দুপুরে মারাত্মক হাইপো হতে পারে! সেহরিতে অতিরিক্ত ডোজ নেওয়া সম্পূর্ণ নিষেধ।',
  },
  {
    classKey: 'DPP4',
    keywords: ['sitagliptin', 'vildagliptin', 'linagliptin', 'januvia', 'galvus', 'trajenta'],
    adviceBn: 'দৈনিক ১টি ট্যাবলেট ইফতারের সময় গ্রহণ করুন। কোনো ডোজ পরিবর্তনের প্রয়োজন নেই।',
    warningLevel: 'INFO' as const,
    precautionBn: 'রমজানে ডায়াবেটিস রোগীদের জন্য অত্যন্ত নিরাপদ ও কার্যকর ওষুধ।',
  },
  {
    classKey: 'SGLT2',
    keywords: ['empagliflozin', 'dapagliflozin', 'jardiance', 'forxiga', 'synjardy'],
    adviceBn: 'অবশ্যই ইফতারে গ্রহণ করবেন (কখনোই সেহরিতে নয়)। ইফতার থেকে সেহরি পর্যন্ত পর্যাপ্ত পানি পান করুন।',
    warningLevel: 'CAUTION' as const,
    precautionBn: 'সেহরিতে নিলে দিনের বেলা অতিরিক্ত প্রস্রাবের কারণে পানিশূন্যতা ও রক্তচাপ কমে মাথা ঘোরার ঝুঁকি থাকে।',
  },
  {
    classKey: 'INSULIN_PREMIX',
    keywords: ['mixtard', 'novomix', 'humalog mix', 'gensulin'],
    adviceBn: 'সকালের ডোজ ইফতারে পূর্ণ মাত্রায় নিন। রাতের ডোজ সেহরিতে সাধারণত ২৫% থেকে ৫০% কমিয়ে নিতে হবে।',
    warningLevel: 'CRITICAL_DOCTOR_ALERT' as const,
    precautionBn: 'সেহরির ইনসুলিন না কমালে বেলা ১২টা থেকে বিকাল ৪টার মধ্যে প্রাণঘাতী হাইপোগ্লাইসেমিয়া হতে পারে।',
  },
  {
    classKey: 'INSULIN_BASAL',
    keywords: ['lantus', 'glargine', 'tresiba', 'degludec', 'toujeo'],
    adviceBn: 'প্রতিদিন ইফতারের পর বা রাতে একই সময়ে নিন; ডোজ চিকিৎসকের পরামর্শ অনুযায়ী ১৫-২০% কমানো হতে পারে।',
    warningLevel: 'CAUTION' as const,
    precautionBn: 'স্থির মাত্রায় সুগার নিয়ন্ত্রণে রাখে, তবে দিনে হাইপো হলে দ্রুত চিকিৎসককে জানান।',
  },
  {
    classKey: 'ANTIHYPERTENSIVE',
    keywords: ['amlodipine', 'telmisartan', 'losartan', 'bisoprolol', 'olmesartan', 'camlosart'],
    adviceBn: 'সকালের প্রেশারের ওষুধ ইফতারের ১ ঘণ্টা পর বা রাতে ঘুমানোর আগে গ্রহণ করুন।',
    warningLevel: 'INFO' as const,
    precautionBn: 'দিনের বেলা প্রেশার অতিরিক্ত কমে মাথা ঘোরা ও ব্ল্যাকআউট প্রতিরোধ করতে রাতে নেওয়া উত্তম।',
  },
];
