import {
  GoutFirstAidStep,
  PurineFoodItem,
  UricAcidStageDef,
} from '@/types/uric-acid-gout-shield';

export const URIC_ACID_STAGES: UricAcidStageDef[] = [
  {
    stage: 'OPTIMAL',
    labelBn: '🟢 নিরাপদ ও স্বাভাবিক (Normal Range)',
    color: '#10B981',
    thresholdMale: '< ৬.০ mg/dL',
    thresholdFemale: '< ৫.০ mg/dL',
    descriptionBn: 'রক্তে ইউরিক এসিডের মাত্রা সম্পূর্ণ নিরাপদ। বাতব্যথা বা কিডনিতে ইউরেট পাথর জমার কোনো ঝুঁকি নেই।',
    clinicalAdviceBn: 'চমৎকার! বর্তমান সুষম খাবার ও পর্যাপ্ত পানি পানের অভ্যাস বজায় রাখুন।',
  },
  {
    stage: 'BORDERLINE',
    labelBn: '🟡 বর্ডারলাইন (Borderline Elevated)',
    color: '#F59E0B',
    thresholdMale: '৬.০ – ৬.৯ mg/dL',
    thresholdFemale: '৫.০ – ৫.৯ mg/dL',
    descriptionBn: 'ইউরিক এসিড স্বাভাবিকের সর্বোচ্চ সীমায় পৌঁছেছে। এখনই পিউরিনযুক্ত খাবার নিয়ন্ত্রণ না করলে ভবিষ্যতে গাউট হতে পারে।',
    clinicalAdviceBn: 'খাসির মাংস, চিংড়ি ও ঘন ডাল খাওয়া কমান। প্রতিদিন পর্যাপ্ত পানি ও লেবুর শরবত পান করুন।',
  },
  {
    stage: 'HYPERURICEMIA',
    labelBn: '🟠 উচ্চ ইউরিক এসিড (Hyperuricemia)',
    color: '#F97316',
    thresholdMale: '৭.০ – ৮.৫ mg/dL',
    thresholdFemale: '৬.০ – ৭.৫ mg/dL',
    descriptionBn: 'রক্তে অতিরিক্ত ইউরিক এসিড জমা হচ্ছে। পায়ের বুড়ো আঙুল, গোড়ালি বা হাঁটুতে ক্রিস্টাল জমে তীব্র প্রদাহ সৃষ্টি হতে পারে।',
    clinicalAdviceBn: 'উচ্চ-পিউরিন খাবার সম্পূর্ণ বর্জন করুন। চিকিৎসকের পরামর্শে ইউরিক এসিড কমানোর ওষুধ বিবেচনা করুন।',
  },
  {
    stage: 'SEVERE_GOUT_RISK',
    labelBn: '🔴 মারাত্মক ঝুঁকি ও তীব্র গাউট (Severe Gout Flare Risk)',
    color: '#EF4444',
    thresholdMale: '> ৮.৫ mg/dL',
    thresholdFemale: '> ৭.৫ mg/dL',
    descriptionBn: 'চরম বিপজ্জনক মাত্রা। জয়েন্টে ইউরেট টোফাই (Tophaceous Gout) এবং স্থায়ী জয়েন্ট বিকৃতির উচ্চ ঝুঁকি।',
    clinicalAdviceBn: 'অবিলম্বে বাতব্যথা বিশেষজ্ঞ (Rheumatologist) বা মেডিসিন বিশেষজ্ঞের পরামর্শ নিন এবং নিয়মমাফিক ওষুধ সেবন করুন।',
  },
];

export const PURINE_FOOD_CATALOG: PurineFoodItem[] = [
  // HIGH PURINE (AVOID)
  {
    id: 'pur_1',
    nameBn: 'খাসির মাংস ও গরুর কলিজা/মগজ',
    nameEn: 'Mutton & Organ Meats (Liver/Brain)',
    purineMgPer100g: 400,
    rating: 'HIGH_PURINE_AVOID',
    ratingLabelBn: '🚫 বর্জনীয় (উচ্চ পিউরিন)',
    ratingColor: '#EF4444',
    categoryBn: 'মাংস ও অর্গান',
    clinicalAdviceBn: 'ইউরিক এসিড বাড়ার প্রধান কারণ। গাউট আক্রান্তদের জন্য সম্পূর্ণ নিষিদ্ধ।',
  },
  {
    id: 'pur_2',
    nameBn: 'চিংড়ি মাছ, কাঁকড়া ও সামুদ্রিক মাছ',
    nameEn: 'Prawns, Crab & Marine Seafood',
    purineMgPer100g: 280,
    rating: 'HIGH_PURINE_AVOID',
    ratingLabelBn: '🚫 বর্জনীয় (উচ্চ পিউরিন)',
    ratingColor: '#EF4444',
    categoryBn: 'মাছ ও সি-ফুড',
    clinicalAdviceBn: 'চিংড়ি ও কাঁকড়ায় প্রচুর পিউরিন থাকে, যা খাওয়ার কয়েক ঘণ্টার মধ্যে জয়েন্টে তীব্র ব্যথা ট্রিগার করে।',
  },
  {
    id: 'pur_3',
    nameBn: 'ইলিশ মাছের ডিম ও মাছের মাথা',
    nameEn: 'Hilsa Fish Roe & Fish Head',
    purineMgPer100g: 350,
    rating: 'HIGH_PURINE_AVOID',
    ratingLabelBn: '🚫 বর্জনীয় (উচ্চ পিউরিন)',
    ratingColor: '#EF4444',
    categoryBn: 'মাছ ও সি-ফুড',
    clinicalAdviceBn: 'মাছের ডিম পিউরিনের ঘন উৎস। ইউরিক এসিড বেশি থাকলে খাওয়া বন্ধ রাখুন।',
  },
  {
    id: 'pur_4',
    nameBn: 'ঘন মসুর ডাল ও শুঁটকি মাছ',
    nameEn: 'Thick Lentil Dal & Dried Fish',
    purineMgPer100g: 220,
    rating: 'HIGH_PURINE_AVOID',
    ratingLabelBn: '🚫 বর্জনীয় (উচ্চ পিউরিন)',
    ratingColor: '#EF4444',
    categoryBn: 'ডাল ও শুঁটকি',
    clinicalAdviceBn: 'ঘন ডালের পরিবর্তে পাতলা ডাল সামান্য খেতে পারেন। শুঁটকি মাছ সম্পূর্ণ পরিহার করুন।',
  },
  {
    id: 'pur_5',
    nameBn: 'পুঁইশাক ও ফুলকপি',
    nameEn: 'Pui Shak & Cauliflower',
    purineMgPer100g: 160,
    rating: 'HIGH_PURINE_AVOID',
    ratingLabelBn: '🚫 বর্জনীয় (উচ্চ পিউরিন)',
    ratingColor: '#EF4444',
    categoryBn: 'শাকসবজি',
    clinicalAdviceBn: 'অন্যান্য শাকসবজি নিরাপদ হলেও পুঁইশাক ও ফুলকপিতে পিউরিন বেশি থাকায় পরিহার্য।',
  },

  // MODERATE PURINE (LIMIT)
  {
    id: 'pur_6',
    nameBn: 'মুরগির মাংস (চামড়া ছাড়া)',
    nameEn: 'Skinless Chicken',
    purineMgPer100g: 110,
    rating: 'MODERATE_PURINE_LIMIT',
    ratingLabelBn: '⚠️ সীমিত (পরিমিত খান)',
    ratingColor: '#F59E0B',
    categoryBn: 'মাংস ও পোল্ট্রি',
    clinicalAdviceBn: 'সপ্তাহে ২-৩ দিন পরিমিত পরিমাণে (১-২ টুকরা) খাওয়া নিরাপদ।',
  },
  {
    id: 'pur_7',
    nameBn: 'রুই, কাতলা ও সাধারণ নদীর মাছ',
    nameEn: 'Rui, Catla Freshwater Fish',
    purineMgPer100g: 90,
    rating: 'MODERATE_PURINE_LIMIT',
    ratingLabelBn: '⚠️ সীমিত (পরিমিত খান)',
    ratingColor: '#F59E0B',
    categoryBn: 'মাছ ও সি-ফুড',
    clinicalAdviceBn: 'তেল ছাড়া হালকা ঝোল করে ১ টুকরা মিষ্টি পানির মাছ খাওয়া যায়।',
  },
  {
    id: 'pur_8',
    nameBn: 'ছোলা ও বুটের ডাল',
    nameEn: 'Chickpeas & Chana Dal',
    purineMgPer100g: 105,
    rating: 'MODERATE_PURINE_LIMIT',
    ratingLabelBn: '⚠️ সীমিত (পরিমিত খান)',
    ratingColor: '#F59E0B',
    categoryBn: 'ডাল ও শুঁটকি',
    clinicalAdviceBn: 'বেশি খাওয়া যাবে না। সামান্য পরিমাণে খাওয়া যেতে পারে।',
  },

  // LOW PURINE / THERAPEUTIC (SAFE & PROTECTIVE)
  {
    id: 'pur_9',
    nameBn: 'টক দই (প্রোবায়োটিক)',
    nameEn: 'Plain Sour Curd / Yogurt',
    purineMgPer100g: 15,
    rating: 'LOW_PURINE_SAFE',
    ratingLabelBn: '🟢 নিরাপদ ও উপকারী',
    ratingColor: '#10B981',
    categoryBn: 'দুগ্ধজাত খাবার',
    clinicalAdviceBn: 'টক দইয়ের প্রোটিন ও প্রোবায়োটিক শরীর থেকে অতিরিক্ত ইউরিক এসিড বের করে দিতে সাহায্য করে।',
  },
  {
    id: 'pur_10',
    nameBn: 'তাজা পাতিলেবুর শরবত',
    nameEn: 'Fresh Lemon Water',
    purineMgPer100g: 5,
    rating: 'LOW_PURINE_SAFE',
    ratingLabelBn: '🟢 নিরাপদ ও উপকারী',
    ratingColor: '#10B981',
    categoryBn: 'ফল ও পানীয়',
    clinicalAdviceBn: 'লেবুর ভিটামিন-সি ও সাইট্রিক এসিড রক্ত ও প্রস্রাব অ্যালকালাইন করে ইউরেট ক্রিস্টাল দ্রবীভূত করে।',
  },
  {
    id: 'pur_11',
    nameBn: 'শসা, লাউ ও কাঁচা পেঁপে',
    nameEn: 'Cucumber, Bottle Gourd & Papaya',
    purineMgPer100g: 12,
    rating: 'LOW_PURINE_SAFE',
    ratingLabelBn: '🟢 নিরাপদ ও উপকারী',
    ratingColor: '#10B981',
    categoryBn: 'শাকসবজি',
    clinicalAdviceBn: 'এগুলোতে প্রচুর পানি থাকে যা প্রস্রাবের প্রবাহ বাড়িয়ে ইউরিক এসিড ধুয়ে বের করে দেয়।',
  },
  {
    id: 'pur_12',
    nameBn: 'ডিমের সাদা অংশ (Egg White)',
    nameEn: 'Egg White (Pure Albumin)',
    purineMgPer100g: 5,
    rating: 'LOW_PURINE_SAFE',
    ratingLabelBn: '🟢 নিরাপদ ও উপকারী',
    ratingColor: '#10B981',
    categoryBn: 'মাংস ও অর্গান',
    clinicalAdviceBn: 'বাতের রোগীদের জন্য সবচেয়ে নিরাপদ ও পিউরিনমুক্ত প্রোটিনের উৎস।',
  },
];

export const GOUT_FIRST_AID_STEPS: GoutFirstAidStep[] = [
  {
    stepNumber: 1,
    titleBn: '🧊 আক্রান্ত জয়েন্টে বরফের সেঁক দিন (Ice Application)',
    actionBn: 'একটি কাপড়ে বরফ পেঁচিয়ে আক্রান্ত পায়ের বুড়ো আঙুল বা হাঁটুতে ১৫-২০ মিনিট আলতো করে চেপে ধরুন। দিনে ৩-৪ বার করুন।',
    cautionBn: 'সতর্কতা: ভুলেও গরম পানির সেঁক বা হট ওয়াটার ব্যাগ দেবেন না! গরমে রক্ত চলাচল বেড়ে প্রদাহ ও ব্যথা আরও তীব্র হবে।',
    icon: 'ac-unit',
  },
  {
    stepNumber: 2,
    titleBn: '🦶 আক্রান্ত পা বালিশের ওপর উঁচুতে রাখুন (Elevation)',
    actionBn: 'বিছানায় শুয়ে ১-২টি বালিশ দিয়ে আক্রান্ত পা হার্টের উচ্চতার ওপরে তুলে রাখুন। এতে রক্ত ও তরল জমাট বাঁধা কমে এবং ফোলাভাব দ্রুত হ্রাস পায়।',
    cautionBn: 'আক্রান্ত পায়ের ওপর ভর দিয়ে হাঁটাচলা সম্পূর্ণ পরিহার করুন।',
    icon: 'airline-seat-legroom-extra',
  },
  {
    stepNumber: 3,
    titleBn: '💧 ১ ঘণ্টায় ১ লিটার পানি পান করুন (Fluid Flush)',
    actionBn: 'তাৎক্ষণিকভাবে ২-৩ গ্লাস পানি ও ১টি পাতিলেবুর শরবত পান করুন। পর্যাপ্ত পানি কিডনির মাধ্যমে রক্তে জমা ইউরেট ক্রিস্টাল দ্রুত বের করে দেয়।',
    cautionBn: 'কোমল পানীয় (সফট ড্রিংকস), ফ্রুক্টোজ জুস বা মিষ্টি শরবত খাবেন না।',
    icon: 'local-drink',
  },
  {
    stepNumber: 4,
    titleBn: '🚫 অ্যাসপিরিন জাতীয় ব্যথানাশক বর্জন করুন (No Aspirin)',
    actionBn: 'ব্যথা কমাতে চিকিৎসকের প্রেসক্রিপশন অনুযায়ী নির্ধারিত ব্যথানাশক (NSAID/Colchicine) গ্রহণ করুন।',
    cautionBn: 'জরুরি সতর্কতা: কখনো নিজে থেকে অ্যাসপিরিন (Aspirin/Disprin) খাবেন না, কারণ এটি কিডনি দিয়ে ইউরিক এসিড নিঃসরণ বন্ধ করে দেয়।',
    icon: 'block',
  },
];
