import { KidneyStoneDietItem, UrineColorDef, UtiSymptom } from '@/types/urine-hydration-shield';

export const ARMSTRONG_URINE_SHADES: UrineColorDef[] = [
  {
    shade: 1,
    hexColor: '#FAFDE8',
    nameBn: '১. একদম স্বচ্ছ পানি (Crystal Clear)',
    nameEn: 'Pale Clear Water',
    category: 'OPTIMAL',
    categoryLabelBn: '🟢 চমৎকার / সামান্য বেশি পানি',
    categoryColor: '#10B981',
    descriptionBn: 'শরীর সম্পূর্ণ হাইড্রেটেড। তবে অতিরিক্ত পানি খেলে ইলেক্ট্রোলাইট লঘু হতে পারে।',
    clinicalAdviceBn: 'হাইড্রেশন লেভেল দারুণ। তৃষ্ণা না পেলে জোর করে অতিরিক্ত পানি খাওয়ার প্রয়োজন নেই।',
    immediateWaterDoseGlasses: 0,
  },
  {
    shade: 2,
    hexColor: '#F7FAB5',
    nameBn: '২. হালকা লেবুর রঙ (Pale Straw)',
    nameEn: 'Pale Straw Lemon',
    category: 'OPTIMAL',
    categoryLabelBn: '🟢 আদর্শ ও সর্বোত্তম সুস্থতা',
    categoryColor: '#10B981',
    descriptionBn: 'মানবদেহের জন্য সবচেয়ে আদর্শ প্রস্রাবের রঙ। কিডনি ও মূত্রনালী সম্পূর্ণ স্বাভাবিকভাবে কাজ করছে।',
    clinicalAdviceBn: 'চমৎকার! বর্তমান পানির অভ্যাস বজায় রাখুন।',
    immediateWaterDoseGlasses: 0,
  },
  {
    shade: 3,
    hexColor: '#F3E96B',
    nameBn: '৩. হালকা সোনালী হলুদ (Transparent Yellow)',
    nameEn: 'Transparent Yellow',
    category: 'GOOD',
    categoryLabelBn: '🟢 ভালো ও স্বাভাবিক',
    categoryColor: '#10B981',
    descriptionBn: 'স্বাভাবিক হাইড্রেশন। শরীর যথেষ্ট পরিমাণ পানি পাচ্ছে।',
    clinicalAdviceBn: 'স্বাভাবিক অবস্থা। আগামী কয়েক ঘণ্টার মধ্যে ১ গ্লাস পানি পান করুন।',
    immediateWaterDoseGlasses: 1,
  },
  {
    shade: 4,
    hexColor: '#ECCF35',
    nameBn: '৪. পরিষ্কার অ্যাম্বার হলুদ (Clear Amber)',
    nameEn: 'Clear Amber',
    category: 'GOOD',
    categoryLabelBn: '🟡 গ্রহণযোগ্য (সামান্য পানি প্রয়োজন)',
    categoryColor: '#F59E0B',
    descriptionBn: 'হাইড্রেশন লেভেল কিছুটা কমছে। শরীর পানি সঞ্চয় করার চেষ্টা করছে।',
    clinicalAdviceBn: 'এখনই ১-২ গ্লাস বিশুদ্ধ পানি পান করা ভালো।',
    immediateWaterDoseGlasses: 1,
  },
  {
    shade: 5,
    hexColor: '#D89E15',
    nameBn: '৫. গাঢ় সরিষার হলুদ (Dark Yellow)',
    nameEn: 'Dark Yellow',
    category: 'MILD_DEHYDRATION',
    categoryLabelBn: '🟠 মৃদু পানিশূন্যতা (Dehydrated)',
    categoryColor: '#F97316',
    descriptionBn: 'শরীরে পানিশূন্যতা শুরু হয়েছে। প্রস্রাবে ইউরিয়া ও লবণের ঘনত্ব বাড়ছে, যা কিডনির ওপর চাপ ফেলে।',
    clinicalAdviceBn: 'অবিলম্বে ২ গ্লাস (৫০০ মিলি) পানি পান করুন এবং চা/কফি পরিহার করুন।',
    immediateWaterDoseGlasses: 2,
  },
  {
    shade: 6,
    hexColor: '#B66E0C',
    nameBn: '৬. কড়া কমলা / অ্যাম্বার (Amber Orange)',
    nameEn: 'Amber Orange',
    category: 'SEVERE_DEHYDRATION',
    categoryLabelBn: '🔴 তীব্র পানিশূন্যতা (Severe Dehydration)',
    categoryColor: '#EF4444',
    descriptionBn: 'মারাত্মক পানিশূন্যতা। কিডনিতে ক্যালসিয়াম অক্সালেট ক্রিস্টাল ও পাথর জমার চরম ঝুঁকি।',
    clinicalAdviceBn: 'জরুরি ভিত্তিতে ৩ গ্লাস (৭৫০ মিলি) পানি বা ডাবের পানি পান করুন। রোদে থাকা পরিহার করুন।',
    immediateWaterDoseGlasses: 3,
  },
  {
    shade: 7,
    hexColor: '#7C3B0B',
    nameBn: '৭. লিকার চা বা বাদামী রঙ (Brownish Tea)',
    nameEn: 'Brownish Tea Color',
    category: 'CRITICAL_MEDICAL_ALERT',
    categoryLabelBn: '🚨 ক্রিটিক্যাল অ্যালার্ট (লিভার বা তীব্র ডিহাইড্রেশন)',
    categoryColor: '#DC2626',
    descriptionBn: 'মারাত্মক ডিহাইড্রেশন অথবা যকৃতের পিত্তরস (Bilirubin) প্রস্রাবে মিশে থাকতে পারে (জন্ডিসের লক্ষণ)।',
    clinicalAdviceBn: 'প্রচুর তরল পান করুন। পানি খাওয়ার পরও রঙ না বদলালে দ্রুত লিভার ফাংশন টেস্ট (Serum Bilirubin) ও ডাক্তার দেখান।',
    immediateWaterDoseGlasses: 3,
  },
  {
    shade: 8,
    hexColor: '#6B1616',
    nameBn: '৮. লালচে বা গাঢ় রক্তাভ (Reddish Cola / Blood)',
    nameEn: 'Reddish Cola Hematuria',
    category: 'CRITICAL_MEDICAL_ALERT',
    categoryLabelBn: '🚨 জরুরি রেড অ্যালার্ট (রক্তপাত / হেমাটুরিয়া)',
    categoryColor: '#991B1B',
    descriptionBn: 'প্রস্রাবে রক্ত (Hematuria), কিডনি ইনফেকশন, পাথর কেটে যাওয়া বা পেশী ভেঙে যাওয়ার (Rhabdomyolysis) লক্ষণ।',
    clinicalAdviceBn: 'কোনো বিলম্ব না করে অবিলম্বে নিকটস্থ হাসপাতালের জরুরি বিভাগ বা ইউরোলজিস্টের শরণাপন্ন হন।',
    immediateWaterDoseGlasses: 2,
  },
];

export const UTI_SYMPTOMS_LIST: UtiSymptom[] = [
  {
    id: 'uti_1',
    nameBn: 'প্রস্রাবে জ্বালাপোড়া বা ব্যথা (Dysuria)',
    descriptionBn: 'প্রস্রাব করার সময় মূত্রনালীতে তীব্র জ্বলন বা অস্বস্তি অনুভব হওয়া।',
    isSevereRedFlag: false,
    isSelected: false,
  },
  {
    id: 'uti_2',
    nameBn: 'ঘন ঘন অল্প অল্প প্রস্রাবের তীব্র বেগ (Urgency & Frequency)',
    descriptionBn: 'প্রস্রাবের তীব্র চাপ অনুভব করা কিন্তু ওয়াশরুমে গেলে সামান্য হওয়া।',
    isSevereRedFlag: false,
    isSelected: false,
  },
  {
    id: 'uti_3',
    nameBn: 'তলপেটে বা মূত্রথলিতে চাপ ও চিনচিন ব্যথা (Pelvic Pain)',
    descriptionBn: 'নাভির নিচে তলপেটের অংশে সার্বক্ষণিক ভারী ভাব বা চিনচিনে ব্যথা।',
    isSevereRedFlag: false,
    isSelected: false,
  },
  {
    id: 'uti_4',
    nameBn: 'প্রস্রাব অস্বাভাবিক ঘোলা বা কড়া দুর্গন্ধযুক্ত (Cloudy / Malodorous)',
    descriptionBn: 'প্রস্রাব স্বচ্ছ না হয়ে দুধের মতো ঘোলাটে বা তীব্র বাজে গন্ধ হওয়া।',
    isSevereRedFlag: false,
    isSelected: false,
  },
  {
    id: 'uti_5',
    nameBn: 'কাঁপুনি দিয়ে তীব্র জ্বর ও কোমরের একপাশে ব্যথা (Pyelonephritis Alert)',
    descriptionBn: 'ইনফেকশন মূত্রথলি পেরিয়ে কিডনিতে ছড়িয়ে পড়ার বিপজ্জনক সংকেত।',
    isSevereRedFlag: true,
    isSelected: false,
  },
  {
    id: 'uti_6',
    nameBn: 'প্রস্রাবের সাথে রক্তক্ষরণ বা লালচে ভাব (Hematuria)',
    descriptionBn: 'ইনফেকশনের কারণে মূত্রনালীর দেয়াল ক্ষতবিক্ষত হওয়ার লক্ষণ।',
    isSevereRedFlag: true,
    isSelected: false,
  },
];

export const KIDNEY_STONE_DIET_CATALOG: KidneyStoneDietItem[] = [
  {
    id: 'stone_1',
    category: 'CITRATE_PROTECTIVE',
    categoryLabelBn: '🍋 সাইট্রেট সুরক্ষা (পাথর গলক)',
    nameBn: 'তাজা পাতিলেবুর রস ও শরবত',
    actionBn: 'প্রতিদিন পানিতে ১টি তাজা লেবুর রস মিশিয়ে পান করুন',
    scientificReasonBn: 'লেবুর প্রাকৃতিক সাইট্রেট (Citrate) প্রস্রাবের ক্যালসিয়ামের সাথে মিশে ক্যালসিয়াম অক্সালেট ক্রিস্টাল জমাট বাঁধতে দেয় না।',
  },
  {
    id: 'stone_2',
    category: 'CITRATE_PROTECTIVE',
    categoryLabelBn: '🍋 সাইট্রেট সুরক্ষা (পাথর গলক)',
    nameBn: 'কচি ডাবের পানি',
    actionBn: 'গরমে সপ্তাহে ২-৩ দিন কচি ডাবের পানি পান করুন',
    scientificReasonBn: 'ডাবের পানি প্রস্রাবের অ্যাসিডিটি কমায় এবং প্রাকৃতিক মূত্রবর্ধক (Diuretic) হিসেবে বালুকণা বের করে দেয়।',
  },
  {
    id: 'stone_3',
    category: 'HIGH_OXALATE_LIMIT',
    categoryLabelBn: '⚠️ উচ্চ অক্সালেট সীমিতকরণ',
    nameBn: 'পালং শাক ও অতিরিক্ত পুঁইশাক',
    actionBn: 'পালং শাক রান্না করার আগে ভালো করে ভাপ দিয়ে পানি ফেলে দিন',
    scientificReasonBn: 'পালং শাকে প্রচুর অক্সালেট থাকে। ভাপ দিলে দ্রবণীয় অক্সালেটের সিংহভাগ পানিতে বের হয়ে যায়।',
  },
  {
    id: 'stone_4',
    category: 'HIGH_OXALATE_LIMIT',
    categoryLabelBn: '⚠️ উচ্চ অক্সালেট সীমিতকরণ',
    nameBn: 'কাঁচা টমেটো ও বেগুনের বীজ',
    actionBn: 'সালাদে টমেটোর ভেতরের বীজ ফেলে শাঁসটুকু গ্রহণ করুন',
    scientificReasonBn: 'টমেটোর বীজে অদ্রবণীয় অক্সালেট থাকে যা পাথর তৈরিতে সহায়তা করে।',
  },
  {
    id: 'stone_5',
    category: 'HYDRATION_RULE',
    categoryLabelBn: '💧 হাইড্রেশন গোল্ডেন রুল',
    nameBn: 'ক্যালসিয়াম ও অক্সালেট একসাথে গ্রহণ',
    actionBn: 'অক্সালেটযুক্ত খাবার খাওয়ার সময় সামান্য দই বা দুধ সাথে রাখুন',
    scientificReasonBn: 'খাদ্যের ক্যালসিয়াম ও অক্সালেট পাকস্থলীতেই একসাথে বাইন্ড হয়ে মল দিয়ে বের হয়ে যায়, ফলে কিডনিতে পৌঁছায় না।',
  },
  {
    id: 'stone_6',
    category: 'HYDRATION_RULE',
    categoryLabelBn: '💧 হাইড্রেশন গোল্ডেন রুল',
    nameBn: 'কাঁচা লবণ ও সোডিয়াম বর্জন',
    actionBn: 'পাতে অতিরিক্ত কাঁচা লবণ খাওয়া বন্ধ করুন',
    scientificReasonBn: 'অতিরিক্ত সোডিয়াম প্রস্রাব দিয়ে ক্যালসিয়াম লিক করায়, যা পাথর সৃষ্টির প্রধান অনুঘটক।',
  },
];
