/**
 * WhatsApp Share Card Generator Modal
 * Generates beautiful, branded share cards and pre-formatted WhatsApp messages
 * for Session Balance, Workout Splits, and Payment Receipts.
 */

import React, { useRef, useState } from 'react';
import {
  Modal,
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Share,
  Linking,
  Platform,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import * as Haptics from 'expo-haptics';
import * as Clipboard from 'expo-clipboard';
import ViewShot, { type ViewShotRef } from 'react-native-view-shot';

import { Vital, TrainingTheme } from '@/constants/vital-theme';
import { useTrainerStore } from '@/stores/trainer-store';
import type {
  AthleteClientDossier,
  PtPaymentRecord,
  AssignedProgram,
} from '@/types/trainer';

const C = Vital.colors;
const F = Vital.fonts;

export type WhatsAppShareMode = 'SESSION_BALANCE' | 'WORKOUT_SPLIT' | 'PAYMENT_RECEIPT';

interface WhatsAppShareCardModalProps {
  visible: boolean;
  onClose: () => void;
  client: AthleteClientDossier | null;
  mode?: WhatsAppShareMode;
  paymentRecord?: PtPaymentRecord;
  assignedProgram?: AssignedProgram;
}

export function WhatsAppShareCardModal({
  visible,
  onClose,
  client,
  mode: initialMode = 'SESSION_BALANCE',
  paymentRecord,
  assignedProgram,
}: WhatsAppShareCardModalProps) {
  const { profile } = useTrainerStore();
  const viewShotRef = useRef<ViewShotRef>(null);

  const [currentMode, setCurrentMode] = useState<WhatsAppShareMode>(initialMode);
  const [isCapturing, setIsCapturing] = useState(false);

  // Sync mode when modal opens
  React.useEffect(() => {
    if (initialMode) {
      setCurrentMode(initialMode);
    }
  }, [initialMode, visible]);

  if (!client) return null;

  const pkg = client.package;
  const progressPct = pkg.totalSessions > 0 ? Math.round((pkg.completedSessions / pkg.totalSessions) * 100) : 0;
  const isExpiringSoon = pkg.remainingSessions <= 2;

  // Clean phone number for WhatsApp deep link (+880...)
  const getCleanPhone = (phoneStr: string) => {
    let clean = phoneStr.replace(/[^0-9]/g, '');
    if (clean.startsWith('01')) {
      clean = '88' + clean;
    } else if (clean.startsWith('880')) {
      // already fine
    } else if (!clean.startsWith('88')) {
      clean = '880' + clean;
    }
    return clean;
  };

  // Generate WhatsApp Markdown Text
  const generateFormattedMessage = (): string => {
    const coachName = profile.name || 'Coach';
    const gymName = profile.gymAffiliation || 'Vital Fitness Elite Studio';

    if (currentMode === 'SESSION_BALANCE') {
      return (
`🏋️‍♂️ *VITAL FITNESS — PERSONAL TRAINING LEDGER* 🏋️‍♂️
────────────────────────
👤 *Athlete:* ${client.name}
🎯 *Goal:* ${client.goal} (${client.currentPhase})
🏆 *Trainer:* ${coachName} (${gymName})
📅 *Date:* ${new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })}

📊 *SESSION PROGRESS:*
• Package: ${pkg.packageName || pkg.packageType}
• Total Booked: *${pkg.totalSessions} Sessions*
• Completed: *${pkg.completedSessions} Sessions* ✅
• Remaining: *${pkg.remainingSessions} Sessions* ⏳
• Progress: ${progressPct}% Completed

${isExpiringSoon ? '⚠️ *RENEWAL NOTICE:* Your PT package has *' + pkg.remainingSessions + ' session(s) left*. Please renew before ' + pkg.expiryDate + ' to reserve your preferred peak training slot!\n' : ''}
💳 *Payment Status:* ${pkg.isPaid ? 'Verified Paid ✓' : 'Pending'}
────────────────────────
_Generated by Vital Fitness Coach Operating System_`
      );
    }

    if (currentMode === 'PAYMENT_RECEIPT') {
      const pay = paymentRecord || (pkg.paymentLog && pkg.paymentLog[0]);
      const amount = pay ? pay.amountBdt : pkg.priceBdt;
      const method = pay ? pay.method : 'bKash';
      const trxId = pay?.transactionId ? `• TrxID / Ref: *${pay.transactionId}*` : '';
      const payDate = pay?.date || pkg.startDate;

      return (
`🧾 *VITAL FITNESS — OFFICIAL PAYMENT RECEIPT* 🧾
────────────────────────
👤 *Athlete:* ${client.name}
🏆 *Coach:* ${coachName}
🏢 *Facility:* ${gymName}
📅 *Receipt Date:* ${payDate}

💰 *PAYMENT SUMMARY:*
• Package: *${pkg.packageName || pkg.packageType} (${pkg.totalSessions} Sessions)*
• Amount Paid: *৳${amount.toLocaleString()} BDT* ✅
• Payment Method: *${method}*
${trxId}
• Status: *CLEARED & RECORDED* 🛡️

Thank you for your commitment to elite fitness progress!
────────────────────────
_Vital Fitness Coach Operating System_`
      );
    }

    if (currentMode === 'WORKOUT_SPLIT') {
      const prog = assignedProgram;
      return (
`💪 *VITAL FITNESS — CUSTOM WORKOUT BLUEPRINT* 💪
────────────────────────
👤 *Athlete:* ${client.name}
🎯 *Phase:* ${client.currentPhase}
🏆 *Coach:* ${coachName}

📋 *PRESCRIPTION OVERVIEW:*
• Split: *${prog?.splitTitle || 'Custom Periodized Split'}*
• Focus: *${client.goal} & Progressive Overload*
• Notes: ${prog?.notes || client.notes || 'Focus on controlled eccentric tempo (3-1-1).'}

🔥 *Coach Guidelines:*
1. Warm up 5-8 mins prior to heavy compound working sets.
2. Hydrate with minimum 2.5L-3L water daily.
3. Report any joint discomfort immediately before pushing loads.
────────────────────────
_Train Hard, Train Safe • Vital Fitness_`
      );
    }

    return '';
  };

  const handleSendToWhatsApp = async () => {
    void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium).catch(() => {});
    const phone = getCleanPhone(client.phone);
    const message = generateFormattedMessage();
    const encoded = encodeURIComponent(message);
    const whatsappUrl = `whatsapp://send?phone=${phone}&text=${encoded}`;
    const webFallbackUrl = `https://api.whatsapp.com/send?phone=${phone}&text=${encoded}`;

    try {
      const supported = await Linking.canOpenURL(whatsappUrl);
      if (supported) {
        await Linking.openURL(whatsappUrl);
      } else {
        await Linking.openURL(webFallbackUrl);
      }
    } catch {
      Alert.alert('WhatsApp Not Available', 'Opening web browser link fallback...', [
        {
          text: 'Open Web',
          onPress: () => Linking.openURL(webFallbackUrl),
        },
        { text: 'Cancel', style: 'cancel' },
      ]);
    }
  };

  const handleCopyText = async () => {
    void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
    const text = generateFormattedMessage();
    await Clipboard.setStringAsync(text);
    Alert.alert('Copied to Clipboard!', 'Message is ready to paste anywhere on WhatsApp or Messenger.');
  };

  const handleCaptureAndShare = async () => {
    if (!viewShotRef.current) return;
    try {
      setIsCapturing(true);
      void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium).catch(() => {});
      const uri = await viewShotRef.current.capture?.();
      setIsCapturing(false);

      if (uri) {
        await Share.share({
          url: uri,
          message: generateFormattedMessage(),
          title: `Vital Fitness - ${client.name} Card`,
        });
      }
    } catch {
      setIsCapturing(false);
      // fallback to sharing text
      await Share.share({
        message: generateFormattedMessage(),
      });
    }
  };

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={styles.modalOverlay}>
        <SafeAreaView style={styles.modalContent}>
          {/* MODAL HEADER */}
          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <View style={styles.whatsappIconCircle}>
                <MaterialIcons name="share" size={20} color="#25D366" />
              </View>
              <View>
                <Text style={styles.headerTitle}>WHATSAPP SHARE CARD</Text>
                <Text style={styles.headerSub}>Instant 1-Tap Client Dispatch</Text>
              </View>
            </View>
            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <MaterialIcons name="close" size={22} color={C.onSurface} />
            </TouchableOpacity>
          </View>

          {/* MODE SELECTOR TABS */}
          <View style={styles.modeTabs}>
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => {
                void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
                setCurrentMode('SESSION_BALANCE');
              }}
              style={[styles.modeTab, currentMode === 'SESSION_BALANCE' && styles.modeTabActive]}>
              <MaterialIcons
                name="schedule"
                size={16}
                color={currentMode === 'SESSION_BALANCE' ? '#89FE00' : C.onSurfaceVariant}
              />
              <Text
                style={[
                  styles.modeTabText,
                  currentMode === 'SESSION_BALANCE' && styles.modeTabTextActive,
                ]}>
                Session Balance
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => {
                void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
                setCurrentMode('PAYMENT_RECEIPT');
              }}
              style={[styles.modeTab, currentMode === 'PAYMENT_RECEIPT' && styles.modeTabActive]}>
              <MaterialIcons
                name="receipt-long"
                size={16}
                color={currentMode === 'PAYMENT_RECEIPT' ? '#89FE00' : C.onSurfaceVariant}
              />
              <Text
                style={[
                  styles.modeTabText,
                  currentMode === 'PAYMENT_RECEIPT' && styles.modeTabTextActive,
                ]}>
                Money Receipt
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => {
                void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
                setCurrentMode('WORKOUT_SPLIT');
              }}
              style={[styles.modeTab, currentMode === 'WORKOUT_SPLIT' && styles.modeTabActive]}>
              <MaterialIcons
                name="fitness-center"
                size={16}
                color={currentMode === 'WORKOUT_SPLIT' ? '#89FE00' : C.onSurfaceVariant}
              />
              <Text
                style={[
                  styles.modeTabText,
                  currentMode === 'WORKOUT_SPLIT' && styles.modeTabTextActive,
                ]}>
                Workout Split
              </Text>
            </TouchableOpacity>
          </View>

          {/* PREVIEW CONTAINER */}
          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.previewScroll}>
            <Text style={styles.previewLabel}>LIVE CARD PREVIEW</Text>

            <ViewShot
              ref={viewShotRef}
              options={{ format: 'png', quality: 0.95 }}
              style={styles.cardCaptureContainer}>
              <View style={styles.cardHeader}>
                <View style={styles.badgeRow}>
                  <View style={styles.brandBadge}>
                    <MaterialIcons name="bolt" size={14} color="#89FE00" />
                    <Text style={styles.brandBadgeText}>VITAL COACH OS</Text>
                  </View>
                  <Text style={styles.cardDate}>
                    {new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'short' })}
                  </Text>
                </View>

                <Text style={styles.cardClientName}>{client.name}</Text>
                <Text style={styles.cardClientMeta}>
                  {client.goal} • {client.currentPhase}
                </Text>
              </View>

              {/* CARD SPECIFIC CONTENT */}
              {currentMode === 'SESSION_BALANCE' && (
                <View style={styles.cardBody}>
                  <View style={styles.sessionCounterBox}>
                    <View style={styles.countBlock}>
                      <Text style={styles.countNum}>{pkg.completedSessions}</Text>
                      <Text style={styles.countLbl}>COMPLETED</Text>
                    </View>
                    <View style={styles.countDivider} />
                    <View style={styles.countBlock}>
                      <Text style={[styles.countNum, { color: isExpiringSoon ? '#FF5C5C' : '#89FE00' }]}>
                        {pkg.remainingSessions}
                      </Text>
                      <Text style={styles.countLbl}>REMAINING</Text>
                    </View>
                    <View style={styles.countDivider} />
                    <View style={styles.countBlock}>
                      <Text style={styles.countNum}>{pkg.totalSessions}</Text>
                      <Text style={styles.countLbl}>TOTAL PACK</Text>
                    </View>
                  </View>

                  {/* PROGRESS BAR */}
                  <View style={styles.progressBarBg}>
                    <View style={[styles.progressBarFill, { width: `${Math.min(100, progressPct)}%` }]} />
                  </View>

                  {isExpiringSoon && (
                    <View style={styles.renewalAlertCard}>
                      <MaterialIcons name="notification-important" size={18} color="#FF5C5C" />
                      <Text style={styles.renewalAlertText}>
                        Package expiring soon ({pkg.remainingSessions} left). Renewal due by {pkg.expiryDate}.
                      </Text>
                    </View>
                  )}

                  <View style={styles.cardMetaRow}>
                    <Text style={styles.cardMetaKey}>Valid Until:</Text>
                    <Text style={styles.cardMetaVal}>{pkg.expiryDate}</Text>
                  </View>
                </View>
              )}

              {currentMode === 'PAYMENT_RECEIPT' && (
                <View style={styles.cardBody}>
                  <View style={styles.receiptBox}>
                    <Text style={styles.receiptTitle}>OFFICIAL PAYMENT VOUCHER</Text>
                    <Text style={styles.receiptAmount}>
                      ৳{(paymentRecord?.amountBdt || pkg.priceBdt).toLocaleString()} BDT
                    </Text>
                    <View style={styles.paidBadge}>
                      <MaterialIcons name="check-circle" size={14} color="#89FE00" />
                      <Text style={styles.paidBadgeText}>VERIFIED PAYMENT</Text>
                    </View>
                  </View>

                  <View style={styles.receiptDetails}>
                    <View style={styles.receiptRow}>
                      <Text style={styles.receiptKey}>Package:</Text>
                      <Text style={styles.receiptVal}>{pkg.packageName || pkg.packageType} ({pkg.totalSessions} Sessions)</Text>
                    </View>
                    <View style={styles.receiptRow}>
                      <Text style={styles.receiptKey}>Payment Method:</Text>
                      <Text style={[styles.receiptVal, { color: '#89FE00' }]}>
                        {paymentRecord?.method || 'bKash Personal'}
                      </Text>
                    </View>
                    {paymentRecord?.transactionId && (
                      <View style={styles.receiptRow}>
                        <Text style={styles.receiptKey}>Transaction ID:</Text>
                        <Text style={styles.receiptVal}>{paymentRecord.transactionId}</Text>
                      </View>
                    )}
                    <View style={styles.receiptRow}>
                      <Text style={styles.receiptKey}>Date Recorded:</Text>
                      <Text style={styles.receiptVal}>{paymentRecord?.date || pkg.startDate}</Text>
                    </View>
                  </View>
                </View>
              )}

              {currentMode === 'WORKOUT_SPLIT' && (
                <View style={styles.cardBody}>
                  <View style={styles.workoutSplitBox}>
                    <Text style={styles.splitTitleText}>{assignedProgram?.splitTitle || '4-Day Hypertrophy Split'}</Text>
                    <Text style={styles.splitSubText}>Custom Periodized Mesocycle</Text>
                  </View>
                  <View style={styles.guidelinesBox}>
                    <Text style={styles.guidelinesHeader}>📋 COACH DIRECTIVES:</Text>
                    <Text style={styles.guidelinesItem}>• Warm up rotator cuff & joint capsules 5 mins.</Text>
                    <Text style={styles.guidelinesItem}>• Keep 1-2 RIR on compound working sets.</Text>
                    <Text style={styles.guidelinesItem}>• Log weight jumps in session review.</Text>
                  </View>
                </View>
              )}

              {/* CARD FOOTER */}
              <View style={styles.cardFooter}>
                <View>
                  <Text style={styles.footerCoachName}>{profile.name || 'Certified Gym Coach'}</Text>
                  <Text style={styles.footerGym}>{profile.gymAffiliation || 'Vital Fitness Studio'}</Text>
                </View>
                <View style={styles.verifiedIcon}>
                  <MaterialIcons name="verified" size={18} color="#89FE00" />
                </View>
              </View>
            </ViewShot>
          </ScrollView>

          {/* ACTION TOOLBAR */}
          <View style={styles.actionToolbar}>
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={handleCopyText}
              style={styles.copyBtn}>
              <MaterialIcons name="content-copy" size={18} color={C.onSurface} />
              <Text style={styles.copyBtnText}>Copy Text</Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={handleCaptureAndShare}
              style={styles.shareImageBtn}>
              <MaterialIcons name="image" size={18} color="#A78BFA" />
              <Text style={styles.shareImageBtnText}>Share Card</Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={handleSendToWhatsApp}
              style={styles.sendWhatsAppBtn}>
              <MaterialIcons name="chat" size={18} color="#002233" />
              <Text style={styles.sendWhatsAppBtnText}>Send WhatsApp</Text>
            </TouchableOpacity>
          </View>
        </SafeAreaView>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#0A121A',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '90%',
    paddingBottom: Platform.OS === 'ios' ? 10 : 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  whatsappIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(37, 211, 102, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#89FE00',
    fontFamily: F.sansBold,
    fontSize: 14,
    letterSpacing: 0.5,
  },
  headerSub: {
    color: C.onSurfaceVariant,
    fontSize: 12,
    fontFamily: F.sansRegular,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
  },
  modeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  modeTabActive: {
    backgroundColor: 'rgba(137, 254, 0, 0.12)',
    borderColor: '#89FE00',
  },
  modeTabText: {
    color: C.onSurfaceVariant,
    fontSize: 11,
    fontFamily: F.sansMedium,
  },
  modeTabTextActive: {
    color: '#89FE00',
    fontFamily: F.sansBold,
  },
  previewScroll: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  previewLabel: {
    color: C.onSurfaceVariant,
    fontSize: 10,
    fontFamily: F.sansBold,
    letterSpacing: 1,
    marginBottom: 8,
    textAlign: 'center',
  },
  cardCaptureContainer: {
    backgroundColor: '#0E1A26',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  cardHeader: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    paddingBottom: 12,
    marginBottom: 14,
  },
  badgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  brandBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(137, 254, 0, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  brandBadgeText: {
    color: '#89FE00',
    fontSize: 9,
    fontFamily: F.sansBold,
    letterSpacing: 0.5,
  },
  cardDate: {
    color: C.onSurfaceVariant,
    fontSize: 11,
    fontFamily: F.sansRegular,
  },
  cardClientName: {
    color: C.onSurface,
    fontSize: 18,
    fontFamily: F.sansBold,
  },
  cardClientMeta: {
    color: '#00B4D8',
    fontSize: 12,
    fontFamily: F.sansMedium,
    marginTop: 2,
  },
  cardBody: {
    marginBottom: 14,
  },
  sessionCounterBox: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  countBlock: {
    alignItems: 'center',
  },
  countNum: {
    color: C.onSurface,
    fontSize: 22,
    fontFamily: F.sansBold,
  },
  countLbl: {
    color: C.onSurfaceVariant,
    fontSize: 9,
    fontFamily: F.sansBold,
    letterSpacing: 0.5,
    marginTop: 2,
  },
  countDivider: {
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  progressBarBg: {
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
    marginBottom: 12,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#89FE00',
    borderRadius: 4,
  },
  renewalAlertCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 92, 92, 0.12)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 92, 92, 0.3)',
  },
  renewalAlertText: {
    color: '#FF7B7B',
    fontSize: 11,
    fontFamily: F.sansMedium,
    flex: 1,
  },
  cardMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  cardMetaKey: {
    color: C.onSurfaceVariant,
    fontSize: 12,
    fontFamily: F.sansRegular,
  },
  cardMetaVal: {
    color: C.onSurface,
    fontSize: 12,
    fontFamily: F.sansBold,
  },
  receiptBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(137, 254, 0, 0.08)',
    borderRadius: 14,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(137, 254, 0, 0.2)',
  },
  receiptTitle: {
    color: C.onSurfaceVariant,
    fontSize: 10,
    fontFamily: F.sansBold,
    letterSpacing: 1,
  },
  receiptAmount: {
    color: '#89FE00',
    fontSize: 26,
    fontFamily: F.sansBold,
    marginVertical: 4,
  },
  paidBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(137, 254, 0, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  paidBadgeText: {
    color: '#89FE00',
    fontSize: 10,
    fontFamily: F.sansBold,
  },
  receiptDetails: {
    gap: 8,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  receiptKey: {
    color: C.onSurfaceVariant,
    fontSize: 12,
    fontFamily: F.sansRegular,
  },
  receiptVal: {
    color: C.onSurface,
    fontSize: 12,
    fontFamily: F.sansBold,
  },
  workoutSplitBox: {
    backgroundColor: 'rgba(0, 180, 216, 0.1)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 180, 216, 0.25)',
  },
  splitTitleText: {
    color: '#00B4D8',
    fontSize: 15,
    fontFamily: F.sansBold,
  },
  splitSubText: {
    color: C.onSurfaceVariant,
    fontSize: 11,
    fontFamily: F.sansRegular,
    marginTop: 2,
  },
  guidelinesBox: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 10,
    padding: 10,
    gap: 4,
  },
  guidelinesHeader: {
    color: '#FFB800',
    fontSize: 11,
    fontFamily: F.sansBold,
    marginBottom: 2,
  },
  guidelinesItem: {
    color: C.onSurface,
    fontSize: 11,
    fontFamily: F.sansRegular,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
    paddingTop: 10,
  },
  footerCoachName: {
    color: C.onSurface,
    fontSize: 12,
    fontFamily: F.sansBold,
  },
  footerGym: {
    color: C.onSurfaceVariant,
    fontSize: 10,
    fontFamily: F.sansRegular,
  },
  verifiedIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(137, 254, 0, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionToolbar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  copyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  copyBtnText: {
    color: C.onSurface,
    fontSize: 12,
    fontFamily: F.sansBold,
  },
  shareImageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(167, 139, 250, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  shareImageBtnText: {
    color: '#A78BFA',
    fontSize: 12,
    fontFamily: F.sansBold,
  },
  sendWhatsAppBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#89FE00',
  },
  sendWhatsAppBtnText: {
    color: '#002233',
    fontSize: 13,
    fontFamily: F.sansBold,
  },
});
